targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
          field_rename: screamingSnake
      freezed:
        options:
          union_key: type
          union_value_case: screaming_snake