targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
          create_to_json: true
          field_rename: screamingSnake
      json_serializable|json_enum:
        options:
          always_create: true
          field_rename: screamingSnake
      freezed:
        options:
          immutable: true
          union_key: type
          to_string_override: false
          union_value_case: screaming_snake
          maybe_map: true
          maybe_when: true