targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
          create_to_json: true
          field_rename: screamingSnake
      freezed:
        options:

          dsdlkf: true
          immutable: true
          toString: false
          union_key: type
          union_value_case: screaming_snake
          maybe_map: true
          maybe_when: true