name: picker
description: Yeni Picker Deneyimi!
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.5.2+164

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #Info Dependencies
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  connectivity_plus: ^6.0.1
  android_id: ^0.3.6

  #Network Dependencies
  dio: ^5.1.1

  #Localizations Dependencies
  easy_localization: ^3.0.3

  #Utils Dependencies
  crypto: ^3.0.3
  copy_with_extension: ^5.0.3
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.8
  google_fonts: ^6.1.0
  path: ^1.8.3
  kartal: ^3.2.0
  path_provider: ^2.1.1
  open_file_plus: ^3.4.1
  permission_handler: ^11.0.1
  share_plus: ^7.2.1

  # Component  Dependencies
  awesome_dialog: ^3.1.0
  shimmer: ^3.0.0
  fl_chart: ^0.66.0
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.0.0
  lottie: ^3.0.0
  wave: ^0.2.2

  #State Management Dependencies
  get: ^4.6.5
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  #Hive Caching Dependencies
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  image_picker: ^1.0.1
  intl: any

  #Json Serialization Dependencies
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  #QR
  qr_code_scanner: ^1.0.1

  flutter_image_compress: ^2.0.3
  timezone: ^0.9.1
  syncfusion_flutter_pdfviewer: ^24.1.45
  collection: ^1.17.2
  app_tracking_transparency: ^2.0.4
  app_settings: ^5.1.1

  #Firebase
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  firebase_messaging: ^14.7.2

  quill_html_editor: ^2.2.7
  freezed_annotation: ^2.4.1
  injectable: ^2.2.0
  get_it: ^7.6.0
  uuid: ^4.1.0
  number_text_input_formatter: ^1.0.0+7
  talker_dio_logger: ^4.0.2
  stack_trace: ^1.11.0
  location: ^5.0.3
  google_maps_flutter: ^2.5.3
  encrypt: ^5.0.3
  pointycastle: ^3.7.4
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  label_marker: ^1.0.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.3
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.3
  hive_generator: ^2.0.0
  mobx_codegen: ^2.2.0
  change_app_package_name: ^1.1.0
  rename: ^3.0.0
  freezed: ^2.4.1
  injectable_generator: ^2.3.0
  flutter_gen_runner: ^5.3.2

flutter_launcher_icons:
  image_path: "assets/app_icon/beyaz_1024.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#bd3d17"

  web:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"
  windows:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#201A19"
  image: "assets/app_icon/beyaz_400.png"
  image_dark: "assets/app_icon/beyaz_400.png"
  fill: false
  android: true
  ios: true
  web: true
  macos: false
  windows: true
  linux: false
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/icons/PickerSvgIcon/
    - assets/icons/PickerSvgIcon/AnaMenu/
    - assets/lotties/
    - assets/icons/
    - assets/app_icon/
    - locales/EN_US.json
    - locales/TR.json
    - assets/translations/
    # - shorebird.yaml

flutter_gen:
  output: lib/core/gen/ # Optional (defaults to lib/flutter_gen)

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
flutter_intl:
  enabled: true
