name: picker
description: Yeni Picker Deneyimi!

publish_to: "none"

version: 1.8.17+301

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #Info Dependencies
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.1
  # platform_device_id: ^1.0.1
  android_id: ^0.4.0

  #Network Dependencies
  dio: ^5.7.0

  #Localizations Dependencies
  easy_localization: ^3.0.3

  #Utils Dependencies
  crypto: ^3.0.3
  copy_with_extension: ^6.0.0
  flutter_svg: ^2.0.8
  google_fonts: ^6.1.0
  path: ^1.8.6
  kartal: ^4.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  share_plus: ^10.1.1

  # Component  Dependencies
  awesome_dialog: ^3.2.1
  shimmer: ^3.0.0
  fl_chart: ^0.70.1
  flutter_staggered_animations: ^1.1.1
  flutter_slidable:
    git:
      url: "https://github.com/letsar/flutter_slidable"
  lottie: ^3.0.0
  wave: ^0.2.2

  #State Management Dependencies
  get: ^4.6.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  #Hive Caching Dependencies
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  image_picker: ^1.0.1
  intl: any

  #Json Serialization Dependencies
  json_annotation: ^4.9.0

  #QR
  # qr_code_scanner: ^1.0.1
  mobile_scanner: ^6.0.2
  flutter_image_compress: ^2.0.3
  syncfusion_flutter_pdfviewer: ^28.1.37
  collection: ^1.17.2
  app_tracking_transparency: ^2.0.4
  app_settings: ^5.1.1

  #Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  firebase_app_check: ^0.3.1+4

  quill_html_editor:
    path: packages/quill_html_editor
  freezed_annotation: ^2.4.1
  uuid: ^4.1.0
  number_text_input_formatter: ^1.0.0+7
  talker_dio_logger: ^4.0.2
  location: ^7.0.1
  google_maps_flutter: ^2.5.3
  encrypt: ^5.0.3
  pointycastle: ^3.7.4
  # cryptography: ^2.7.0
  # cryptography_flutter: ^2.3.2
  url_launcher: ^6.3.0
  # url_strategy: ^0.3.0
  json: ^0.20.2
  syncfusion_localizations: ^28.1.39
  open_filex: ^4.5.0
  animated_text_kit: ^4.2.2
  text_scroll: ^0.2.0
  package_info_plus: ^8.1.0
# dependency_overrides:
# google_maps_flutter_ios: 2.3.0
# rive: 0.13.15
# rive_common: 0.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  copy_with_extension_gen: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.3
  hive_generator: ^2.0.0
  mobx_codegen: ^2.6.1
  change_app_package_name: ^1.1.0
  rename: ^3.0.0
  freezed: ^2.5.2
  injectable_generator: ^2.3.0
  flutter_gen_runner: ^5.3.2
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  image_path: "assets/app_icon/beyaz_1024.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#bd3d17"

  web:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"
  windows:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#201A19"
  image: "assets/app_icon/beyaz_400.png"
  image_dark: "assets/app_icon/beyaz_400.png"
  fill: false
  android: true
  ios: true
  web: true
  macos: false
  windows: true
  linux: false
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/icons/PickerSvgIcon/
    - assets/icons/PickerSvgIcon/AnaMenu/
    - assets/lotties/
    - assets/icons/
    - assets/background/
    - assets/app_icon/
    - locales/EN_US.json
    - locales/TR.json
    - assets/translations/
    # - shorebird.yaml

flutter_gen:
  output: lib/core/gen/

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
flutter_intl:
  enabled: true
