name: picker
description: Yeni Picker Deneyimi!

publish_to: "none"

version: 1.9.20+301

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #Info Dependencies
  device_info_plus: ^11.4.0
  connectivity_plus: ^6.0.1
  android_id: ^0.4.0

  #Network Dependencies
  dio: ^5.7.0

  #Localizations Dependencies
  easy_localization: ^3.0.3

  #Utils Dependencies
  crypto: ^3.0.3
  copy_with_extension: ^9.1.0
  flutter_svg: ^2.0.8
  google_fonts: ^6.1.0
  path: ^1.8.6
  kartal:
    git:
      url: https://github.com/VB10/kartal.git
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  share_plus: ^10.1.1

  # Component  Dependencies
  awesome_dialog: ^3.2.1
  shimmer: ^3.0.0
  fl_chart: ^1.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^4.0.0
  lottie: ^3.0.0
  wave: ^0.2.2

  #State Management Dependencies
  get: ^4.6.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  #Hive Caching Dependencies
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1

  image_picker: ^1.0.1
  intl: any

  #Json Serialization Dependencies
  json_annotation: ^4.9.0

  #QR
  mobile_scanner: ^7.0.0
  flutter_image_compress: ^2.0.3
  syncfusion_flutter_pdfviewer: ^29.2.5
  collection: ^1.17.2
  app_tracking_transparency: ^2.0.4
  app_settings: ^6.1.1

  #Firebase
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  firebase_app_check: ^0.4.0
  print_bluetooth_thermal: ^1.1.6
  flutter_blue_plus: ^1.35.3
  esc_pos_utils_plus: ^2.0.4
  quill_html_editor:
    path: packages/quill_html_editor
  freezed_annotation: ^3.0.0
  uuid: ^4.1.0
  number_text_input_formatter: ^1.0.0+7
  talker_dio_logger: ^4.0.2
  location: ^8.0.0
  google_maps_flutter: ^2.5.3
  encrypt: ^5.0.3
  flutter_credit_card: ^4.1.0
  pointycastle: ^3.7.4
  url_launcher: ^6.3.0
  syncfusion_localizations: ^29.2.5
  open_filex: ^4.7.0
  animated_text_kit: ^4.2.2
  text_scroll: ^0.2.0
  package_info_plus: ^8.1.0
  geolocator: ^14.0.0
  get_it: ^8.0.3
  app_links: ^6.4.0

  webview_flutter: ^4.9.0
  web: ^1.1.0
  webview_flutter_web: ^0.2.3+4
  
# dependency_overrides:
# google_maps_flutter_ios: 2.3.0
# rive: 0.13.15
# rive_common: 0.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.15
  copy_with_extension_gen: ^9.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  # flutter_native_splash: ^2.3.3
  hive_ce_generator: ^1.9.2
  mobx_codegen: ^2.6.1
  change_app_package_name: ^1.1.0
  rename: ^3.0.0
  freezed: ^3.0.0-0.0.dev
  injectable_generator: ^2.3.0
  flutter_gen_runner: ^5.3.2
  very_good_analysis: ^9.0.0
  pigeon: ^26.0.1
  analyzer: ^7.4.5

flutter_launcher_icons:
  image_path: "assets/app_icon/beyaz_1024.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#bd3d17"

  web:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"
  windows:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon/beyaz_1024.png"

# flutter_native_splash:
#   color: "#ffffff"
#   color_dark: "#201A19"
#   image: "assets/app_icon/beyaz_400.png"
#   image_dark: "assets/app_icon/beyaz_400.png"
#   fill: false
#   android: true
#   ios: true
#   web: true
#   macos: false
#   windows: true
#   linux: false
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/icons/PickerSvgIcon/
    - assets/icons/PickerSvgIcon/AnaMenu/
    - assets/lotties/
    - assets/icons/
    - assets/background/
    - assets/app_icon/
    - locales/EN_US.json
    - locales/TR.json
    - assets/translations/
    # - shorebird.yaml

flutter_gen:
  output: lib/core/gen/

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
flutter_intl:
  enabled: true
