name: picker
description: Yeni Picker Deneyimi!
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.3.0+27

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #Info Dependencies
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  connectivity_plus: ^5.0.0
  android_id: ^0.3.5

  #Network Dependencies
  dio: ^5.1.1

  #Utils Dependencies
  crypto: ^3.0.2
  copy_with_extension: ^5.0.3
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.5
  google_fonts: ^6.1.0
  path: ^1.8.3
  kartal: ^3.2.0
  path_provider: ^2.0.15
  open_file_plus: ^3.4.1
  permission_handler: ^11.0.0
  share_plus: ^7.0.2

  # Component  Dependencies
  awesome_dialog: ^3.0.2
  fl_chart: ^0.64.0
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.0.0
  lottie: ^2.3.1
  wave: ^0.2.2

  #State Management Dependencies
  get: ^4.6.5
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  #Hive Caching Dependencies
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  image_picker: ^1.0.1
  intl: any

  #Json Serialization Dependencies
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1

  #QR
  qr_code_scanner: ^1.0.1

  flutter_image_compress: ^2.0.3
  timezone: ^0.9.1
  syncfusion_flutter_pdfviewer: ^23.1.38
  collection: ^1.17.1
  app_tracking_transparency: ^2.0.4
  app_settings: ^5.0.0

  #Firebase
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.6.6

  #HTML Editor
  # html_editor_enhanced: ^2.5.1
  quill_html_editor: ^2.2.6
  freezed_annotation: ^2.4.1
  injectable: ^2.2.0
  get_it: ^7.6.0
  uuid: ^3.0.7
  number_text_input_formatter: ^1.0.0+7

flutter_launcher_icons:
  image_path: "assets/splash/pickerLogoTuruncu_512.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/splash/pickerLogoTuruncu_512.png"
  windows:
    generate: true
    image_path: "assets/splash/pickerLogoTuruncu_512.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/splash/pickerLogoTuruncu_512.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.3
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.3
  hive_generator: ^2.0.0
  mobx_codegen: ^2.2.0
  change_app_package_name: ^1.1.0
  rename: ^3.0.0
  freezed: ^2.4.1
  injectable_generator: ^2.3.0

flutter_native_splash:
  color: "#201A19"
  image: "assets/splash/pickerLogoTuruncu_512.png"
  fill: false
  android: true
  ios: true
  web: false
  macos: false
  windows: true
  linux: false
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/icons/PickerSvgIcon/
    - assets/icons/PickerSvgIcon/AnaMenu/