// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'e_belge_listesi_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_EBelgeListesiModel _$EBelgeListesiModelFromJson(Map<String, dynamic> json) =>
    _EBelgeListesiModel(
      ebelgeTuru: json['EBELGE_TURU'] as String?,
      inckeyno: (json['INCKEYNO'] as num?)?.toInt(),
      efatmasInckeyno: (json['EFATMAS_INCKEYNO'] as num?)?.toInt(),
      gelen: json['GELEN'] as String?,
      taslak: json['TASLAK'] as String?,
      gonderildi: json['GONDERILDI'] as String?,
      faturaIslendi: json['FATURA_ISLENDI'] as String?,
      dekontIslendi: json['DEKONT_ISLENDI'] as String?,
      iptalEdildi: json['IPTAL_EDILDI'] as String?,
      cevapKodu: (json['CEVAP_KODU'] as num?)?.toInt(),
      cevapAciklama: json['CEVAP_ACIKLAMA'] as String?,
      basariylaGonderildi: json['BASARIYLA_GONDERILDI'] as String?,
      onayDurumKodu: json['ONAY_DURUM_KODU'] as String?,
      onayAciklama: json['ONAY_ACIKLAMA'] as String?,
      resmiBelgeNo: json['RESMI_BELGE_NO'] as String?,
      tarih: json['TARIH'] == null
          ? null
          : DateTime.parse(json['TARIH'] as String),
      kayittarihi: json['KAYITTARIHI'] == null
          ? null
          : DateTime.parse(json['KAYITTARIHI'] as String),
      belgeTuru: json['BELGE_TURU'] as String?,
      cariAdi: json['CARI_ADI'] as String?,
      vergiNo: json['VERGI_NO'] as String?,
      cariIlce: json['CARI_ILCE'] as String?,
      cariIl: json['CARI_IL'] as String?,
      dovizKuru: (json['DOVIZ_KURU'] as num?)?.toDouble(),
      basimYapildi: json['BASIM_YAPILDI'] as String?,
      genelToplam: (json['GENEL_TOPLAM'] as num?)?.toDouble(),
      kdvTutari: (json['KDV_TUTARI'] as num?)?.toDouble(),
      senaryo: json['SENARYO'] as String?,
      zarfid: json['ZARFID'] as String?,
      uuid: json['UUID'] as String?,
      faturaTipi: json['FATURA_TIPI'] as String?,
      kayityapankul: json['KAYITYAPANKUL'] as String?,
      kontrolEdildi: json['KONTROL_EDILDI'] as String?,
      kayitliCariKodu: json['KAYITLI_CARI_KODU'] as String?,
      belgeNo: json['BELGE_NO'] as String?,
      islenenBelgeNo: json['ISLENEN_BELGE_NO'] as String?,
      cariKodu: json['CARI_KODU'] as String?,
      dovizTipi: (json['DOVIZ_TIPI'] as num?)?.toInt(),
      dovizAdi: json['DOVIZ_ADI'] as String?,
      dovizTutari: (json['DOVIZ_TUTARI'] as num?)?.toDouble(),
      iskontoTutari: (json['ISKONTO_TUTARI'] as num?)?.toDouble(),
      dekontJson: json['DEKONT_JSON'] as String?,
      kontrolAciklama: json['KONTROL_ACIKLAMA'] as String?,
      dizaynYolu: json['DIZAYN_YOLU'] as String?,
      gondermeDurumu: json['GONDERME_DURUMU'] as String?,
      zarfSilinebilir: json['ZARF_SILINEBILIR'] as String?,
      iptalTarihi: json['IPTAL_TARIHI'] == null
          ? null
          : DateTime.parse(json['IPTAL_TARIHI'] as String),
      eposta: json['EPOSTA'] as String?,
      eBelgeTuru: json['E_BELGE_TURU'] as String?,
      id: (json['ID'] as num?)?.toInt(),
      eFatMasId: (json['E_FAT_MAS_ID'] as num?)?.toInt(),
      eIrsMasId: (json['E_IRS_MAS_ID'] as num?)?.toInt(),
      kayitTarihi: json['KAYIT_TARIHI'] == null
          ? null
          : DateTime.parse(json['KAYIT_TARIHI'] as String),
      eFaturaIptalTarihi: json['E_FATURA_IPTAL_TARIHI'] == null
          ? null
          : DateTime.parse(json['E_FATURA_IPTAL_TARIHI'] as String),
      ilce: json['ILCE'] as String?,
      sehir: json['SEHIR'] as String?,
      kayitYapanKul: json['KAYIT_YAPAN_KUL'] as String?,
      gelenEFatKontrolEdildi: json['GELEN_E_FAT_KONTROL_EDILDI'] as String?,
      gelenEFatKontrolAciklama: json['GELEN_E_FAT_KONTROL_ACIKLAMA'] as String?,
      gonderimSekliEPosta: json['GONDERIM_SEKLI_E_POSTA'] as bool?,
      ePosta: json['E_POSTA'] as String?,
      islemKodu: (json['ISLEM_KODU'] as num?)?.toInt(),
      kutuTuru: json['KUTU_TURU'] as String?,
      aciklama: json['ACIKLAMA'] as String?,
      senaryoTipi: json['SENARYO_TIPI'] as String?,
      kopyaSayisi: (json['KOPYA_SAYISI'] as num?)?.toInt(),
      yaziciAdi: json['YAZICI_ADI'] as String?,
      dizaynNo: (json['DIZAYN_NO'] as num?)?.toInt(),
      dovizliOlustur: json['DOVIZLI_OLUSTUR'] as bool?,
      internetFaturasi: json['INTERNET_FATURASI'] as bool?,
      eirsBilgi: json['EIRS_BILGI'] == null
          ? null
          : EIrsaliyeBilgiModel.fromJson(
              json['EIRS_BILGI'] as Map<String, dynamic>,
            ),
    );

Map<String, dynamic> _$EBelgeListesiModelToJson(_EBelgeListesiModel instance) =>
    <String, dynamic>{
      'EBELGE_TURU': ?instance.ebelgeTuru,
      'INCKEYNO': ?instance.inckeyno,
      'EFATMAS_INCKEYNO': ?instance.efatmasInckeyno,
      'GELEN': ?instance.gelen,
      'TASLAK': ?instance.taslak,
      'GONDERILDI': ?instance.gonderildi,
      'FATURA_ISLENDI': ?instance.faturaIslendi,
      'DEKONT_ISLENDI': ?instance.dekontIslendi,
      'IPTAL_EDILDI': ?instance.iptalEdildi,
      'CEVAP_KODU': ?instance.cevapKodu,
      'CEVAP_ACIKLAMA': ?instance.cevapAciklama,
      'BASARIYLA_GONDERILDI': ?instance.basariylaGonderildi,
      'ONAY_DURUM_KODU': ?instance.onayDurumKodu,
      'ONAY_ACIKLAMA': ?instance.onayAciklama,
      'RESMI_BELGE_NO': ?instance.resmiBelgeNo,
      'TARIH': ?instance.tarih?.toIso8601String(),
      'KAYITTARIHI': ?instance.kayittarihi?.toIso8601String(),
      'BELGE_TURU': ?instance.belgeTuru,
      'CARI_ADI': ?instance.cariAdi,
      'VERGI_NO': ?instance.vergiNo,
      'CARI_ILCE': ?instance.cariIlce,
      'CARI_IL': ?instance.cariIl,
      'DOVIZ_KURU': ?instance.dovizKuru,
      'BASIM_YAPILDI': ?instance.basimYapildi,
      'GENEL_TOPLAM': ?instance.genelToplam,
      'KDV_TUTARI': ?instance.kdvTutari,
      'SENARYO': ?instance.senaryo,
      'ZARFID': ?instance.zarfid,
      'UUID': ?instance.uuid,
      'FATURA_TIPI': ?instance.faturaTipi,
      'KAYITYAPANKUL': ?instance.kayityapankul,
      'KONTROL_EDILDI': ?instance.kontrolEdildi,
      'KAYITLI_CARI_KODU': ?instance.kayitliCariKodu,
      'BELGE_NO': ?instance.belgeNo,
      'ISLENEN_BELGE_NO': ?instance.islenenBelgeNo,
      'CARI_KODU': ?instance.cariKodu,
      'DOVIZ_TIPI': ?instance.dovizTipi,
      'DOVIZ_ADI': ?instance.dovizAdi,
      'DOVIZ_TUTARI': ?instance.dovizTutari,
      'ISKONTO_TUTARI': ?instance.iskontoTutari,
      'DEKONT_JSON': ?instance.dekontJson,
      'KONTROL_ACIKLAMA': ?instance.kontrolAciklama,
      'DIZAYN_YOLU': ?instance.dizaynYolu,
      'GONDERME_DURUMU': ?instance.gondermeDurumu,
      'ZARF_SILINEBILIR': ?instance.zarfSilinebilir,
      'IPTAL_TARIHI': ?instance.iptalTarihi?.toIso8601String(),
      'EPOSTA': ?instance.eposta,
      'E_BELGE_TURU': ?instance.eBelgeTuru,
      'ID': ?instance.id,
      'E_FAT_MAS_ID': ?instance.eFatMasId,
      'E_IRS_MAS_ID': ?instance.eIrsMasId,
      'KAYIT_TARIHI': ?instance.kayitTarihi?.toIso8601String(),
      'E_FATURA_IPTAL_TARIHI': ?instance.eFaturaIptalTarihi?.toIso8601String(),
      'ILCE': ?instance.ilce,
      'SEHIR': ?instance.sehir,
      'KAYIT_YAPAN_KUL': ?instance.kayitYapanKul,
      'GELEN_E_FAT_KONTROL_EDILDI': ?instance.gelenEFatKontrolEdildi,
      'GELEN_E_FAT_KONTROL_ACIKLAMA': ?instance.gelenEFatKontrolAciklama,
      'GONDERIM_SEKLI_E_POSTA': ?instance.gonderimSekliEPosta,
      'E_POSTA': ?instance.ePosta,
      'ISLEM_KODU': ?instance.islemKodu,
      'KUTU_TURU': ?instance.kutuTuru,
      'ACIKLAMA': ?instance.aciklama,
      'SENARYO_TIPI': ?instance.senaryoTipi,
      'KOPYA_SAYISI': ?instance.kopyaSayisi,
      'YAZICI_ADI': ?instance.yaziciAdi,
      'DIZAYN_NO': ?instance.dizaynNo,
      'DOVIZLI_OLUSTUR': ?instance.dovizliOlustur,
      'INTERNET_FATURASI': ?instance.internetFaturasi,
      'EIRS_BILGI': ?instance.eirsBilgi?.toJson(),
    };
