// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class SewooPigeonCodecReader: FlutterStandardReader {
}

private class SewooPigeonCodecWriter: FlutterStandardWriter {
}

private class SewooPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SewooPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SewooPigeonCodecWriter(data: data)
  }
}

class SewooPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SewooPigeonCodec(readerWriter: SewooPigeonCodecReaderWriter())
}


/// Sewoo is a Bluetooth printer
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Sewoo {
  func printText(text: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func printImage(image: [Int64], completion: @escaping (Result<Bool, Error>) -> Void)
  func printPDF(pdfData: [Int64], width: Int64, height: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SewooSetup {
  static var codec: FlutterStandardMessageCodec { SewooPigeonCodec.shared }
  /// Sets up an instance of `Sewoo` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Sewoo?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let printTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.printText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        api.printText(text: textArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printTextChannel.setMessageHandler(nil)
    }
    let printImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.printImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageArg = args[0] as! [Int64]
        api.printImage(image: imageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printImageChannel.setMessageHandler(nil)
    }
    let printPDFChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.printPDF\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printPDFChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pdfDataArg = args[0] as! [Int64]
        let widthArg = args[1] as! Int64
        let heightArg = args[2] as! Int64
        api.printPDF(pdfData: pdfDataArg, width: widthArg, height: heightArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printPDFChannel.setMessageHandler(nil)
    }
  }
}
