// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct PrinterList {
  var printers: [PrinterDetails]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrinterList? {
    let printers = pigeonVar_list[0] as! [PrinterDetails]

    return PrinterList(
      printers: printers
    )
  }
  func toList() -> [Any?] {
    return [
      printers
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PrinterDetails {
  var connected: Bool
  var connectionID: Int64
  var name: String
  var modelNumber: String
  var serialNumber: String
  var width: Int64? = nil
  var height: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrinterDetails? {
    let connected = pigeonVar_list[0] as! Bool
    let connectionID = pigeonVar_list[1] as! Int64
    let name = pigeonVar_list[2] as! String
    let modelNumber = pigeonVar_list[3] as! String
    let serialNumber = pigeonVar_list[4] as! String
    let width: Int64? = nilOrValue(pigeonVar_list[5])
    let height: Int64? = nilOrValue(pigeonVar_list[6])

    return PrinterDetails(
      connected: connected,
      connectionID: connectionID,
      name: name,
      modelNumber: modelNumber,
      serialNumber: serialNumber,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      connected,
      connectionID,
      name,
      modelNumber,
      serialNumber,
      width,
      height,
    ]
  }
}

private class SewooPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PrinterList.fromList(self.readValue() as! [Any?])
    case 130:
      return PrinterDetails.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SewooPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PrinterList {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PrinterDetails {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SewooPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SewooPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SewooPigeonCodecWriter(data: data)
  }
}

class SewooPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SewooPigeonCodec(readerWriter: SewooPigeonCodecReaderWriter())
}


/// Sewoo is a Bluetooth printer
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Sewoo {
  func openPort() throws -> Bool
  func closePort() throws -> Bool
  func printText(text: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func printImage(image: FlutterStandardTypedData, width: Int64, height: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  func printPDF(pdfData: FlutterStandardTypedData, width: Int64, height: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  func checkConnectedAccessories() throws -> PrinterList?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SewooSetup {
  static var codec: FlutterStandardMessageCodec { SewooPigeonCodec.shared }
  /// Sets up an instance of `Sewoo` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Sewoo?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openPortChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.openPort\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openPortChannel.setMessageHandler { _, reply in
        do {
          let result = try api.openPort()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openPortChannel.setMessageHandler(nil)
    }
    let closePortChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.closePort\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closePortChannel.setMessageHandler { _, reply in
        do {
          let result = try api.closePort()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closePortChannel.setMessageHandler(nil)
    }
    let printTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.printText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        api.printText(text: textArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printTextChannel.setMessageHandler(nil)
    }
    let printImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.printImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageArg = args[0] as! FlutterStandardTypedData
        let widthArg = args[1] as! Int64
        let heightArg = args[2] as! Int64
        api.printImage(image: imageArg, width: widthArg, height: heightArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printImageChannel.setMessageHandler(nil)
    }
    let printPDFChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.printPDF\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printPDFChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pdfDataArg = args[0] as! FlutterStandardTypedData
        let widthArg = args[1] as! Int64
        let heightArg = args[2] as! Int64
        api.printPDF(pdfData: pdfDataArg, width: widthArg, height: heightArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printPDFChannel.setMessageHandler(nil)
    }
    let checkConnectedAccessoriesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.picker.Sewoo.checkConnectedAccessories\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkConnectedAccessoriesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.checkConnectedAccessories()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkConnectedAccessoriesChannel.setMessageHandler(nil)
    }
  }
}
