// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'pdf_viewer_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_PdfModel _$PdfModelFromJson(Map<String, dynamic> json) => _PdfModel(
  raporOzelKod: json['RAPOR_OZEL_KOD'] as String?,
  standart: json['STANDART'] as bool?,
  dicParams: json['DIC_PARAMS'] == null
      ? null
      : DicParams.fromJson(json['DIC_PARAMS'] as Map<String, dynamic>),
  dicParamsMap: json['DicParams'] as Map<String, dynamic>?,
  dizaynId: (json['DIZAYN_ID'] as num?)?.toInt(),
  etiketSayisi: (json['ETIKET_SAYISI'] as num?)?.toInt(),
);

Map<String, dynamic> _$PdfModelToJson(_PdfModel instance) => <String, dynamic>{
  'RAPOR_OZEL_KOD': ?instance.raporOzelKod,
  'STANDART': ?instance.standart,
  'DIC_PARAMS': ?instance.dicParams?.toJson(),
  'DIZAYN_ID': ?instance.dizaynId,
  'ETIKET_SAYISI': ?instance.etiketSayisi,
};

_DicParams _$DicParamsFromJson(Map<String, dynamic> json) => _DicParams(
  belgeNo: json['BELGE_NO'] as String,
  cariKodu: json['CARI_KODU'] as String?,
  teslimCariKodu: json['TESLIM_CARI_KODU'] as String?,
  stokKodu: json['STOK_KODU'] as String?,
  sifirHaric: json['SIFIR_HARIC'] as String?,
  maliyetTipi: json['MALIYET_TIPI'] as String?,
  tlHarDokulsun: json['TL_HAR_DOKULSUN'] as String?,
  depoKodlari: json['DEPO_KODLARI'] as String?,
  haricStokKodlari: json['HARIC_STOK_KODLARI'] as String?,
  haricStokGrupKodlari: json['HARIC_STOK_GRUP_KODLARI'] as String?,
  dovizTipi: json['DOVIZ_TIPI'] as String?,
  bastar: json['BASTAR'] as String?,
  bittar: json['BITTAR'] as String?,
  grupKodu: json['GRUP_KODU'] as String?,
  borcAlacak: json['BORC_ALACAK'] as String?,
  refTarih: json['REF_TARIH'] as String?,
  tarihTipi: json['TARIH_TIPI'] as String?,
  kod1: json['KOD1'] as String?,
  kod2: json['KOD2'] as String?,
  kod3: json['KOD3'] as String?,
  kod4: json['KOD4'] as String?,
  kod5: json['KOD5'] as String?,
  kapali: json['KAPALI'] as String?,
  durum: json['DURUM'] as String?,
  vergiNo: json['VERGI_NO'] as String?,
  plasiyerKodu: json['PLASIYER_KODU'] as String?,
  aralikTipi: json['ARALIK_TIPI'] as String?,
  sirala: json['SIRALA'] as String?,
  bakiyeDurumu: json['BAKIYE_DURUMU'] as String?,
  caharInckey: json['CAHAR_INCKEY'] as String?,
  belgeTipi: json['BELGE_TIPI'] as String?,
  isemriNo: json['ISEMRI_NO'] as String?,
  dinamikParam: json['DINAMIK_PARAM'] as String?,
  kasaharInckey: json['KASAHAR_INCKEY'] as String?,
  uretimFiyatiDahil: json['URETIM_FIYATI_DAHIL'] as String?,
  fiyatTipi: json['FIYAT_TIPI'] as String?,
  tblnfStokfiyatgecmisiId: json['TBLNF_STOKFIYATGECMISI_ID'] as String?,
  gorunecekAlanlar: json['GORUNECEK_ALANLAR'] as String?,
  miktar: (json['MIKTAR'] as num?)?.toInt(),
  yapkod: json['YAPKOD'] as String?,
  opkodu: json['OPKODU'] as String?,
  kasaKodu: json['KASA_KODU'] as String?,
  muhasebeKodu: json['MUHASEBE_KODU'] as String?,
  filtre: json['FILTRE'] as String?,
  depoKodu: json['DEPO_KODU'] as String?,
  hucreKodu: json['HUCRE_KODU'] as String?,
  kalemId: json['KALEM_ID'] as String?,
  tempBelgeId: json['TEMP_BELGE_ID'] as String?,
  irsDahil: json['IRS_DAHIL'] as String?,
  dovizTipleri: (json['DOVIZ_TIPLERI'] as List<dynamic>?)
      ?.map((e) => (e as num).toInt())
      .toList(),
  plasiyerKirilimi: json['PLASIYER_KIRILIMI'] as String?,
);

Map<String, dynamic> _$DicParamsToJson(_DicParams instance) =>
    <String, dynamic>{
      'BELGE_NO': instance.belgeNo,
      'CARI_KODU': ?instance.cariKodu,
      'TESLIM_CARI_KODU': ?instance.teslimCariKodu,
      'STOK_KODU': ?instance.stokKodu,
      'SIFIR_HARIC': ?instance.sifirHaric,
      'MALIYET_TIPI': ?instance.maliyetTipi,
      'TL_HAR_DOKULSUN': ?instance.tlHarDokulsun,
      'DEPO_KODLARI': ?instance.depoKodlari,
      'HARIC_STOK_KODLARI': ?instance.haricStokKodlari,
      'HARIC_STOK_GRUP_KODLARI': ?instance.haricStokGrupKodlari,
      'DOVIZ_TIPI': ?instance.dovizTipi,
      'BASTAR': ?instance.bastar,
      'BITTAR': ?instance.bittar,
      'GRUP_KODU': ?instance.grupKodu,
      'BORC_ALACAK': ?instance.borcAlacak,
      'REF_TARIH': ?instance.refTarih,
      'TARIH_TIPI': ?instance.tarihTipi,
      'KOD1': ?instance.kod1,
      'KOD2': ?instance.kod2,
      'KOD3': ?instance.kod3,
      'KOD4': ?instance.kod4,
      'KOD5': ?instance.kod5,
      'KAPALI': ?instance.kapali,
      'DURUM': ?instance.durum,
      'VERGI_NO': ?instance.vergiNo,
      'PLASIYER_KODU': ?instance.plasiyerKodu,
      'ARALIK_TIPI': ?instance.aralikTipi,
      'SIRALA': ?instance.sirala,
      'BAKIYE_DURUMU': ?instance.bakiyeDurumu,
      'CAHAR_INCKEY': ?instance.caharInckey,
      'BELGE_TIPI': ?instance.belgeTipi,
      'ISEMRI_NO': ?instance.isemriNo,
      'DINAMIK_PARAM': ?instance.dinamikParam,
      'KASAHAR_INCKEY': ?instance.kasaharInckey,
      'URETIM_FIYATI_DAHIL': ?instance.uretimFiyatiDahil,
      'FIYAT_TIPI': ?instance.fiyatTipi,
      'TBLNF_STOKFIYATGECMISI_ID': ?instance.tblnfStokfiyatgecmisiId,
      'GORUNECEK_ALANLAR': ?instance.gorunecekAlanlar,
      'MIKTAR': ?instance.miktar,
      'YAPKOD': ?instance.yapkod,
      'OPKODU': ?instance.opkodu,
      'KASA_KODU': ?instance.kasaKodu,
      'MUHASEBE_KODU': ?instance.muhasebeKodu,
      'FILTRE': ?instance.filtre,
      'DEPO_KODU': ?instance.depoKodu,
      'HUCRE_KODU': ?instance.hucreKodu,
      'KALEM_ID': ?instance.kalemId,
      'TEMP_BELGE_ID': ?instance.tempBelgeId,
      'IRS_DAHIL': ?instance.irsDahil,
      'DOVIZ_TIPLERI': ?_dovizTipleriToJson(instance.dovizTipleri),
      'PLASIYER_KIRILIMI': ?instance.plasiyerKirilimi,
    };
