// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'talep_teklif_listesi_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$TalepTeklifListesiModelImpl _$$TalepTeklifListesiModelImplFromJson(Map<String, dynamic> json) =>
    _$TalepTeklifListesiModelImpl(
      cariDovizli: json['CARI_DOVIZLI'] as bool?,
      kayittarihi: json['KAYITTARIHI'] == null ? null : DateTime.parse(json['KAYITTARIHI'] as String),
      tarih: json['TARIH'] == null ? null : DateTime.parse(json['TARIH'] as String),
      teslimTarihi: json['TESLIM_TARIHI'] == null ? null : DateTime.parse(json['TESLIM_TARIHI'] as String),
      vadeTarihi: json['VADE_TARIHI'] == null ? null : DateTime.parse(json['VADE_TARIHI'] as String),
      dovizTutari: (json['DOVIZ_TUTARI'] as num?)?.toDouble(),
      genelIskonto1: (json['GENEL_ISKONTO1'] as num?)?.toDouble(),
      genelIskonto2: (json['GENEL_ISKONTO2'] as num?)?.toDouble(),
      genelIskonto3: (json['GENEL_ISKONTO3'] as num?)?.toDouble(),
      genelToplam: (json['GENEL_TOPLAM'] as num?)?.toDouble(),
      genIsk1O: (json['GEN_ISK1_O'] as num?)?.toDouble(),
      genisk1Tipi: (json['GENISK1_TIPI'] as num?)?.toDouble(),
      genIsk2O: (json['GEN_ISK2_O'] as num?)?.toDouble(),
      genIsk3O: (json['GEN_ISK3_O'] as num?)?.toDouble(),
      kalanMiktar: (json['KALAN_MIKTAR'] as num?)?.toDouble(),
      kdv: (json['KDV'] as num?)?.toDouble(),
      miktar: (json['MIKTAR'] as num?)?.toDouble(),
      tamamlananMiktar: (json['TAMAMLANAN_MIKTAR'] as num?)?.toDouble(),
      dovizTipi: (json['DOVIZ_TIPI'] as num?)?.toInt(),
      genisk3Tipi: (json['GENISK3_TIPI'] as num?)?.toInt(),
      kalemAdedi: (json['KALEM_ADEDI'] as num?)?.toInt(),
      tipi: (json['TIPI'] as num?)?.toInt(),
      vadeGunu: (json['VADE_GUNU'] as num?)?.toInt(),
      tempSipList: json['TEMP_SIP_LIST'] as List<dynamic>?,
      kalemList: (json['KALEM_LIST'] as List<dynamic>?)
          ?.map((e) => KalemListModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      acik1: json['ACIK1'] as String?,
      acik2: json['ACIK2'] as String?,
      acik3: json['ACIK3'] as String?,
      acik4: json['ACIK4'] as String?,
      acik5: json['ACIK5'] as String?,
      acik6: json['ACIK6'] as String?,
      acik7: json['ACIK7'] as String?,
      acik8: json['ACIK8'] as String?,
      acik9: json['ACIK9'] as String?,
      acik10: json['ACIK10'] as String?,
      acik11: json['ACIK11'] as String?,
      acik12: json['ACIK12'] as String?,
      acik13: json['ACIK13'] as String?,
      acik14: json['ACIK14'] as String?,
      acik15: json['ACIK15'] as String?,
      acik16: json['ACIK16'] as String?,
      belgeKodu: json['BELGE_KODU'] as String?,
      belgeNo: json['BELGE_NO'] as String?,
      belgeTuru: json['BELGE_TURU'] as String?,
      cariAdi: json['CARI_ADI'] as String?,
      cariKodu: json['CARI_KODU'] as String?,
      cYedek6: json['C_YEDEK6'] as String?,
      dovizAdi: json['DOVIZ_ADI'] as String?,
      ekAciklama: json['EK_ACIKLAMA'] as String?,
      faturalasti: json['FATURALASTI'] as String?,
      kasaKodu: json['KASA_KODU'] as String?,
      kayityapankul: json['KAYITYAPANKUL'] as String?,
      kdvDahil: json['KDV_DAHIL'] as String?,
      plasiyerAciklama: json['PLASIYER_ACIKLAMA'] as String?,
      plasiyerKodu: json['PLASIYER_KODU'] as String?,
      siparislesti: json['SIPARISLESTI'] as String?,
      ekAcik1: json['EK_ACIK1'] as String?,
      ekAcik10: json['EK_ACIK10'] as String?,
      ekAcik11: json['EK_ACIK11'] as String?,
      ekAcik12: json['EK_ACIK12'] as String?,
      ekAcik13: json['EK_ACIK13'] as String?,
      ekAcik14: json['EK_ACIK14'] as String?,
      ekAcik15: json['EK_ACIK15'] as String?,
      ekAcik16: json['EK_ACIK16'] as String?,
      ekAcik2: json['EK_ACIK2'] as String?,
      ekAcik3: json['EK_ACIK3'] as String?,
      ekAcik4: json['EK_ACIK4'] as String?,
      ekAcik5: json['EK_ACIK5'] as String?,
      ekAcik6: json['EK_ACIK6'] as String?,
      ekAcik7: json['EK_ACIK7'] as String?,
      ekAcik8: json['EK_ACIK8'] as String?,
      ekAcik9: json['EK_ACIK9'] as String?,
      islemKodu: (json['ISLEM_KODU'] as num?)?.toInt(),
      tag: json['TAG'] as String? ?? "FaturaModel",
    );

Map<String, dynamic> _$$TalepTeklifListesiModelImplToJson(_$TalepTeklifListesiModelImpl instance) => <String, dynamic>{
  if (instance.cariDovizli case final value?) 'CARI_DOVIZLI': value,
  if (instance.kayittarihi?.toIso8601String() case final value?) 'KAYITTARIHI': value,
  if (instance.tarih?.toIso8601String() case final value?) 'TARIH': value,
  if (instance.teslimTarihi?.toIso8601String() case final value?) 'TESLIM_TARIHI': value,
  if (instance.vadeTarihi?.toIso8601String() case final value?) 'VADE_TARIHI': value,
  if (instance.dovizTutari case final value?) 'DOVIZ_TUTARI': value,
  if (instance.genelIskonto1 case final value?) 'GENEL_ISKONTO1': value,
  if (instance.genelIskonto2 case final value?) 'GENEL_ISKONTO2': value,
  if (instance.genelIskonto3 case final value?) 'GENEL_ISKONTO3': value,
  if (instance.genelToplam case final value?) 'GENEL_TOPLAM': value,
  if (instance.genIsk1O case final value?) 'GEN_ISK1_O': value,
  if (instance.genisk1Tipi case final value?) 'GENISK1_TIPI': value,
  if (instance.genIsk2O case final value?) 'GEN_ISK2_O': value,
  if (instance.genIsk3O case final value?) 'GEN_ISK3_O': value,
  if (instance.kalanMiktar case final value?) 'KALAN_MIKTAR': value,
  if (instance.kdv case final value?) 'KDV': value,
  if (instance.miktar case final value?) 'MIKTAR': value,
  if (instance.tamamlananMiktar case final value?) 'TAMAMLANAN_MIKTAR': value,
  if (instance.dovizTipi case final value?) 'DOVIZ_TIPI': value,
  if (instance.genisk3Tipi case final value?) 'GENISK3_TIPI': value,
  if (instance.kalemAdedi case final value?) 'KALEM_ADEDI': value,
  if (instance.tipi case final value?) 'TIPI': value,
  if (instance.vadeGunu case final value?) 'VADE_GUNU': value,
  if (instance.tempSipList case final value?) 'TEMP_SIP_LIST': value,
  if (instance.kalemList?.map((e) => e.toJson()).toList() case final value?) 'KALEM_LIST': value,
  if (instance.acik1 case final value?) 'ACIK1': value,
  if (instance.acik2 case final value?) 'ACIK2': value,
  if (instance.acik3 case final value?) 'ACIK3': value,
  if (instance.acik4 case final value?) 'ACIK4': value,
  if (instance.acik5 case final value?) 'ACIK5': value,
  if (instance.acik6 case final value?) 'ACIK6': value,
  if (instance.acik7 case final value?) 'ACIK7': value,
  if (instance.acik8 case final value?) 'ACIK8': value,
  if (instance.acik9 case final value?) 'ACIK9': value,
  if (instance.acik10 case final value?) 'ACIK10': value,
  if (instance.acik11 case final value?) 'ACIK11': value,
  if (instance.acik12 case final value?) 'ACIK12': value,
  if (instance.acik13 case final value?) 'ACIK13': value,
  if (instance.acik14 case final value?) 'ACIK14': value,
  if (instance.acik15 case final value?) 'ACIK15': value,
  if (instance.acik16 case final value?) 'ACIK16': value,
  if (instance.belgeKodu case final value?) 'BELGE_KODU': value,
  if (instance.belgeNo case final value?) 'BELGE_NO': value,
  if (instance.belgeTuru case final value?) 'BELGE_TURU': value,
  if (instance.cariAdi case final value?) 'CARI_ADI': value,
  if (instance.cariKodu case final value?) 'CARI_KODU': value,
  if (instance.cYedek6 case final value?) 'C_YEDEK6': value,
  if (instance.dovizAdi case final value?) 'DOVIZ_ADI': value,
  if (instance.ekAciklama case final value?) 'EK_ACIKLAMA': value,
  if (instance.faturalasti case final value?) 'FATURALASTI': value,
  if (instance.kasaKodu case final value?) 'KASA_KODU': value,
  if (instance.kayityapankul case final value?) 'KAYITYAPANKUL': value,
  if (instance.kdvDahil case final value?) 'KDV_DAHIL': value,
  if (instance.plasiyerAciklama case final value?) 'PLASIYER_ACIKLAMA': value,
  if (instance.plasiyerKodu case final value?) 'PLASIYER_KODU': value,
  if (instance.siparislesti case final value?) 'SIPARISLESTI': value,
  if (instance.ekAcik1 case final value?) 'EK_ACIK1': value,
  if (instance.ekAcik10 case final value?) 'EK_ACIK10': value,
  if (instance.ekAcik11 case final value?) 'EK_ACIK11': value,
  if (instance.ekAcik12 case final value?) 'EK_ACIK12': value,
  if (instance.ekAcik13 case final value?) 'EK_ACIK13': value,
  if (instance.ekAcik14 case final value?) 'EK_ACIK14': value,
  if (instance.ekAcik15 case final value?) 'EK_ACIK15': value,
  if (instance.ekAcik16 case final value?) 'EK_ACIK16': value,
  if (instance.ekAcik2 case final value?) 'EK_ACIK2': value,
  if (instance.ekAcik3 case final value?) 'EK_ACIK3': value,
  if (instance.ekAcik4 case final value?) 'EK_ACIK4': value,
  if (instance.ekAcik5 case final value?) 'EK_ACIK5': value,
  if (instance.ekAcik6 case final value?) 'EK_ACIK6': value,
  if (instance.ekAcik7 case final value?) 'EK_ACIK7': value,
  if (instance.ekAcik8 case final value?) 'EK_ACIK8': value,
  if (instance.ekAcik9 case final value?) 'EK_ACIK9': value,
  if (instance.islemKodu case final value?) 'ISLEM_KODU': value,
  if (instance.tag case final value?) 'TAG': value,
};
