// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'siparisler_request_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_SiparislerRequestModel _$SiparislerRequestModelFromJson(
  Map<String, dynamic> json,
) => _SiparislerRequestModel(
  pickerBelgeTuru: json['PickerBelgeTuru'] as String?,
  iadeMi: json['IadeMi'] as bool?,
  cariKodu: json['CariKodu'] as String? ?? "",
  teslimCariKodu: json['TeslimCariKodu'] as String?,
  ozelKod2: json['OzelKod2'] as String?,
  cariTipi: json['CariTipi'] as String?,
  miktarGetir: json['MiktarGetir'] as String?,
  kontrolEdildi: json['KontrolEdildi'] as String?,
  siralama: json['SIRALAMA'] as String?,
  siparisKarsilanmaDurumu: json['SiparisKarsilanmaDurumu'] as String?,
  ozelKod1: json['OzelKod1'] as String?,
  stokKodu: json['StokKodu'] as String?,
  kapaliBelgelerListelenmesin: json['KapaliBelgelerListelenmesin'] as bool?,
  projeKodu: json['ProjeKodu'] as String?,
  faturalasmaGoster: json['FaturalasmaGoster'] as bool?,
  arrKod5: json['ArrKod5'] as String?,
  arrGrupKodu: json['ArrGrupKodu'] as String?,
  arrKod4: json['ArrKod4'] as String?,
  arrKod3: json['ArrKod3'] as String?,
  arrKod2: json['ArrKod2'] as String?,
  arrPlasiyerKodu: json['ArrPlasiyerKodu'] as String?,
  arrKod1: json['ArrKod1'] as String?,
  ekranTipi: json['EkranTipi'] as String? ?? "R",
  sayfa: (json['Sayfa'] as num?)?.toInt(),
  baslamaTarihi: json['BaslamaTarihi'] as String?,
  bitisTarihi: json['BitisTarihi'] as String?,
  searchText: json['SearchText'] as String?,
  filtreKodu: (json['FiltreKodu'] as num?)?.toInt(),
  depoKodu: json['DepoKodu'] as String?,
  hedefDepoKodu: json['HedefDepoKodu'] as String?,
  belgeNo: json['BelgeNo'] as String? ?? "",
  siparisDurumu: json['SiparisDurumu'] as String?,
  referansStokKodu: json['ReferansStokKodu'] as String?,
  fiyatGrubu: json['FiyatGrubu'] as String?,
  menuKodu: json['MenuKodu'] as String?,
  siparisSevkEdilenGoster: json['SiparisSevkEdilenGoster'] as bool?,
  refBelgeTuru: json['RefBelgeTuru'] as String?,
  kisitYok: json['KisitYok'] as bool?,
  arrBelgeTipi: json['ArrBelgeTipi'] as String?,
  arrBelgeNo: json['ArrBelgeNo'] as String?,
  lokalDAT: json['LokalDAT'] as String?,
  faturalanmisIrsaliyelerGelsin: json['FaturalanmisIrsaliyelerGelsin'] as bool?,
  onayDurumu: json['OnayDurumu'] as String?,
);

Map<String, dynamic> _$SiparislerRequestModelToJson(
  _SiparislerRequestModel instance,
) => <String, dynamic>{
  'PickerBelgeTuru': ?instance.pickerBelgeTuru,
  'IadeMi': ?instance.iadeMi,
  'CariKodu': ?instance.cariKodu,
  'TeslimCariKodu': ?instance.teslimCariKodu,
  'OzelKod2': ?instance.ozelKod2,
  'CariTipi': ?instance.cariTipi,
  'MiktarGetir': ?instance.miktarGetir,
  'KontrolEdildi': ?instance.kontrolEdildi,
  'SIRALAMA': ?instance.siralama,
  'SiparisKarsilanmaDurumu': ?instance.siparisKarsilanmaDurumu,
  'OzelKod1': ?instance.ozelKod1,
  'StokKodu': ?instance.stokKodu,
  'KapaliBelgelerListelenmesin': ?instance.kapaliBelgelerListelenmesin,
  'ProjeKodu': ?instance.projeKodu,
  'FaturalasmaGoster': ?instance.faturalasmaGoster,
  'ArrKod5': ?instance.arrKod5,
  'ArrGrupKodu': ?instance.arrGrupKodu,
  'ArrKod4': ?instance.arrKod4,
  'ArrKod3': ?instance.arrKod3,
  'ArrKod2': ?instance.arrKod2,
  'ArrPlasiyerKodu': ?instance.arrPlasiyerKodu,
  'ArrKod1': ?instance.arrKod1,
  'EkranTipi': ?instance.ekranTipi,
  'Sayfa': ?instance.sayfa,
  'BaslamaTarihi': ?instance.baslamaTarihi,
  'BitisTarihi': ?instance.bitisTarihi,
  'SearchText': ?instance.searchText,
  'FiltreKodu': ?instance.filtreKodu,
  'DepoKodu': ?instance.depoKodu,
  'HedefDepoKodu': ?instance.hedefDepoKodu,
  'BelgeNo': ?instance.belgeNo,
  'SiparisDurumu': ?instance.siparisDurumu,
  'ReferansStokKodu': ?instance.referansStokKodu,
  'FiyatGrubu': ?instance.fiyatGrubu,
  'MenuKodu': ?instance.menuKodu,
  'SiparisSevkEdilenGoster': ?instance.siparisSevkEdilenGoster,
  'RefBelgeTuru': ?instance.refBelgeTuru,
  'KisitYok': ?instance.kisitYok,
  'ArrBelgeTipi': ?instance.arrBelgeTipi,
  'ArrBelgeNo': ?instance.arrBelgeNo,
  'LokalDAT': ?instance.lokalDAT,
  'FaturalanmisIrsaliyelerGelsin': ?instance.faturalanmisIrsaliyelerGelsin,
  'OnayDurumu': ?instance.onayDurumu,
};
