// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'siparisler_request_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SiparislerRequestModelImpl _$$SiparislerRequestModelImplFromJson(Map<String, dynamic> json) =>
    _$SiparislerRequestModelImpl(
      pickerBelgeTuru: json['PickerBelgeTuru'] as String?,
      iadeMi: json['IadeMi'] as bool?,
      cariKodu: json['CariKodu'] as String? ?? "",
      teslimCariKodu: json['TeslimCariKodu'] as String?,
      ozelKod2: json['OzelKod2'] as String?,
      cariTipi: json['CariTipi'] as String?,
      miktarGetir: json['MiktarGetir'] as String?,
      siralama: json['SIRALAMA'] as String?,
      siparisKarsilanmaDurumu: json['SiparisKarsilanmaDurumu'] as String?,
      ozelKod1: json['OzelKod1'] as String?,
      stokKodu: json['StokKodu'] as String?,
      kapaliBelgelerListelenmesin: json['KapaliBelgelerListelenmesin'] as bool?,
      projeKodu: json['ProjeKodu'] as String?,
      faturalasmaGoster: json['FaturalasmaGoster'] as bool?,
      arrKod5: json['ArrKod5'] as String?,
      arrGrupKodu: json['ArrGrupKodu'] as String?,
      arrKod4: json['ArrKod4'] as String?,
      arrKod3: json['ArrKod3'] as String?,
      arrKod2: json['ArrKod2'] as String?,
      arrPlasiyerKodu: json['ArrPlasiyerKodu'] as String?,
      arrKod1: json['ArrKod1'] as String?,
      ekranTipi: json['EkranTipi'] as String? ?? "R",
      sayfa: (json['Sayfa'] as num?)?.toInt(),
      baslamaTarihi: json['BaslamaTarihi'] as String?,
      bitisTarihi: json['BitisTarihi'] as String?,
      searchText: json['SearchText'] as String?,
      filtreKodu: (json['FiltreKodu'] as num?)?.toInt(),
      depoKodu: json['DepoKodu'] as String?,
      hedefDepoKodu: json['HedefDepoKodu'] as String?,
      belgeNo: json['BelgeNo'] as String? ?? "",
      siparisDurumu: json['SiparisDurumu'] as String?,
      referansStokKodu: json['ReferansStokKodu'] as String?,
      fiyatGrubu: json['FiyatGrubu'] as String?,
      menuKodu: json['MenuKodu'] as String?,
      siparisSevkEdilenGoster: json['SiparisSevkEdilenGoster'] as bool?,
      refBelgeTuru: json['RefBelgeTuru'] as String?,
      kisitYok: json['KisitYok'] as bool?,
      arrBelgeTipi: json['ArrBelgeTipi'] as String?,
      arrBelgeNo: json['ArrBelgeNo'] as String?,
      lokalDAT: json['LokalDAT'] as String?,
      faturalanmisIrsaliyelerGelsin: json['FaturalanmisIrsaliyelerGelsin'] as bool?,
    );

Map<String, dynamic> _$$SiparislerRequestModelImplToJson(_$SiparislerRequestModelImpl instance) => <String, dynamic>{
  if (instance.pickerBelgeTuru case final value?) 'PickerBelgeTuru': value,
  if (instance.iadeMi case final value?) 'IadeMi': value,
  if (instance.cariKodu case final value?) 'CariKodu': value,
  if (instance.teslimCariKodu case final value?) 'TeslimCariKodu': value,
  if (instance.ozelKod2 case final value?) 'OzelKod2': value,
  if (instance.cariTipi case final value?) 'CariTipi': value,
  if (instance.miktarGetir case final value?) 'MiktarGetir': value,
  if (instance.siralama case final value?) 'SIRALAMA': value,
  if (instance.siparisKarsilanmaDurumu case final value?) 'SiparisKarsilanmaDurumu': value,
  if (instance.ozelKod1 case final value?) 'OzelKod1': value,
  if (instance.stokKodu case final value?) 'StokKodu': value,
  if (instance.kapaliBelgelerListelenmesin case final value?) 'KapaliBelgelerListelenmesin': value,
  if (instance.projeKodu case final value?) 'ProjeKodu': value,
  if (instance.faturalasmaGoster case final value?) 'FaturalasmaGoster': value,
  if (instance.arrKod5 case final value?) 'ArrKod5': value,
  if (instance.arrGrupKodu case final value?) 'ArrGrupKodu': value,
  if (instance.arrKod4 case final value?) 'ArrKod4': value,
  if (instance.arrKod3 case final value?) 'ArrKod3': value,
  if (instance.arrKod2 case final value?) 'ArrKod2': value,
  if (instance.arrPlasiyerKodu case final value?) 'ArrPlasiyerKodu': value,
  if (instance.arrKod1 case final value?) 'ArrKod1': value,
  if (instance.ekranTipi case final value?) 'EkranTipi': value,
  if (instance.sayfa case final value?) 'Sayfa': value,
  if (instance.baslamaTarihi case final value?) 'BaslamaTarihi': value,
  if (instance.bitisTarihi case final value?) 'BitisTarihi': value,
  if (instance.searchText case final value?) 'SearchText': value,
  if (instance.filtreKodu case final value?) 'FiltreKodu': value,
  if (instance.depoKodu case final value?) 'DepoKodu': value,
  if (instance.hedefDepoKodu case final value?) 'HedefDepoKodu': value,
  if (instance.belgeNo case final value?) 'BelgeNo': value,
  if (instance.siparisDurumu case final value?) 'SiparisDurumu': value,
  if (instance.referansStokKodu case final value?) 'ReferansStokKodu': value,
  if (instance.fiyatGrubu case final value?) 'FiyatGrubu': value,
  if (instance.menuKodu case final value?) 'MenuKodu': value,
  if (instance.siparisSevkEdilenGoster case final value?) 'SiparisSevkEdilenGoster': value,
  if (instance.refBelgeTuru case final value?) 'RefBelgeTuru': value,
  if (instance.kisitYok case final value?) 'KisitYok': value,
  if (instance.arrBelgeTipi case final value?) 'ArrBelgeTipi': value,
  if (instance.arrBelgeNo case final value?) 'ArrBelgeNo': value,
  if (instance.lokalDAT case final value?) 'LokalDAT': value,
  if (instance.faturalanmisIrsaliyelerGelsin case final value?) 'FaturalanmisIrsaliyelerGelsin': value,
};
