// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'siparis_edit_request_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_SiparisEditRequestModel _$SiparisEditRequestModelFromJson(
  Map<String, dynamic> json,
) => _SiparisEditRequestModel(
  ekranTipi: json['EkranTipi'] as String? ?? 'D',
  kisitYok: json['KisitYok'] as bool? ?? true,
  belgeTipi: json['BelgeTipi'] as String?,
  pickerBelgeTuru: json['PickerBelgeTuru'] as String?,
  remoteTempBelge: json['RemoteTempBelge'] as bool?,
  faturaTipi: (json['FaturaTipi'] as num?)?.toInt(),
  tempBelgeId: (json['TempBelgeId'] as num?)?.toInt(),
  tipi: (json['Tipi'] as num?)?.toInt(),
  belgeNo: json['BelgeNo'] as String?,
  belgeTarihi: json['BelgeTarihi'] as String?,
  belgeTuru: json['BelgeTuru'] as String?,
  cariKodu: json['CariKodu'] as String?,
  islemId: json['IslemId'] as String?,
  kayitModu: json['KayitModu'] as String?,
  menuKodu: json['MenuKodu'] as String?,
  mevcutBelgeNo: json['MevcutBelgeNo'] as String?,
  mevcutCariKodu: json['MevcutCariKodu'] as String?,
  paramMap: json['ParamMap'] as String?,
  resimGoster: json['ResimGoster'] as String?,
  stokKodu: json['StokKodu'] as String?,
  tag: json['Tag'] as String?,
  siparisSevkEdilenGoster: json['SiparisSevkEdilenGoster'] as bool?,
  filtreKodu: (json['FiltreKodu'] as num?)?.toInt(),
  eFaturaIncKeyNo: (json['EFaturaIncKeyNo'] as num?)?.toInt(),
  depoKodu: (json['DepoKodu'] as num?)?.toInt(),
  iadeMi: json['IadeMi'] as bool?,
  ozelKod2: json['OzelKod2'] as String?,
  cariTipi: json['CariTipi'] as String?,
  miktarGetir: json['MiktarGetir'] as String?,
  siralama: json['SIRALAMA'] as String?,
  siparisKarsilanmaDurumu: json['SiparisKarsilanmaDurumu'] as String?,
  ozelKod1: json['OzelKod1'] as String?,
  kapaliBelgelerListelenmesin: json['KapaliBelgelerListelenmesin'] as bool?,
  projeKodu: json['ProjeKodu'] as String?,
  faturalasmaGoster: json['FaturalasmaGoster'] as bool?,
  arrKod5: json['ArrKod5'] as String?,
  arrGrupKodu: json['ArrGrupKodu'] as String?,
  arrKod4: json['ArrKod4'] as String?,
  arrKod3: json['ArrKod3'] as String?,
  arrKod2: json['ArrKod2'] as String?,
  arrPlasiyerKodu: json['ArrPlasiyerKodu'] as String?,
  arrKod1: json['ArrKod1'] as String?,
  sayfa: (json['Sayfa'] as num?)?.toInt(),
  baslamaTarihi: json['BaslamaTarihi'] as String?,
  bitisTarihi: json['BitisTarihi'] as String?,
  searchText: json['SearchText'] as String?,
  siparisDurumu: json['SiparisDurumu'] as String?,
  referansStokKodu: json['ReferansStokKodu'] as String?,
  refBelgeTuru: json['RefBelgeTuru'] as String?,
  arrBelgeTipi: json['ArrBelgeTipi'] as String?,
  arrBelgeNo: json['ArrBelgeNo'] as String?,
  bakiyeDurumu: json['BakiyeDurumu'] as String?,
  isNew: json['IsNew'] as bool?,
  hedefDepoKodu: (json['HedefDepoKodu'] as num?)?.toInt(),
  barkod: json['Barkod'] as String?,
  okutuldu: json['Okutuldu'] as String?,
);

Map<String, dynamic> _$SiparisEditRequestModelToJson(
  _SiparisEditRequestModel instance,
) => <String, dynamic>{
  'EkranTipi': ?instance.ekranTipi,
  'KisitYok': ?instance.kisitYok,
  'BelgeTipi': ?instance.belgeTipi,
  'PickerBelgeTuru': ?instance.pickerBelgeTuru,
  'RemoteTempBelge': ?instance.remoteTempBelge,
  'FaturaTipi': ?instance.faturaTipi,
  'TempBelgeId': ?instance.tempBelgeId,
  'Tipi': ?instance.tipi,
  'BelgeNo': ?instance.belgeNo,
  'BelgeTarihi': ?instance.belgeTarihi,
  'BelgeTuru': ?instance.belgeTuru,
  'CariKodu': ?instance.cariKodu,
  'IslemId': ?instance.islemId,
  'KayitModu': ?instance.kayitModu,
  'MenuKodu': ?instance.menuKodu,
  'MevcutBelgeNo': ?instance.mevcutBelgeNo,
  'MevcutCariKodu': ?instance.mevcutCariKodu,
  'ParamMap': ?instance.paramMap,
  'ResimGoster': ?instance.resimGoster,
  'StokKodu': ?instance.stokKodu,
  'Tag': ?instance.tag,
  'SiparisSevkEdilenGoster': ?instance.siparisSevkEdilenGoster,
  'FiltreKodu': ?instance.filtreKodu,
  'EFaturaIncKeyNo': ?instance.eFaturaIncKeyNo,
  'DepoKodu': ?instance.depoKodu,
  'IadeMi': ?instance.iadeMi,
  'OzelKod2': ?instance.ozelKod2,
  'CariTipi': ?instance.cariTipi,
  'MiktarGetir': ?instance.miktarGetir,
  'SIRALAMA': ?instance.siralama,
  'SiparisKarsilanmaDurumu': ?instance.siparisKarsilanmaDurumu,
  'OzelKod1': ?instance.ozelKod1,
  'KapaliBelgelerListelenmesin': ?instance.kapaliBelgelerListelenmesin,
  'ProjeKodu': ?instance.projeKodu,
  'FaturalasmaGoster': ?instance.faturalasmaGoster,
  'ArrKod5': ?instance.arrKod5,
  'ArrGrupKodu': ?instance.arrGrupKodu,
  'ArrKod4': ?instance.arrKod4,
  'ArrKod3': ?instance.arrKod3,
  'ArrKod2': ?instance.arrKod2,
  'ArrPlasiyerKodu': ?instance.arrPlasiyerKodu,
  'ArrKod1': ?instance.arrKod1,
  'Sayfa': ?instance.sayfa,
  'BaslamaTarihi': ?instance.baslamaTarihi,
  'BitisTarihi': ?instance.bitisTarihi,
  'SearchText': ?instance.searchText,
  'SiparisDurumu': ?instance.siparisDurumu,
  'ReferansStokKodu': ?instance.referansStokKodu,
  'RefBelgeTuru': ?instance.refBelgeTuru,
  'ArrBelgeTipi': ?instance.arrBelgeTipi,
  'ArrBelgeNo': ?instance.arrBelgeNo,
  'BakiyeDurumu': ?instance.bakiyeDurumu,
  'IsNew': ?instance.isNew,
  'HedefDepoKodu': ?instance.hedefDepoKodu,
  'Barkod': ?instance.barkod,
  'Okutuldu': ?instance.okutuldu,
};
