// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'siparis_edit_request_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SiparisEditRequestModelImpl _$$SiparisEditRequestModelImplFromJson(
        Map<String, dynamic> json) =>
    _$SiparisEditRequestModelImpl(
      ekranTipi: json['EkranTipi'] as String? ?? 'D',
      kisitYok: json['KisitYok'] as bool? ?? true,
      belgeTipi: json['BelgeTipi'] as String?,
      pickerBelgeTuru: json['PickerBelgeTuru'] as String?,
      remoteTempBelge: json['RemoteTempBelge'] as bool?,
      faturaTipi: (json['FaturaTipi'] as num?)?.toInt(),
      tempBelgeId: (json['TempBelgeId'] as num?)?.toInt(),
      tipi: (json['Tipi'] as num?)?.toInt(),
      belgeNo: json['BelgeNo'] as String?,
      belgeTarihi: json['BelgeTarihi'] as String?,
      belgeTuru: json['BelgeTuru'] as String?,
      cariKodu: json['CariKodu'] as String?,
      islemId: json['IslemId'] as String?,
      kayitModu: json['KayitModu'] as String?,
      menuKodu: json['MenuKodu'] as String?,
      mevcutBelgeNo: json['MevcutBelgeNo'] as String?,
      mevcutCariKodu: json['MevcutCariKodu'] as String?,
      paramMap: json['ParamMap'] as String?,
      resimGoster: json['ResimGoster'] as String?,
      stokKodu: json['StokKodu'] as String?,
      tag: json['Tag'] as String?,
      siparisSevkEdilenGoster: json['SiparisSevkEdilenGoster'] as bool?,
      filtreKodu: (json['FiltreKodu'] as num?)?.toInt(),
      eFaturaIncKeyNo: (json['EFaturaIncKeyNo'] as num?)?.toInt(),
      depoKodu: (json['DepoKodu'] as num?)?.toInt(),
      iadeMi: json['IadeMi'] as bool?,
      ozelKod2: json['OzelKod2'] as String?,
      cariTipi: json['CariTipi'] as String?,
      miktarGetir: json['MiktarGetir'] as String?,
      siralama: json['SIRALAMA'] as String?,
      siparisKarsilanmaDurumu: json['SiparisKarsilanmaDurumu'] as String?,
      ozelKod1: json['OzelKod1'] as String?,
      kapaliBelgelerListelenmesin: json['KapaliBelgelerListelenmesin'] as bool?,
      projeKodu: json['ProjeKodu'] as String?,
      faturalasmaGoster: json['FaturalasmaGoster'] as bool?,
      arrKod5: json['ArrKod5'] as String?,
      arrGrupKodu: json['ArrGrupKodu'] as String?,
      arrKod4: json['ArrKod4'] as String?,
      arrKod3: json['ArrKod3'] as String?,
      arrKod2: json['ArrKod2'] as String?,
      arrPlasiyerKodu: json['ArrPlasiyerKodu'] as String?,
      arrKod1: json['ArrKod1'] as String?,
      sayfa: (json['Sayfa'] as num?)?.toInt(),
      baslamaTarihi: json['BaslamaTarihi'] as String?,
      bitisTarihi: json['BitisTarihi'] as String?,
      searchText: json['SearchText'] as String?,
      siparisDurumu: json['SiparisDurumu'] as String?,
      referansStokKodu: json['ReferansStokKodu'] as String?,
      refBelgeTuru: json['RefBelgeTuru'] as String?,
      arrBelgeTipi: json['ArrBelgeTipi'] as String?,
      arrBelgeNo: json['ArrBelgeNo'] as String?,
      bakiyeDurumu: json['BakiyeDurumu'] as String?,
      isNew: json['IsNew'] as bool?,
    );

Map<String, dynamic> _$$SiparisEditRequestModelImplToJson(
        _$SiparisEditRequestModelImpl instance) =>
    <String, dynamic>{
      if (instance.ekranTipi case final value?) 'EkranTipi': value,
      if (instance.kisitYok case final value?) 'KisitYok': value,
      if (instance.belgeTipi case final value?) 'BelgeTipi': value,
      if (instance.pickerBelgeTuru case final value?) 'PickerBelgeTuru': value,
      if (instance.remoteTempBelge case final value?) 'RemoteTempBelge': value,
      if (instance.faturaTipi case final value?) 'FaturaTipi': value,
      if (instance.tempBelgeId case final value?) 'TempBelgeId': value,
      if (instance.tipi case final value?) 'Tipi': value,
      if (instance.belgeNo case final value?) 'BelgeNo': value,
      if (instance.belgeTarihi case final value?) 'BelgeTarihi': value,
      if (instance.belgeTuru case final value?) 'BelgeTuru': value,
      if (instance.cariKodu case final value?) 'CariKodu': value,
      if (instance.islemId case final value?) 'IslemId': value,
      if (instance.kayitModu case final value?) 'KayitModu': value,
      if (instance.menuKodu case final value?) 'MenuKodu': value,
      if (instance.mevcutBelgeNo case final value?) 'MevcutBelgeNo': value,
      if (instance.mevcutCariKodu case final value?) 'MevcutCariKodu': value,
      if (instance.paramMap case final value?) 'ParamMap': value,
      if (instance.resimGoster case final value?) 'ResimGoster': value,
      if (instance.stokKodu case final value?) 'StokKodu': value,
      if (instance.tag case final value?) 'Tag': value,
      if (instance.siparisSevkEdilenGoster case final value?)
        'SiparisSevkEdilenGoster': value,
      if (instance.filtreKodu case final value?) 'FiltreKodu': value,
      if (instance.eFaturaIncKeyNo case final value?) 'EFaturaIncKeyNo': value,
      if (instance.depoKodu case final value?) 'DepoKodu': value,
      if (instance.iadeMi case final value?) 'IadeMi': value,
      if (instance.ozelKod2 case final value?) 'OzelKod2': value,
      if (instance.cariTipi case final value?) 'CariTipi': value,
      if (instance.miktarGetir case final value?) 'MiktarGetir': value,
      if (instance.siralama case final value?) 'SIRALAMA': value,
      if (instance.siparisKarsilanmaDurumu case final value?)
        'SiparisKarsilanmaDurumu': value,
      if (instance.ozelKod1 case final value?) 'OzelKod1': value,
      if (instance.kapaliBelgelerListelenmesin case final value?)
        'KapaliBelgelerListelenmesin': value,
      if (instance.projeKodu case final value?) 'ProjeKodu': value,
      if (instance.faturalasmaGoster case final value?)
        'FaturalasmaGoster': value,
      if (instance.arrKod5 case final value?) 'ArrKod5': value,
      if (instance.arrGrupKodu case final value?) 'ArrGrupKodu': value,
      if (instance.arrKod4 case final value?) 'ArrKod4': value,
      if (instance.arrKod3 case final value?) 'ArrKod3': value,
      if (instance.arrKod2 case final value?) 'ArrKod2': value,
      if (instance.arrPlasiyerKodu case final value?) 'ArrPlasiyerKodu': value,
      if (instance.arrKod1 case final value?) 'ArrKod1': value,
      if (instance.sayfa case final value?) 'Sayfa': value,
      if (instance.baslamaTarihi case final value?) 'BaslamaTarihi': value,
      if (instance.bitisTarihi case final value?) 'BitisTarihi': value,
      if (instance.searchText case final value?) 'SearchText': value,
      if (instance.siparisDurumu case final value?) 'SiparisDurumu': value,
      if (instance.referansStokKodu case final value?)
        'ReferansStokKodu': value,
      if (instance.refBelgeTuru case final value?) 'RefBelgeTuru': value,
      if (instance.arrBelgeTipi case final value?) 'ArrBelgeTipi': value,
      if (instance.arrBelgeNo case final value?) 'ArrBelgeNo': value,
      if (instance.bakiyeDurumu case final value?) 'BakiyeDurumu': value,
      if (instance.isNew case final value?) 'IsNew': value,
    };
