// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:picker/core/base/model/login_dialog_model.dart';
import 'package:picker/core/base/model/yazici_model.dart';
import 'package:picker/core/constants/enum/edit_tipi_enum.dart';
import 'package:picker/core/init/cache/favorites_model.dart';
import 'package:picker/view/add_company/model/account_model.dart';
import 'package:picker/view/add_company/model/account_response_model.dart';
import 'package:picker/view/auth/login/model/login_model.dart';
import 'package:picker/view/auth/model/isletme_model.dart';
import 'package:picker/view/main_page/alt_sayfalar/cari/cari_listesi/model/cari_listesi_model.dart';
import 'package:picker/view/main_page/alt_sayfalar/cari/cari_listesi/model/cari_sehirler_model.dart';
import 'package:picker/view/main_page/alt_sayfalar/payker/payker_odeme_listesi/model/module_info_model.dart';
import 'package:picker/view/main_page/alt_sayfalar/siparis/base_siparis_edit/model/base_siparis_edit_model.dart';
import 'package:picker/view/main_page/alt_sayfalar/stok/base_stok_edit/model/stok_detay_model.dart';
import 'package:picker/view/main_page/model/main_page_model.dart';
import 'package:picker/view/main_page/model/param_model.dart';
import 'package:picker/view/main_page/model/sirket_model.dart';
import 'package:picker/view/main_page/model/user_model/user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountModelAdapter());
    registerAdapter(AccountResponseModelAdapter());
    registerAdapter(BarkodListAdapter());
    registerAdapter(BaseSiparisEditModelAdapter());
    registerAdapter(CariListesiModelAdapter());
    registerAdapter(CariSehirlerModelAdapter());
    registerAdapter(CihazlarAdapter());
    registerAdapter(DepoListAdapter());
    registerAdapter(DeveloperBilgiAdapter());
    registerAdapter(EditTipiEnumAdapter());
    registerAdapter(EkLisanslarAdapter());
    registerAdapter(FavoritesModelAdapter());
    registerAdapter(HesapAdapter());
    registerAdapter(IsletmeModelAdapter());
    registerAdapter(KalemModelAdapter());
    registerAdapter(ListSiparisEditModelAdapter());
    registerAdapter(LoginDialogModelAdapter());
    registerAdapter(MainPageModelAdapter());
    registerAdapter(ModuleInfoModelAdapter());
    registerAdapter(ModullerAdapter());
    registerAdapter(NetFectDizaynListAdapter());
    registerAdapter(SeriListAdapter());
    registerAdapter(SirketModelAdapter());
    registerAdapter(SqlserverinfoAdapter());
    registerAdapter(TokenModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(YaziciListAdapter());
    registerAdapter(YaziciModelAdapter());
    registerAdapter(YaziciTipiAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountModelAdapter());
    registerAdapter(AccountResponseModelAdapter());
    registerAdapter(BarkodListAdapter());
    registerAdapter(BaseSiparisEditModelAdapter());
    registerAdapter(CariListesiModelAdapter());
    registerAdapter(CariSehirlerModelAdapter());
    registerAdapter(CihazlarAdapter());
    registerAdapter(DepoListAdapter());
    registerAdapter(DeveloperBilgiAdapter());
    registerAdapter(EditTipiEnumAdapter());
    registerAdapter(EkLisanslarAdapter());
    registerAdapter(FavoritesModelAdapter());
    registerAdapter(HesapAdapter());
    registerAdapter(IsletmeModelAdapter());
    registerAdapter(KalemModelAdapter());
    registerAdapter(ListSiparisEditModelAdapter());
    registerAdapter(LoginDialogModelAdapter());
    registerAdapter(MainPageModelAdapter());
    registerAdapter(ModuleInfoModelAdapter());
    registerAdapter(ModullerAdapter());
    registerAdapter(NetFectDizaynListAdapter());
    registerAdapter(SeriListAdapter());
    registerAdapter(SirketModelAdapter());
    registerAdapter(SqlserverinfoAdapter());
    registerAdapter(TokenModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(YaziciListAdapter());
    registerAdapter(YaziciModelAdapter());
    registerAdapter(YaziciTipiAdapter());
  }
}
