
# Update fastlane to latest version
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push code and tag to remote for CodeMagic build"
  lane :prepare_for_build do

    increment_build_number({xcodeproj: "Runner.xcodeproj",build_number: latest_testflight_build_number + 1})
    
    puts "Build number has been incremented"
    puts "Build number: #{get_build_number(xcodeproj: "Runner.xcodeproj")}"

    add_git_tag(
      grouping: "",
      tag: "V#{get_version_number(xcodeproj: "Runner.xcodeproj", target: "Runner")}+#{get_build_number(xcodeproj: "Runner.xcodeproj")}",
      includes_lane: false,
      )

    puts "Git tag has been added"

    push_to_git_remote()

    puts "Code has been pushed to remote"

    push_git_tags()

    puts "Git tag has been pushed to remote"


  end
end
