// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tahsilat_request_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_TahsilatRequestModel _$TahsilatRequestModelFromJson(
  Map<String, dynamic> json,
) => _TahsilatRequestModel(
  aciklama: json['ACIKLAMA'] as String?,
  belgeNo: json['BELGE_NO'] as String?,
  gc: json['GC'] as String?,
  guid: json['GUID'] as String?,
  hesapKodu: json['HESAP_KODU'] as String?,
  hesapTipi: json['HESAP_TIPI'] as String?,
  kasaKodu: json['KASA_KODU'] as String?,
  plasiyerKodu: json['PLASIYER_KODU'] as String?,
  projeKodu: json['PROJE_KODU'] as String?,
  tag: json['TAG'] as String?,
  tahsilatmi: json['TAHSILATMI'] as bool?,
  tarih: json['TARIH'] == null ? null : DateTime.parse(json['TARIH'] as String),
  tutar: (json['TUTAR'] as num?)?.toDouble(),
  dovizTutari: (json['DOVIZ_TUTARI'] as num?)?.toDouble(),
  dovizTipi: (json['DOVIZ_TIPI'] as num?)?.toInt(),
  kktYontemi: json['KKT_YONTEMI'] as String?,
  raporKodu2: json['RAPOR_KODU2'] as String?,
  refKod: json['REF_KOD'] as String?,
  pickerBelgeTuru: json['PickerBelgeTuru'] as String?,
  stokKodu: json['STOK_KODU'] as String?,
  depoKodu: (json['DEPO_KODU'] as num?)?.toInt(),
  hareketTuru: json['HAREKET_TURU'] as String?,
  miktar: (json['MIKTAR'] as num?)?.toInt(),
  fiyat: (json['FIYAT'] as num?)?.toDouble(),
  dekontSeri: json['DEKONT_SERI'] as String?,
  yeniKayit: json['_YeniKayit'] as bool?,
  cariKodu: json['CARI_KODU'] as String?,
  sozlesmeKodu: json['SOZLESME_KODU'] as String?,
  krediKartNo: json['KREDI_KART_NO'] as String?,
  hedefAciklama: json['HEDEF_ACIKLAMA'] as String?,
  vadeGunu: (json['VADE_GUNU'] as num?)?.toInt(),
  bsmvTutari: (json['BSMV_TUTARI'] as num?)?.toDouble(),
  dekontIslemTuru: json['DEKONT_ISLEM_TURU'] as String?,
  dekontBelgeNo: json['DEKONT_BELGE_NO'] as String?,
  hedefHesapKodu: json['HEDEF_HESAP_KODU'] as String?,
  islemModulu: json['ISLEM_MODULU'] as String?,
  masrafMuhKodu: json['MASRAF_MUH_KODU'] as String?,
  masrafTutari: (json['MASRAF_TUTARI'] as num?)?.toDouble(),
  cariyiBorclandir: json['CARIYI_BORCLANDIR'] as bool?,
  hesapNo: json['HESAP_NO'] as String?,
  iban: json['IBAN'] as String?,
  tcmbBankaKodu: json['TCMB_BANKA_KODU'] as String?,
  tcmbSubeKodu: json['TCMB_SUBE_KODU'] as String?,
  kalemler: (json['KALEMLER'] as List<dynamic>?)
      ?.map((e) => DekontKalemler.fromJson(e as Map<String, dynamic>))
      .toList(),
  hedefCariKodu: json['HEDEF_CARI_KODU'] as String?,
  tahsilatBakiye: (json['TAHSILAT_BAKIYE'] as num?)?.toDouble(),
  odemeBakiye: (json['ODEME_BAKIYE'] as num?)?.toDouble(),
  hedefHesapReferansKodu: json['HEDEF_HESAP_REFERANS_KODU'] as String?,
  kaynakHesapReferansKodu: json['KAYNAK_HESAP_REFERANS_KODU'] as String?,
  taksitSayisi: (json['TAKSIT_SAYISI'] as num?)?.toInt(),
);

Map<String, dynamic> _$TahsilatRequestModelToJson(
  _TahsilatRequestModel instance,
) => <String, dynamic>{
  'ACIKLAMA': ?instance.aciklama,
  'BELGE_NO': ?instance.belgeNo,
  'GC': ?instance.gc,
  'GUID': ?instance.guid,
  'HESAP_KODU': ?instance.hesapKodu,
  'HESAP_TIPI': ?instance.hesapTipi,
  'KASA_KODU': ?instance.kasaKodu,
  'PLASIYER_KODU': ?instance.plasiyerKodu,
  'PROJE_KODU': ?instance.projeKodu,
  'TAG': ?instance.tag,
  'TAHSILATMI': ?instance.tahsilatmi,
  'TARIH': ?instance.tarih?.toIso8601String(),
  'TUTAR': ?instance.tutar,
  'DOVIZ_TUTARI': ?instance.dovizTutari,
  'DOVIZ_TIPI': ?instance.dovizTipi,
  'KKT_YONTEMI': ?instance.kktYontemi,
  'RAPOR_KODU2': ?instance.raporKodu2,
  'REF_KOD': ?instance.refKod,
  'PickerBelgeTuru': ?instance.pickerBelgeTuru,
  'STOK_KODU': ?instance.stokKodu,
  'DEPO_KODU': ?instance.depoKodu,
  'HAREKET_TURU': ?instance.hareketTuru,
  'MIKTAR': ?instance.miktar,
  'FIYAT': ?instance.fiyat,
  'DEKONT_SERI': ?instance.dekontSeri,
  '_YeniKayit': ?instance.yeniKayit,
  'CARI_KODU': ?instance.cariKodu,
  'SOZLESME_KODU': ?instance.sozlesmeKodu,
  'KREDI_KART_NO': ?instance.krediKartNo,
  'HEDEF_ACIKLAMA': ?instance.hedefAciklama,
  'VADE_GUNU': ?instance.vadeGunu,
  'BSMV_TUTARI': ?instance.bsmvTutari,
  'DEKONT_ISLEM_TURU': ?instance.dekontIslemTuru,
  'DEKONT_BELGE_NO': ?instance.dekontBelgeNo,
  'HEDEF_HESAP_KODU': ?instance.hedefHesapKodu,
  'ISLEM_MODULU': ?instance.islemModulu,
  'MASRAF_MUH_KODU': ?instance.masrafMuhKodu,
  'MASRAF_TUTARI': ?instance.masrafTutari,
  'CARIYI_BORCLANDIR': ?instance.cariyiBorclandir,
  'HESAP_NO': ?instance.hesapNo,
  'IBAN': ?instance.iban,
  'TCMB_BANKA_KODU': ?instance.tcmbBankaKodu,
  'TCMB_SUBE_KODU': ?instance.tcmbSubeKodu,
  'KALEMLER': ?instance.kalemler?.map((e) => e.toJson()).toList(),
  'HEDEF_CARI_KODU': ?instance.hedefCariKodu,
  'TAHSILAT_BAKIYE': ?instance.tahsilatBakiye,
  'ODEME_BAKIYE': ?instance.odemeBakiye,
  'HEDEF_HESAP_REFERANS_KODU': ?instance.hedefHesapReferansKodu,
  'KAYNAK_HESAP_REFERANS_KODU': ?instance.kaynakHesapReferansKodu,
  'TAKSIT_SAYISI': ?instance.taksitSayisi,
};

_DekontKalemler _$DekontKalemlerFromJson(Map<String, dynamic> json) =>
    _DekontKalemler(
      aciklama: json['ACIKLAMA'] as String?,
      belgeNo: json['BELGE_NO'] as String?,
      ba: json['BA'] as String?,
      dovizTipi: (json['DOVIZ_TIPI'] as num?)?.toInt(),
      dovizTutari: (json['DOVIZ_TUTARI'] as num?)?.toDouble(),
      exportRefno: json['EXPORT_REFNO'] as String?,
      exportTipi: (json['EXPORT_TIPI'] as num?)?.toInt(),
      hesapKodu: json['HESAP_KODU'] as String?,
      hesapTipi: json['HESAP_TIPI'] as String?,
      plasiyerKodu: json['PLASIYER_KODU'] as String?,
      projeKodu: json['PROJE_KODU'] as String?,
      tarih: json['TARIH'] == null
          ? null
          : DateTime.parse(json['TARIH'] as String),
      tutar: (json['TUTAR'] as num?)?.toDouble(),
      depoKodu: (json['DEPO_KODU'] as num?)?.toInt(),
      inckeyno: (json['INCKEYNO'] as num?)?.toInt(),
      seriNo: json['SERI_NO'] as String?,
      dekontNo: (json['DEKONT_NO'] as num?)?.toInt(),
      siraNo: (json['SIRA_NO'] as num?)?.toInt(),
      hesapTipiAciklama: json['HESAP_TIPI_ACIKLAMA'] as String?,
      hesapAdi: json['HESAP_ADI'] as String?,
      dovizAdi: json['DOVIZ_ADI'] as String?,
      refkey: json['REFKEY'] as String?,
      plasiyerAciklama: json['PLASIYER_ACIKLAMA'] as String?,
      muhasebeHesapTipi: json['MUHASEBE_HESAP_TIPI'] as String?,
      cariKodu: json['CARI_KODU'] as String?,
      dekontIslemTuru: json['DEKONT_ISLEM_TURU'] as String?,
      dekontSeri: json['DEKONT_SERI'] as String?,
      guid: json['GUID'] as String?,
      hedefAciklama: json['HEDEF_ACIKLAMA'] as String?,
      hedefCariKodu: json['HEDEF_CARI_KODU'] as String?,
      islemModulu: json['ISLEM_MODULU'] as String?,
      tag: json['TAG'] as String?,
      vadeGunu: (json['VADE_GUNU'] as num?)?.toInt(),
      yeniKayit: json['YENI_KAYIT'] as bool?,
    );

Map<String, dynamic> _$DekontKalemlerToJson(_DekontKalemler instance) =>
    <String, dynamic>{
      'ACIKLAMA': ?instance.aciklama,
      'BELGE_NO': ?instance.belgeNo,
      'BA': ?instance.ba,
      'DOVIZ_TIPI': ?instance.dovizTipi,
      'DOVIZ_TUTARI': ?instance.dovizTutari,
      'EXPORT_REFNO': ?instance.exportRefno,
      'EXPORT_TIPI': ?instance.exportTipi,
      'HESAP_KODU': ?instance.hesapKodu,
      'HESAP_TIPI': ?instance.hesapTipi,
      'PLASIYER_KODU': ?instance.plasiyerKodu,
      'PROJE_KODU': ?instance.projeKodu,
      'TARIH': ?instance.tarih?.toIso8601String(),
      'TUTAR': ?instance.tutar,
      'DEPO_KODU': ?instance.depoKodu,
      'INCKEYNO': ?instance.inckeyno,
      'SERI_NO': ?instance.seriNo,
      'DEKONT_NO': ?instance.dekontNo,
      'SIRA_NO': ?instance.siraNo,
      'HESAP_TIPI_ACIKLAMA': ?instance.hesapTipiAciklama,
      'HESAP_ADI': ?instance.hesapAdi,
      'DOVIZ_ADI': ?instance.dovizAdi,
      'REFKEY': ?instance.refkey,
      'PLASIYER_ACIKLAMA': ?instance.plasiyerAciklama,
      'MUHASEBE_HESAP_TIPI': ?instance.muhasebeHesapTipi,
      'CARI_KODU': ?instance.cariKodu,
      'DEKONT_ISLEM_TURU': ?instance.dekontIslemTuru,
      'DEKONT_SERI': ?instance.dekontSeri,
      'GUID': ?instance.guid,
      'HEDEF_ACIKLAMA': ?instance.hedefAciklama,
      'HEDEF_CARI_KODU': ?instance.hedefCariKodu,
      'ISLEM_MODULU': ?instance.islemModulu,
      'TAG': ?instance.tag,
      'VADE_GUNU': ?instance.vadeGunu,
      'YENI_KAYIT': ?instance.yeniKayit,
    };
