import "dart:convert";

import "package:json_annotation/json_annotation.dart";

part "profil_yetki_model.g.dart";

@JsonSerializable(createFactory: true)
class ProfilYetkiModel {
  ProfilYetkiModel();
  @JsonKey(name: "yazdirma_SatisIrs_Yazicilari")
  List<String>? yazdirmaSatisIrsYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_SatisIrs")
  List<int>? yazdirmaDizaynSatisIrs;
  @JsonKey(name: "yazdirma_SatisTalebi")
  bool? yazdirmaSatisTalebi;
  @JsonKey(name: "yazdirma_SatisTalebi_Yazicilari")
  List<String>? yazdirmaSatisTalebiYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_SatisTalebi")
  List<int>? yazdirmaDizaynSatisTalebi;
  @JsonKey(name: "yazdirma_SatisTeklifi")
  bool? yazdirmaSatisTeklifi;
  @JsonKey(name: "yazdirma_Dizayn_SatisTeklifi")
  List<int>? yazdirmaDizaynSatisTeklifi;
  @JsonKey(name: "yazdirma_Sayim")
  bool? yazdirmaSayim;
  @JsonKey(name: "yazdirma_Sayim_Yazicilari")
  List<String>? yazdirmaSayimYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_Sayim")
  List<int>? yazdirmaDizaynSayim;
  @JsonKey(name: "yazdirma_Sevkiyat_Etiketi")
  bool? yazdirmaSevkiyatEtiketi;
  @JsonKey(name: "yazdirma_Sevkiyat_Etiketi_Yazicilari")
  List<String>? yazdirmaSevkiyatEtiketiYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_SevkiyatEtiketi")
  List<int>? yazdirmaDizaynSevkiyatEtiketi;
  @JsonKey(name: "yazdirma_Sevkiyat_Etiketi_KopyaSayisiGizle")
  bool? yazdirmaSevkiyatEtiketiKopyaSayisiGizle;
  @JsonKey(name: "yazdirma_Serbest")
  bool? yazdirmaSerbest;
  @JsonKey(name: "yazdirma_Serbest_Yazicilari")
  List<dynamic>? yazdirmaSerbestYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_Serbest")
  List<int>? yazdirmaDizaynSerbest;
  @JsonKey(name: "yazdirma_SeriEtiketi")
  bool? yazdirmaSeriEtiketi;
  @JsonKey(name: "yazdirma_Seri_Etiketi_Yazicilari")
  List<String>? yazdirmaSeriEtiketiYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_SeriEtiketi")
  List<int>? yazdirmaDizaynSeriEtiketi;
  @JsonKey(name: "yazdirma_Stok_Etiketi")
  bool? yazdirmaStokEtiketi;
  @JsonKey(name: "yazdirma_Stok_Etiketi_Yazicilari")
  List<String>? yazdirmaStokEtiketiYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_StokEtiketi")
  List<int>? yazdirmaDizaynStokEtiketi;
  @JsonKey(name: "yazdirma_TahsilatMakbuzu")
  bool? yazdirmaTahsilatMakbuzu;
  @JsonKey(name: "yazdirma_Dizayn_TahsilatMakbuzu")
  List<int>? yazdirmaDizaynTahsilatMakbuzu;
  @JsonKey(name: "yazdirma_USK")
  bool? yazdirmaUsk;
  @JsonKey(name: "yazdirma_USK_Yazicilari")
  List<String>? yazdirmaUskYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_USK")
  List<int>? yazdirmaDizaynUSK;
  @JsonKey(name: "yazdirma_UretMalTop")
  bool? yazdirmaUretMalTop;
  @JsonKey(name: "yazdirma_UretMalTop_Yazicilari")
  List<dynamic>? yazdirmaUretMalTopYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_UretMalTop")
  List<dynamic>? yazdirmaDizaynUretMalTop;
  @JsonKey(name: "kullanicilar")
  List<String>? kullanicilar;
  @JsonKey(name: "sirket_TamEkranAcilsin")
  bool? sirketTamEkranAcilsin;
  @JsonKey(name: "sirket_RehberdeCariKodGizle")
  bool? sirketRehberdeCariKodGizle;
  @JsonKey(name: "sirket_RehberdeStokKodGizle")
  bool? sirketRehberdeStokKodGizle;
  @JsonKey(name: "sirket_RaporlardaFiyatGizle")
  bool? sirketRaporlardaFiyatGizle;
  @JsonKey(name: "sirket_TarihDegismesin")
  bool? sirketTarihDegismesin;
  @JsonKey(name: "sirket_DevirSirketineGiris")
  String? sirketDevirSirketineGiris;
  @JsonKey(name: "sirket_KontrolluAktar_BelgeTipleri")
  List<String>? sirketKontrolluAktarBelgeTipleri;
  @JsonKey(name: "sirket_KontrolluAktar_BelgeNoGoster")
  List<dynamic>? sirketKontrolluAktarBelgeNoGoster;
  @JsonKey(name: "sirket_KontrolAciklamasi_BelgeTipleri")
  List<dynamic>? sirketKontrolAciklamasiBelgeTipleri;
  @JsonKey(name: "sirket_TLFiyatGelsin_BelgeTipleri")
  List<dynamic>? sirketTLFiyatGelsinBelgeTipleri;
  @JsonKey(name: "sirket_KalemKayitKontrol_BelgeTipleri")
  List<dynamic>? sirketKalemKayitKontrolBelgeTipleri;
  @JsonKey(name: "sirket_aktifDepolar")
  List<int>? sirketAktifDepolar;
  @JsonKey(name: "sirket_satisDepo")
  int? sirketSatisDepo;
  @JsonKey(name: "sirket_satisDepo_Ozellestir")
  bool? sirketSatisDepoOzellestir;
  @JsonKey(name: "sirket_satisDepo_MusSip")
  int? sirketSatisDepoMusSip;
  @JsonKey(name: "sirket_satisDepo_SatisFat")
  int? sirketSatisDepoSatisFat;
  @JsonKey(name: "sirket_satisDepo_SatisIrs")
  int? sirketSatisDepoSatisIrs;
  @JsonKey(name: "sirket_alisDepo")
  int? sirketAlisDepo;
  @JsonKey(name: "sirket_iadeDepo")
  int? sirketIadeDepo;
  @JsonKey(name: "sirket_projeKodu")
  String? sirketProjeKodu;
  @JsonKey(name: "sirket_aktifProjeler")
  List<String>? sirketAktifProjeler;
  @JsonKey(name: "ayarlar_FirmaAyarlari")
  bool? ayarlarFirmaAyarlari;
  @JsonKey(name: "ayarlar_Oturumlar")
  bool? ayarlarOturumlar;
  @JsonKey(name: "sirket_SifreHatirlamaDurumu")
  String? sirketSifreHatirlamaDurumu;
  @JsonKey(name: "genel_DovizKurlari")
  bool? genelDovizKurlari;
  @JsonKey(name: "genel_DovizKurlari_Ekle")
  bool? genelDovizKurlariEkle;
  @JsonKey(name: "genel_DovizKurlari_Duzelt")
  bool? genelDovizKurlariDuzelt;
  @JsonKey(name: "genel_DovizKurlari_Sil")
  bool? genelDovizKurlariSil;
  @JsonKey(name: "genel_BelgeKontrol")
  bool? genelBelgeKontrol;
  @JsonKey(name: "genel_BelgeKontrol_Ekle")
  bool? genelBelgeKontrolEkle;
  @JsonKey(name: "genel_BelgeKontrol_Sil")
  bool? genelBelgeKontrolSil;
  @JsonKey(name: "genel_BelgeKontrol_BelgeTipleri")
  List<String>? genelBelgeKontrolBelgeTipleri;
  @JsonKey(name: "genel_BelgeKontrol_BarkodOkutsun")
  String? genelBelgeKontrolBarkodOkutsun;
  @JsonKey(name: "genel_BelgeKontrol_MiktarOtomatikGelsin")
  String? genelBelgeKontrolMiktarOtomatikGelsin;
  @JsonKey(name: "genel_BelgeKontrol_KalemDetaySorulmasin")
  String? genelBelgeKontrolKalemDetaySorulmasin;
  @JsonKey(name: "genel_BelgeKontrol_BelgeOnaySormasin")
  String? genelBelgeKontrolBelgeOnaySormasin;
  @JsonKey(name: "malKabul_FiyatDegistirilmesin")
  bool? malKabulFiyatDegistirilmesin;
  @JsonKey(name: "malKabul_AlisIrs_BelgeTipleri")
  List<int>? malKabulAlisIrsBelgeTipleri;
  @JsonKey(name: "malKabul_AlisIrs_GizlenecekAlanlar")
  List<dynamic>? malKabulAlisIrsGizlenecekAlanlar;
  @JsonKey(name: "malKabul_AlisIrs_AciklamaAlanlari")
  List<int>? malKabulAlisIrsAciklamaAlanlari;
  @JsonKey(name: "malKabul_SatinAlma")
  bool? malKabulSatinAlma;
  @JsonKey(name: "malKabul_SatinAlma_Kaydet")
  bool? malKabulSatinAlmaKaydet;
  @JsonKey(name: "malKabul_SatinAlma_Duzelt")
  bool? malKabulSatinAlmaDuzelt;
  @JsonKey(name: "malKabul_SatinAlma_Sil")
  bool? malKabulSatinAlmaSil;
  @JsonKey(name: "malKabul_AlisIrsaliyesiFiyatGor")
  bool? malKabulAlisIrsaliyesiFiyatGor;
  @JsonKey(name: "malKabul_AlisIrs_DigerSekmesiGoster")
  bool? malKabulAlisIrsDigerSekmesiGoster;
  @JsonKey(name: "malKabul_AlisIrs_SipBagSecenegi")
  String? malKabulAlisIrsSipBagSecenegi;
  @JsonKey(name: "malKabul_AlisIrs_ReferansStokUygulamasi")
  bool? malKabulAlisIrsReferansStokUygulamasi;
  @JsonKey(name: "malKabul_AlisIrs_SipBag_SipHariciKalemEklenebilir")
  bool? malKabulAlisIrsSipBagSipHariciKalemEklenebilir;
  @JsonKey(name: "malKabul_AlisIrs_SipBag_FazlaTeslimatYapilabilir")
  bool? malKabulAlisIrsSipBagFazlaTeslimatYapilabilir;
  @JsonKey(name: "malKabul_AlisIrs_SipBag_SipOkutulsun")
  bool? malKabulAlisIrsSipBagSipOkutulsun;
  @JsonKey(name: "malKabul_AlisIrs_SipBag_CokluSecim")
  bool? malKabulAlisIrsSipBagCokluSecim;
  @JsonKey(name: "malKabul_AlisIrs_SipBag_TumKalemlerSecilsin")
  bool? malKabulAlisIrsSipBagTumKalemlerSecilsin;
  @JsonKey(name: "malKabul_AlisIrs_SipBag_EslesmeDurumu")
  int? malKabulAlisIrsSipBagEslesmeDurumu;
  @JsonKey(name: "malKabul_AlisIrs_BarkodluGiris")
  bool? malKabulAlisIrsBarkodluGiris;
  @JsonKey(name: "malKabul_AlisIrs_MiktarOtomatikGelsin")
  bool? malKabulAlisIrsMiktarOtomatikGelsin;
  @JsonKey(name: "malKabul_AlisIrs_KalemDetaySorulmasin")
  bool? malKabulAlisIrsKalemDetaySorulmasin;
  @JsonKey(name: "malKabul_AlisIrs_KalemlerBirlestirilsin")
  bool? malKabulAlisIrsKalemlerBirlestirilsin;
  @JsonKey(name: "malKabul_AlisIrs_StokRehberiAcilmasin")
  bool? malKabulAlisIrsStokRehberiAcilmasin;
  @JsonKey(name: "malKabul_AlisIrs_KalemDuzeltilemesin")
  bool? malKabulAlisIrsKalemDuzeltilemesin;
  @JsonKey(name: "malKabul_AlisIrs_TekrarEdenBarkod")
  String? malKabulAlisIrsTekrarEdenBarkod;
  @JsonKey(name: "malKabul_AlisIrs_KlavyeEngelle")
  bool? malKabulAlisIrsKlavyeEngelle;
  @JsonKey(name: "malKabul_AlisIrs_Miktar1Gelsin")
  bool? malKabulAlisIrsMiktar1Gelsin;
  @JsonKey(name: "malKabul_AlisIrs_Raporlar")
  bool? malKabulAlisIrsRaporlar;
  @JsonKey(name: "malKabul_AlisIrs_KalemRaporu")
  bool? malKabulAlisIrsKalemRaporu;
  @JsonKey(name: "malKabul_AlisIrs_OtoBasimYap")
  bool? malKabulAlisIrsOtoBasimYap;
  @JsonKey(name: "malKabul_AlisIrs_KacGunlukKayitlarListelensin")
  int? malKabulAlisIrsKacGunlukKayitlarListelensin;
  @JsonKey(name: "malKabul_AlisIrs_FiyatSirasi")
  int? malKabulAlisIrsFiyatSirasi;
  @JsonKey(name: "malKabul_AlisIrs_CariKoduDegistir")
  bool? malKabulAlisIrsCariKoduDegistir;
  @JsonKey(name: "malKabul_AlisIrs_CariRehPlaEslesmesin")
  bool? malKabulAlisIrsCariRehPlaEslesmesin;
  @JsonKey(name: "malKabul_Iade")
  bool? malKabulIade;
  @JsonKey(name: "malKabul_Iade_Kaydet")
  bool? malKabulIadeKaydet;
  @JsonKey(name: "malKabul_Iade_Duzelt")
  bool? malKabulIadeDuzelt;
  @JsonKey(name: "malKabul_Iade_Sil")
  bool? malKabulIadeSil;
  @JsonKey(name: "malKabul_AlisFaturasi_BelgeTipleri")
  List<int>? malKabulAlisFaturasiBelgeTipleri;
  @JsonKey(name: "malKabul_AlisFaturasi")
  bool? malKabulAlisFaturasi;
  @JsonKey(name: "malKabul_AlisFaturasi_Kaydet")
  bool? malKabulAlisFaturasiKaydet;
  @JsonKey(name: "malKabul_AlisFaturasi_Duzelt")
  bool? malKabulAlisFaturasiDuzelt;
  @JsonKey(name: "malKabul_AlisFaturasi_Sil")
  bool? malKabulAlisFaturasiSil;
  @JsonKey(name: "malKabul_AlisFat_DigerSekmesiGoster")
  bool? malKabulAlisFatDigerSekmesiGoster;
  @JsonKey(name: "malKabul_AlisFat_KacGunlukKayitlarListelensin")
  int? malKabulAlisFatKacGunlukKayitlarListelensin;
  @JsonKey(name: "malKabul_AlisFat_FiyatSirasi")
  int? malKabulAlisFatFiyatSirasi;
  @JsonKey(name: "malKabul_AlisFat_Aciklamalar_YetkiTuru")
  String? malKabulAlisFatAciklamalarYetkiTuru;
  @JsonKey(name: "malKabul_AlisFat_AciklamaAlanlari")
  List<int>? malKabulAlisFatAciklamaAlanlari;
  @JsonKey(name: "malKabul_AlisFat_CariKoduDegistir")
  bool? malKabulAlisFatCariKoduDegistir;
  @JsonKey(name: "malKabul_AlisFat_BarkodluGiris")
  bool? malKabulAlisFatBarkodluGiris;
  @JsonKey(name: "malKabul_AlisFat_MiktarOtomatikGelsin")
  bool? malKabulAlisFatMiktarOtomatikGelsin;
  @JsonKey(name: "malKabul_AlisFat_KalemDetaySorulmasin")
  bool? malKabulAlisFatKalemDetaySorulmasin;
  @JsonKey(name: "malKabul_AlisFat_StokRehberiAcilmasin")
  bool? malKabulAlisFatStokRehberiAcilmasin;
  @JsonKey(name: "malKabul_AlisFat_KalemDuzeltilemesin")
  bool? malKabulAlisFatKalemDuzeltilemesin;
  @JsonKey(name: "malKabul_AlisFat_KlavyeEngelle")
  bool? malKabulAlisFatKlavyeEngelle;
  @JsonKey(name: "malKabul_AlisFat_Miktar1Gelsin")
  bool? malKabulAlisFatMiktar1Gelsin;
  @JsonKey(name: "malKabul_AlisFat_ReferansStokUygulamasi")
  bool? malKabulAlisFatReferansStokUygulamasi;
  @JsonKey(name: "malKabul_AlisFat_SipBag_SipHariciKalemEklenebilir")
  bool? malKabulAlisFatSipBagSipHariciKalemEklenebilir;
  @JsonKey(name: "malKabul_AlisFat_SipBag_FazlaTeslimatYapilabilir")
  bool? malKabulAlisFatSipBagFazlaTeslimatYapilabilir;
  @JsonKey(name: "malKabul_AlisFat_SipBag_SipOkutulsun")
  bool? malKabulAlisFatSipBagSipOkutulsun;
  @JsonKey(name: "malKabul_AlisFat_SipBag_CokluSecim")
  bool? malKabulAlisFatSipBagCokluSecim;
  @JsonKey(name: "malKabul_AlisFat_SipBag_TumKalemlerSecilsin")
  bool? malKabulAlisFatSipBagTumKalemlerSecilsin;
  @JsonKey(name: "malKabul_AlisFat_SipBag_EslesmeDurumu")
  int? malKabulAlisFatSipBagEslesmeDurumu;
  @JsonKey(name: "malKabul_AlisFat_Raporlar")
  bool? malKabulAlisFatRaporlar;
  @JsonKey(name: "malKabul_AlisFat_KalemRaporu")
  bool? malKabulAlisFatKalemRaporu;
  @JsonKey(name: "malKabul_Mustahsil")
  bool? malKabulMustahsil;
  @JsonKey(name: "malKabul_Mustahsil_Ekle")
  bool? malKabulMustahsilEkle;
  @JsonKey(name: "malKabul_Mustahsil_Duzelt")
  bool? malKabulMustahsilDuzelt;
  @JsonKey(name: "malKabul_Mustahsil_Sil")
  bool? malKabulMustahsilSil;
  @JsonKey(name: "transfer_DAT")
  bool? transferDat;
  @JsonKey(name: "transfer_DAT_Kaydet")
  bool? transferDatKaydet;
  @JsonKey(name: "transfer_DAT_Duzelt")
  bool? transferDatDuzelt;
  @JsonKey(name: "transfer_DAT_Sil")
  bool? transferDatSil;
  @JsonKey(name: "transfer_DAT_FiyatGor")
  bool? transferDatFiyatGor;
  @JsonKey(name: "transfer_DAT_OtoEtiketBas")
  bool? transferDatOtoEtiketBas;
  @JsonKey(name: "transfer_DAT_VarsayilanCikisDepo")
  int? transferDatVarsayilanCikisDepo;
  @JsonKey(name: "transfer_DAT_VarsayilanGirisDepo")
  int? transferDatVarsayilanGirisDepo;
  @JsonKey(name: "transfer_DAT_eIrsIsaretleyemesin")
  bool? transferDatEIrsIsaretleyemesin;
  @JsonKey(name: "transfer_DAT_DigerSekmesiGoster")
  bool? transferDatDigerSekmesiGoster;
  @JsonKey(name: "transfer_DAT_BarkodluGiris")
  bool? transferDatBarkodluGiris;
  @JsonKey(name: "transfer_DAT_MiktarOtomatikGelsin")
  bool? transferDatMiktarOtomatikGelsin;
  @JsonKey(name: "transfer_DAT_KalemDetaySorulmasin")
  bool? transferDatKalemDetaySorulmasin;
  @JsonKey(name: "transfer_DAT_StokRehberiAcilmasin")
  bool? transferDatStokRehberiAcilmasin;
  @JsonKey(name: "transfer_DAT_KalemDuzeltilemesin")
  bool? transferDatKalemDuzeltilemesin;
  @JsonKey(name: "transfer_DAT_KlavyeEngelle")
  bool? transferDatKlavyeEngelle;
  @JsonKey(name: "transfer_DAT_Miktar1Gelsin")
  bool? transferDatMiktar1Gelsin;
  @JsonKey(name: "transfer_DAT_KalemlerBirlestirilsin")
  bool? transferDatKalemlerBirlestirilsin;
  @JsonKey(name: "transfer_DAT_KacGunlukKayitlarListelensin")
  int? transferDatKacGunlukKayitlarListelensin;
  @JsonKey(name: "transfer_DAT_OnayIslemleri")
  bool? transferDatOnayIslemleri;
  @JsonKey(name: "transfer_DAT_OnayIslemleri_Depolar")
  List<dynamic>? transferDatOnayIslemleriDepolar;
  @JsonKey(name: "transfer_DAT_EkAlan2Hatirla")
  bool? transferDatEkAlan2Hatirla;
  @JsonKey(name: "transfer_DAT_EkAlan2Tablodan")
  bool? transferDatEkAlan2Tablodan;
  @JsonKey(name: "transfer_DAT_SeriGirisHarYapabilsin")
  bool? transferDatSeriGirisHarYapabilsin;
  @JsonKey(name: "transfer_DAT_Birim1denKaydet")
  bool? transferDatBirim1DenKaydet;
  @JsonKey(name: "transfer_DAT_Barkod2Sor")
  bool? transferDatBarkod2Sor;
  @JsonKey(name: "transfer_DAT_BosGecilmeyecekAlanlar")
  List<dynamic>? transferDatBosGecilmeyecekAlanlar;
  @JsonKey(name: "transfer_DAT_GizlenecekAlanlar")
  List<dynamic>? transferDatGizlenecekAlanlar;
  @JsonKey(name: "transfer_DAT_DegismeyecekAlanlar")
  List<dynamic>? transferDatDegismeyecekAlanlar;
  @JsonKey(name: "transfer_DAT_AciklamaAlanlari")
  List<dynamic>? transferDatAciklamaAlanlari;
  @JsonKey(name: "transfer_DAT_SipBagSecenegi")
  String? transferDatSipBagSecenegi;
  @JsonKey(name: "transfer_DAT_ReferansStokUygulamasi")
  bool? transferDatReferansStokUygulamasi;
  @JsonKey(name: "transfer_DAT_SipBag_SipHariciKalemEklenebilir")
  bool? transferDatSipBagSipHariciKalemEklenebilir;
  @JsonKey(name: "transfer_DAT_SipBag_FazlaTeslimatYapilabilir")
  bool? transferDatSipBagFazlaTeslimatYapilabilir;
  @JsonKey(name: "transfer_DAT_SipBag_SipOkutulsun")
  bool? transferDatSipBagSipOkutulsun;
  @JsonKey(name: "transfer_DAT_SipBag_SipOkutulsun_Miktar2BazAl")
  bool? transferDatSipBagSipOkutulsunMiktar2BazAl;
  @JsonKey(name: "transfer_DAT_SipBag_SipOkutulsun_KalanMiktarGelsin")
  String? transferDatSipBagSipOkutulsunKalanMiktarGelsin;
  @JsonKey(name: "transfer_DAT_SipBag_CokluSecim")
  bool? transferDatSipBagCokluSecim;
  @JsonKey(name: "transfer_DAT_SipBag_TumKalemlerSecilsin")
  bool? transferDatSipBagTumKalemlerSecilsin;
  @JsonKey(name: "transfer_DAT_SipBag_EslesmeDurumu")
  int? transferDatSipBagEslesmeDurumu;
  @JsonKey(name: "transfer_DAT_SipBag_MalToplananlarGelsin")
  bool? transferDatSipBagMalToplananlarGelsin;
  @JsonKey(name: "transfer_DAT_SipBag_SevkOnayliSiparislerGelsin")
  bool? transferDatSipBagSevkOnayliSiparislerGelsin;
  @JsonKey(name: "transfer_AG")
  bool? transferAg;
  @JsonKey(name: "transfer_AG_Kaydet")
  bool? transferAgKaydet;
  @JsonKey(name: "transfer_AG_Duzelt")
  bool? transferAgDuzelt;
  @JsonKey(name: "transfer_AG_Sil")
  bool? transferAgSil;
  @JsonKey(name: "transfer_AG_FiyatGor")
  bool? transferAgFiyatGor;
  @JsonKey(name: "transfer_AG_KacGunlukKayitlarListelensin")
  int? transferAgKacGunlukKayitlarListelensin;
  @JsonKey(name: "transfer_AG_VarsayilanDepo")
  int? transferAgVarsayilanDepo;
  @JsonKey(name: "transfer_AG_DigerSekmesiGoster")
  bool? transferAgDigerSekmesiGoster;
  @JsonKey(name: "transfer_AG_BelgeKopyala")
  bool? transferAgBelgeKopyala;
  @JsonKey(name: "transfer_AG_OtoBasimYap")
  bool? transferAgOtoBasimYap;
  @JsonKey(name: "transfer_AG_SeriGirisHarYapabilsin")
  bool? transferAgSeriGirisHarYapabilsin;
  @JsonKey(name: "transfer_AG_BarkodluGiris")
  bool? transferAgBarkodluGiris;
  @JsonKey(name: "transfer_AG_MiktarOtomatikGelsin")
  bool? transferAgMiktarOtomatikGelsin;
  @JsonKey(name: "transfer_AG_KalemDetaySorulmasin")
  bool? transferAgKalemDetaySorulmasin;
  @JsonKey(name: "transfer_AG_StokRehberiAcilmasin")
  bool? transferAgStokRehberiAcilmasin;
  @JsonKey(name: "transfer_AG_KalemDuzeltilemesin")
  bool? transferAgKalemDuzeltilemesin;
  @JsonKey(name: "transfer_AG_KlavyeEngelle")
  bool? transferAgKlavyeEngelle;
  @JsonKey(name: "transfer_AG_Miktar1Gelsin")
  bool? transferAgMiktar1Gelsin;
  @JsonKey(name: "transfer_AG_ReferansStokUygulamasi")
  bool? transferAgReferansStokUygulamasi;
  @JsonKey(name: "transfer_AG_SipBag_SipHariciKalemEklenebilir")
  bool? transferAgSipBagSipHariciKalemEklenebilir;
  @JsonKey(name: "transfer_AG_SipBag_FazlaTeslimatYapilabilir")
  bool? transferAgSipBagFazlaTeslimatYapilabilir;
  @JsonKey(name: "transfer_AG_SipBag_SipOkutulsun")
  bool? transferAgSipBagSipOkutulsun;
  @JsonKey(name: "transfer_AG_SipBag_SipOkutulsun_Miktar2BazAl")
  bool? transferAgSipBagSipOkutulsunMiktar2BazAl;
  @JsonKey(name: "transfer_AG_SipBag_CokluSecim")
  bool? transferAgSipBagCokluSecim;
  @JsonKey(name: "transfer_AG_SipBag_TumKalemlerSecilsin")
  bool? transferAgSipBagTumKalemlerSecilsin;
  @JsonKey(name: "transfer_AG_SipBag_EslesmeDurumu")
  int? transferAgSipBagEslesmeDurumu;
  @JsonKey(name: "transfer_AG_SipBag_MalToplananlarGelsin")
  bool? transferAgSipBagMalToplananlarGelsin;
  @JsonKey(name: "transfer_AG_SipBag_SevkOnayliSiparislerGelsin")
  bool? transferAgSipBagSevkOnayliSiparislerGelsin;
  @JsonKey(name: "transfer_AC")
  bool? transferAc;
  @JsonKey(name: "transfer_AC_Kaydet")
  bool? transferAcKaydet;
  @JsonKey(name: "transfer_AC_Duzelt")
  bool? transferAcDuzelt;
  @JsonKey(name: "transfer_AC_Sil")
  bool? transferAcSil;
  @JsonKey(name: "transfer_AC_FiyatGor")
  bool? transferAcFiyatGor;
  @JsonKey(name: "transfer_AC_KacGunlukKayitlarListelensin")
  int? transferAcKacGunlukKayitlarListelensin;
  @JsonKey(name: "transfer_AC_VarsayilanDepo")
  int? transferAcVarsayilanDepo;
  @JsonKey(name: "transfer_AC_eIrsIsaretleyemesin")
  bool? transferAcEIrsIsaretleyemesin;
  @JsonKey(name: "transfer_AC_DigerSekmesiGoster")
  bool? transferAcDigerSekmesiGoster;
  @JsonKey(name: "transfer_AC_BelgeKopyala")
  bool? transferAcBelgeKopyala;
  @JsonKey(name: "transfer_AC_OtoBasimYap")
  bool? transferAcOtoBasimYap;
  @JsonKey(name: "transfer_AC_SeriGirisHarYapabilsin")
  bool? transferAcSeriGirisHarYapabilsin;
  @JsonKey(name: "transfer_AC_EkAlan2Tablodan")
  bool? transferAcEkAlan2Tablodan;
  @JsonKey(name: "transfer_AC_EkAlan2Hatirla")
  bool? transferAcEkAlan2Hatirla;
  @JsonKey(name: "transfer_AC_MinStokMikGoster")
  String? transferAcMinStokMikGoster;
  @JsonKey(name: "transfer_AC_BosGecilmeyecekAlanlar")
  List<dynamic>? transferAcBosGecilmeyecekAlanlar;
  @JsonKey(name: "transfer_AC_BarkodluGiris")
  bool? transferAcBarkodluGiris;
  @JsonKey(name: "transfer_AC_MiktarOtomatikGelsin")
  bool? transferAcMiktarOtomatikGelsin;
  @JsonKey(name: "transfer_AC_KalemDetaySorulmasin")
  bool? transferAcKalemDetaySorulmasin;
  @JsonKey(name: "transfer_AC_StokRehberiAcilmasin")
  bool? transferAcStokRehberiAcilmasin;
  @JsonKey(name: "transfer_AC_KalemDuzeltilemesin")
  bool? transferAcKalemDuzeltilemesin;
  @JsonKey(name: "transfer_AC_KlavyeEngelle")
  bool? transferAcKlavyeEngelle;
  @JsonKey(name: "transfer_AC_Miktar1Gelsin")
  bool? transferAcMiktar1Gelsin;
  @JsonKey(name: "transfer_AC_ReferansStokUygulamasi")
  bool? transferAcReferansStokUygulamasi;
  @JsonKey(name: "transfer_AC_SipBag_SipHariciKalemEklenebilir")
  bool? transferAcSipBagSipHariciKalemEklenebilir;
  @JsonKey(name: "transfer_AC_SipBag_FazlaTeslimatYapilabilir")
  bool? transferAcSipBagFazlaTeslimatYapilabilir;
  @JsonKey(name: "transfer_AC_SipBag_SipOkutulsun")
  bool? transferAcSipBagSipOkutulsun;
  @JsonKey(name: "transfer_AC_SipBag_SipOkutulsun_Miktar2BazAl")
  bool? transferAcSipBagSipOkutulsunMiktar2BazAl;
  @JsonKey(name: "transfer_AC_SipBag_CokluSecim")
  bool? transferAcSipBagCokluSecim;
  @JsonKey(name: "transfer_AC_SipBag_TumKalemlerSecilsin")
  bool? transferAcSipBagTumKalemlerSecilsin;
  @JsonKey(name: "transfer_AC_SipBag_EslesmeDurumu")
  int? transferAcSipBagEslesmeDurumu;
  @JsonKey(name: "transfer_AC_SipBag_MalToplananlarGelsin")
  bool? transferAcSipBagMalToplananlarGelsin;
  @JsonKey(name: "transfer_AC_SipBag_SevkOnayliSiparislerGelsin")
  bool? transferAcSipBagSevkOnayliSiparislerGelsin;
  @JsonKey(name: "transfer_DepoTalebi")
  bool? transferDepoTalebi;
  @JsonKey(name: "transfer_DepoTalebi_Sil")
  bool? transferDepoTalebiSil;
  @JsonKey(name: "transfer_DepoTalebi_MalTop")
  bool? transferDepoTalebiMalTop;
  @JsonKey(name: "transfer_DepoTalebi_MalTop_FazlaTeslimat")
  String? transferDepoTalebiMalTopFazlaTeslimat;
  @JsonKey(name: "hucre_GiristeHucreYerlestir")
  bool? hucreGiristeHucreYerlestir;
  @JsonKey(name: "hucre_CikistaHucreYerlestir")
  bool? hucreCikistaHucreYerlestir;
  @JsonKey(name: "hucre_Yerlestir")
  bool? hucreYerlestir;
  @JsonKey(name: "hucre_YerlestirBelgesiz")
  bool? hucreYerlestirBelgesiz;
  @JsonKey(name: "hucre_Yerlestir_KlavyeEngelle")
  bool? hucreYerlestirKlavyeEngelle;
  @JsonKey(name: "hucre_Yerlestir_RehberdenStokSecilmesin")
  bool? hucreYerlestirRehberdenStokSecilmesin;
  @JsonKey(name: "hucre_Yerlestir_HangiHucrede")
  bool? hucreYerlestirHangiHucrede;
  @JsonKey(name: "hucre_Yerlestir_BelgeTipleri")
  List<String>? hucreYerlestirBelgeTipleri;
  @JsonKey(name: "hucre_Bosalt")
  bool? hucreBosalt;
  @JsonKey(name: "hucre_BosaltBelgesiz")
  bool? hucreBosaltBelgesiz;
  @JsonKey(name: "hucre_Bosalt_KlavyeEngelle")
  bool? hucreBosaltKlavyeEngelle;
  @JsonKey(name: "hucre_Bosalt_RehberdenStokSecilmesin")
  bool? hucreBosaltRehberdenStokSecilmesin;
  @JsonKey(name: "hucre_Bosalt_HangiHucrede")
  bool? hucreBosaltHangiHucrede;
  @JsonKey(name: "hucre_Bosalt_BelgeTipleri")
  List<String>? hucreBosaltBelgeTipleri;
  @JsonKey(name: "hucre_Arama")
  bool? hucreArama;
  @JsonKey(name: "hucre_AramaTumDepolar")
  bool? hucreAramaTumDepolar;
  @JsonKey(name: "hucre_AramaOzelFonksiyon")
  String? hucreAramaOzelFonksiyon;
  @JsonKey(name: "hucre_Transfer")
  bool? hucreTransfer;
  @JsonKey(name: "hucre_Transfer_KlavyeEngelle")
  bool? hucreTransferKlavyeEngelle;
  @JsonKey(name: "hucre_Transfer_RehberdenStokSecilmesin")
  bool? hucreTransferRehberdenStokSecilmesin;
  @JsonKey(name: "hucre_Transfer_BelgeTipleri")
  List<String>? hucreTransferBelgeTipleri;
  @JsonKey(name: "hucre_Listesi")
  bool? hucreListesi;
  @JsonKey(name: "hucre_Bosalt_OtomatikStokEtiketiYazdir")
  bool? hucreBosaltOtomatikStokEtiketiYazdir;
  @JsonKey(name: "hucre_BakiyeDurumu")
  bool? hucreBakiyeDurumu;
  @JsonKey(name: "hucre_Hareketleri")
  bool? hucreHareketleri;
  @JsonKey(name: "hucre_Hareketleri_Sil")
  bool? hucreHareketleriSil;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesi_BelgeTipleri")
  List<dynamic>? sevkiyatSatisIrsaliyesiBelgeTipleri;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesi_GizlenecekAlanlar")
  List<dynamic>? sevkiyatSatisIrsaliyesiGizlenecekAlanlar;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesi_DegismeyecekAlanlar")
  List<dynamic>? sevkiyatSatisIrsaliyesiDegismeyecekAlanlar;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesi")
  bool? sevkiyatSatisIrsaliyesi;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesiKayit")
  bool? sevkiyatSatisIrsaliyesiKayit;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesiDuzeltme")
  bool? sevkiyatSatisIrsaliyesiDuzeltme;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesiSilme")
  bool? sevkiyatSatisIrsaliyesiSilme;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesiFiyatGor")
  bool? sevkiyatSatisIrsaliyesiFiyatGor;
  @JsonKey(name: "sevkiyat_SatisIrs_DigerSekmesiGoster")
  bool? sevkiyatSatisIrsDigerSekmesiGoster;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesi_SipBagSecenegi")
  String? sevkiyatSatisIrsaliyesiSipBagSecenegi;
  @JsonKey(name: "sevkiyat_SatisIrs_ReferansStokUygulamasi")
  bool? sevkiyatSatisIrsReferansStokUygulamasi;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_SipHariciKalemEklenebilir")
  bool? sevkiyatSatisIrsSipBagSipHariciKalemEklenebilir;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_FazlaTeslimatYapilabilir")
  bool? sevkiyatSatisIrsSipBagFazlaTeslimatYapilabilir;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_SipOkutulsun")
  bool? sevkiyatSatisIrsSipBagSipOkutulsun;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_SipOkutulsun_Miktar2BazAl")
  bool? sevkiyatSatisIrsSipBagSipOkutulsunMiktar2BazAl;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_SipOkutulsun_KalanMiktarGelsin")
  String? sevkiyatSatisIrsSipBagSipOkutulsunKalanMiktarGelsin;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_CokluSecim")
  bool? sevkiyatSatisIrsSipBagCokluSecim;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_TumKalemlerSecilsin")
  bool? sevkiyatSatisIrsSipBagTumKalemlerSecilsin;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_EslesmeDurumu")
  int? sevkiyatSatisIrsSipBagEslesmeDurumu;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_MalToplananlarGelsin")
  bool? sevkiyatSatisIrsSipBagMalToplananlarGelsin;
  @JsonKey(name: "sevkiyat_SatisIrs_SipBag_SevkOnayliSiparislerGelsin")
  bool? sevkiyatSatisIrsSipBagSevkOnayliSiparislerGelsin;
  @JsonKey(name: "sevkiyat_FiyatDegistirilmesin")
  bool? sevkiyatFiyatDegistirilmesin;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesi_EIrsaliyeDuzenleyemesin")
  bool? sevkiyatSatisIrsaliyesiEIrsaliyeDuzenleyemesin;
  @JsonKey(name: "sevkiyat_SatisIrs_KalemlerBirlestirilsin")
  bool? sevkiyatSatisIrsKalemlerBirlestirilsin;
  @JsonKey(name: "sevkiyat_SatisIrs_OtoBasimYap")
  bool? sevkiyatSatisIrsOtoBasimYap;
  @JsonKey(name: "sevkiyat_SatisIrs_KacGunlukKayitlarListelensin")
  int? sevkiyatSatisIrsKacGunlukKayitlarListelensin;
  @JsonKey(name: "sevkiyat_SatisIrs_FiyatSirasi")
  int? sevkiyatSatisIrsFiyatSirasi;
  @JsonKey(name: "sevkiyat_SatisIrs_SeriGirisHarYapabilsin")
  bool? sevkiyatSatisIrsSeriGirisHarYapabilsin;
  @JsonKey(name: "sevkiyat_SatisIrs_EkAlan2Tablodan")
  bool? sevkiyatSatisIrsEkAlan2Tablodan;
  @JsonKey(name: "sevkiyat_SatisIrs_EkAlan2Hatirla")
  bool? sevkiyatSatisIrsEkAlan2Hatirla;
  @JsonKey(name: "sevkiyat_SatisIrs_OlcuBirimi")
  int? sevkiyatSatisIrsOlcuBirimi;
  @JsonKey(name: "sevkiyat_SatisIrs_CariKoduDegistir")
  bool? sevkiyatSatisIrsCariKoduDegistir;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxIskUygulamasi")
  bool? sevkiyatSatisIrsMaxIskUygulamasi;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxSatIsk1")
  double? sevkiyatSatisIrsMaxSatIsk1;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxSatIsk2")
  double? sevkiyatSatisIrsMaxSatIsk2;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxSatIsk3")
  double? sevkiyatSatisIrsMaxSatIsk3;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxSatIsk4")
  double? sevkiyatSatisIrsMaxSatIsk4;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxSatIsk5")
  double? sevkiyatSatisIrsMaxSatIsk5;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxSatIsk6")
  double? sevkiyatSatisIrsMaxSatIsk6;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxGenIsk1")
  double? sevkiyatSatisIrsMaxGenIsk1;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxGenIsk2")
  double? sevkiyatSatisIrsMaxGenIsk2;
  @JsonKey(name: "sevkiyat_SatisIrs_MaxGenIsk3")
  double? sevkiyatSatisIrsMaxGenIsk3;
  @JsonKey(name: "sevkiyat_SatisIrs_DipFiyatUygulamasi")
  bool? sevkiyatSatisIrsDipFiyatUygulamasi;
  @JsonKey(name: "sevkiyat_SatisIrs_DipFiyatSaha")
  String? sevkiyatSatisIrsDipFiyatSaha;
  @JsonKey(name: "sevkiyat_SatisIrs_DipFiyatEylem")
  String? sevkiyatSatisIrsDipFiyatEylem;
  @JsonKey(name: "sevkiyat_SatisIrs_BarkodluGiris")
  bool? sevkiyatSatisIrsBarkodluGiris;
  @JsonKey(name: "sevkiyat_SatisIrs_MiktarOtomatikGelsin")
  bool? sevkiyatSatisIrsMiktarOtomatikGelsin;
  @JsonKey(name: "sevkiyat_SatisIrs_KalemDetaySorulmasin")
  bool? sevkiyatSatisIrsKalemDetaySorulmasin;
  @JsonKey(name: "sevkiyat_SatisIrs_StokRehberiAcilmasin")
  bool? sevkiyatSatisIrsStokRehberiAcilmasin;
  @JsonKey(name: "sevkiyat_SatisIrs_KalemDuzeltilemesin")
  bool? sevkiyatSatisIrsKalemDuzeltilemesin;
  @JsonKey(name: "sevkiyat_SatisIrs_KlavyeEngelle")
  bool? sevkiyatSatisIrsKlavyeEngelle;
  @JsonKey(name: "sevkiyat_SatisIrs_Miktar1Gelsin")
  bool? sevkiyatSatisIrsMiktar1Gelsin;
  @JsonKey(name: "sevkiyat_SatisIrs_BakiyesizStokSecilmesin")
  bool? sevkiyatSatisIrsBakiyesizStokSecilmesin;
  @JsonKey(name: "sevkiyat_SatisIrs_Raporlar")
  bool? sevkiyatSatisIrsRaporlar;
  @JsonKey(name: "sevkiyat_SatisIrs_KalemRaporu")
  bool? sevkiyatSatisIrsKalemRaporu;
  @JsonKey(name: "sevkiyat_SatisFat_BelgeTipleri")
  List<dynamic>? sevkiyatSatisFatBelgeTipleri;
  @JsonKey(name: "sevkiyat_SatisFat_VarsayilanBelgeTipi")
  int? sevkiyatSatisFatVarsayilanBelgeTipi;
  @JsonKey(name: "sevkiyat_SatisFat")
  bool? sevkiyatSatisFat;
  @JsonKey(name: "sevkiyat_SatisFat_Kaydet")
  bool? sevkiyatSatisFatKaydet;
  @JsonKey(name: "sevkiyat_SatisFat_Duzelt")
  bool? sevkiyatSatisFatDuzelt;
  @JsonKey(name: "sevkiyat_SatisFat_Sil")
  bool? sevkiyatSatisFatSil;
  @JsonKey(name: "sevkiyat_SatisFat_ToplamlarCariTahsilatIslemleri")
  bool? sevkiyatSatisFatToplamlarCariTahsilatIslemleri;
  @JsonKey(name: "sevkiyat_SatisFat_KayittanSonraTaslakOlustur")
  bool? sevkiyatSatisFatKayittanSonraTaslakOlustur;
  @JsonKey(name: "sevkiyat_SatisFat_OtomatikBasimYap")
  bool? sevkiyatSatisFatOtomatikBasimYap;
  @JsonKey(name: "sevkiyat_SatisFat_DigerSekmesiGoster")
  bool? sevkiyatSatisFatDigerSekmesiGoster;
  @JsonKey(name: "sevkiyat_SatisFat_FiyatDegistirilmesin")
  bool? sevkiyatSatisFatFiyatDegistirilmesin;
  @JsonKey(name: "sevkiyat_SatisFat_KacGunlukKayitlarListelensin")
  int? sevkiyatSatisFatKacGunlukKayitlarListelensin;
  @JsonKey(name: "sevkiyat_SatisFat_FiyatSirasi")
  int? sevkiyatSatisFatFiyatSirasi;
  @JsonKey(name: "sevkiyat_SatisFat_KalemlerBirlestirilsin")
  bool? sevkiyatSatisFatKalemlerBirlestirilsin;
  @JsonKey(name: "sevkiyat_SatisFat_EkAlan2Tablodan")
  bool? sevkiyatSatisFatEkAlan2Tablodan;
  @JsonKey(name: "sevkiyat_SatisFat_EkAlan2Hatirla")
  bool? sevkiyatSatisFatEkAlan2Hatirla;
  @JsonKey(name: "sevkiyat_SatisFat_Filtre")
  String? sevkiyatSatisFatFiltre;
  @JsonKey(name: "sevkiyat_SatisFat_FiltreSQL")
  String? sevkiyatSatisFatFiltreSQL;
  @JsonKey(name: "sevkiyat_SatisFat_OlcuBirimi")
  int? sevkiyatSatisFatOlcuBirimi;
  @JsonKey(name: "sevkiyat_SatisFat_AciklamaAlanlari")
  List<int>? sevkiyatSatisFatAciklamaAlanlari;
  @JsonKey(name: "sevkiyat_SatisFat_BosGecilmeyecekAlanlar")
  List<dynamic>? sevkiyatSatisFatBosGecilmeyecekAlanlar;
  @JsonKey(name: "sevkiyat_SatisFat_GizlenecekAlanlar")
  List<dynamic>? sevkiyatSatisFatGizlenecekAlanlar;
  @JsonKey(name: "sevkiyat_SatisFat_DegismeyecekAlanlar")
  List<dynamic>? sevkiyatSatisFatDegismeyecekAlanlar;
  @JsonKey(name: "sevkiyat_SatisFat_SeriGirisHarYapabilsin")
  bool? sevkiyatSatisFatSeriGirisHarYapabilsin;
  @JsonKey(name: "sevkiyat_SatisFat_CariKoduDegistir")
  bool? sevkiyatSatisFatCariKoduDegistir;
  @JsonKey(name: "sevkiyat_SatisFaturasi_SipBagSecenegi")
  String? sevkiyatSatisFaturasiSipBagSecenegi;
  @JsonKey(name: "sevkiyat_SatisFat_ReferansStokUygulamasi")
  bool? sevkiyatSatisFatReferansStokUygulamasi;
  @JsonKey(name: "sevkiyat_SatisFat_SipBag_SipHariciKalemEklenebilir")
  bool? sevkiyatSatisFatSipBagSipHariciKalemEklenebilir;
  @JsonKey(name: "sevkiyat_SatisFat_SipBag_FazlaTeslimatYapilabilir")
  bool? sevkiyatSatisFatSipBagFazlaTeslimatYapilabilir;
  @JsonKey(name: "sevkiyat_SatisFat_SipBag_SipOkutulsun")
  bool? sevkiyatSatisFatSipBagSipOkutulsun;
  @JsonKey(name: "sevkiyat_SatisFat_SipBag_SipOkutulsun_Miktar2BazAl")
  bool? sevkiyatSatisFatSipBagSipOkutulsunMiktar2BazAl;
  @JsonKey(name: "sevkiyat_SatisFat_SipBag_CokluSecim")
  bool? sevkiyatSatisFatSipBagCokluSecim;
  @JsonKey(name: "sevkiyat_SatisFat_SipBag_TumKalemlerSecilsin")
  bool? sevkiyatSatisFatSipBagTumKalemlerSecilsin;
  @JsonKey(name: "sevkiyat_SatisFat_SipBag_EslesmeDurumu")
  int? sevkiyatSatisFatSipBagEslesmeDurumu;
  @JsonKey(name: "sevkiyat_SatisFat_SipBag_SevkOnayliSiparislerGelsin")
  bool? sevkiyatSatisFatSipBagSevkOnayliSiparislerGelsin;
  @JsonKey(name: "sevkiyat_SatisFat_BarkodluGiris")
  bool? sevkiyatSatisFatBarkodluGiris;
  @JsonKey(name: "sevkiyat_SatisFaturasi_MiktarOtomatikGelsin")
  bool? sevkiyatSatisFaturasiMiktarOtomatikGelsin;
  @JsonKey(name: "sevkiyat_SatisFaturasi_KalemDetaySorulmasin")
  bool? sevkiyatSatisFaturasiKalemDetaySorulmasin;
  @JsonKey(name: "sevkiyat_SatisFat_BarkodSayisiSaklanacakAlan")
  String? sevkiyatSatisFatBarkodSayisiSaklanacakAlan;
  @JsonKey(name: "sevkiyat_SatisFat_StokRehberiAcilmasin")
  bool? sevkiyatSatisFatStokRehberiAcilmasin;
  @JsonKey(name: "sevkiyat_SatisFat_KalemDuzeltilemesin")
  bool? sevkiyatSatisFatKalemDuzeltilemesin;
  @JsonKey(name: "sevkiyat_SatisFat_KlavyeEngelle")
  bool? sevkiyatSatisFatKlavyeEngelle;
  @JsonKey(name: "sevkiyat_SatisFat_Miktar1Gelsin")
  bool? sevkiyatSatisFatMiktar1Gelsin;
  @JsonKey(name: "sevkiyat_SatisFat_BakiyesizStokSecilmesin")
  bool? sevkiyatSatisFatBakiyesizStokSecilmesin;
  @JsonKey(name: "sevkiyat_SatisFat_Raporlar")
  bool? sevkiyatSatisFatRaporlar;
  @JsonKey(name: "sevkiyat_SatisFat_KalemRaporu")
  bool? sevkiyatSatisFatKalemRaporu;
  @JsonKey(name: "sevkiyat_SatisFat_KarlilikRaporu")
  bool? sevkiyatSatisFatKarlilikRaporu;
  @JsonKey(name: "sevkiyat_SatisFat_MaxIskUygulamasi")
  bool? sevkiyatSatisFatMaxIskUygulamasi;
  @JsonKey(name: "sevkiyat_SatisFat_MaxSatIsk1")
  double? sevkiyatSatisFatMaxSatIsk1;
  @JsonKey(name: "sevkiyat_SatisFat_MaxSatIsk2")
  double? sevkiyatSatisFatMaxSatIsk2;
  @JsonKey(name: "sevkiyat_SatisFat_MaxSatIsk3")
  double? sevkiyatSatisFatMaxSatIsk3;
  @JsonKey(name: "sevkiyat_SatisFat_MaxSatIsk4")
  double? sevkiyatSatisFatMaxSatIsk4;
  @JsonKey(name: "sevkiyat_SatisFat_MaxSatIsk5")
  double? sevkiyatSatisFatMaxSatIsk5;
  @JsonKey(name: "sevkiyat_SatisFat_MaxSatIsk6")
  double? sevkiyatSatisFatMaxSatIsk6;
  @JsonKey(name: "sevkiyat_SatisFat_MaxGenIsk1")
  double? sevkiyatSatisFatMaxGenIsk1;
  @JsonKey(name: "sevkiyat_SatisFat_MaxGenIsk2")
  double? sevkiyatSatisFatMaxGenIsk2;
  @JsonKey(name: "sevkiyat_SatisFat_MaxGenIsk3")
  double? sevkiyatSatisFatMaxGenIsk3;
  @JsonKey(name: "sevkiyat_SatisFat_DipFiyatUygulamasi")
  bool? sevkiyatSatisFatDipFiyatUygulamasi;
  @JsonKey(name: "sevkiyat_SatisFat_DipFiyatSaha")
  String? sevkiyatSatisFatDipFiyatSaha;
  @JsonKey(name: "sevkiyat_SatisFat_DipFiyatEylem")
  String? sevkiyatSatisFatDipFiyatEylem;
  @JsonKey(name: "sevkiyat_SatisFat_DipFiyatKDVDurumu")
  String? sevkiyatSatisFatDipFiyatKDVDurumu;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesiSiparissiz")
  bool? sevkiyatSatisIrsaliyesiSiparissiz;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesiSiparissizFiyatGor")
  bool? sevkiyatSatisIrsaliyesiSiparissizFiyatGor;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesiIade")
  bool? sevkiyatSatisIrsaliyesiIade;
  @JsonKey(name: "sevkiyat_SiptenMalTop")
  bool? sevkiyatSiptenMalTop;
  @JsonKey(name: "sevkiyat_SiptenMalTop_MiktarBarkoddanGelsin")
  bool? sevkiyatSiptenMalTopMiktarBarkoddanGelsin;
  @JsonKey(name: "sevkiyat_SiptenMalTop_RehberdenStokSecilmesin")
  bool? sevkiyatSiptenMalTopRehberdenStokSecilmesin;
  @JsonKey(name: "sevkiyat_SiptenMalTop_KlavyedenBarkodGirilmesin")
  bool? sevkiyatSiptenMalTopKlavyedenBarkodGirilmesin;
  @JsonKey(name: "sevkiyat_SiptenMalTop_SevkOnayliSiparislerGelsin")
  bool? sevkiyatSiptenMalTopSevkOnayliSiparislerGelsin;
  @JsonKey(name: "sevkiyat_SiptenMalTop_KacGunlukKayitlarListelensin")
  int? sevkiyatSiptenMalTopKacGunlukKayitlarListelensin;
  @JsonKey(name: "sevkemri_MalToplama")
  bool? sevkemriMalToplama;
  @JsonKey(name: "sevkemri_MalToplamaAtanabilir")
  bool? sevkemriMalToplamaAtanabilir;
  @JsonKey(name: "sevkemri_MalToplamaAtayabilir")
  bool? sevkemriMalToplamaAtayabilir;
  @JsonKey(name: "sevkemri_UrunDegistir")
  bool? sevkemriUrunDegistir;
  @JsonKey(name: "sevkemri_MiktarDegistir")
  bool? sevkemriMiktarDegistir;
  @JsonKey(name: "sevkemri_MuadilUrun")
  bool? sevkemriMuadilUrun;
  @JsonKey(name: "sevkemri_malToplama_BarkodsuzUrunListedenSecilsin")
  bool? sevkemriMalToplamaBarkodsuzUrunListedenSecilsin;
  @JsonKey(name: "sevkemri_MalToplama_OtoStokEtiketiYazdir")
  bool? sevkemriMalToplamaOtoStokEtiketiYazdir;
  @JsonKey(name: "sevkemri_MalToplama_OtoStokEtiketiYazdirSor")
  bool? sevkemriMalToplamaOtoStokEtiketiYazdirSor;
  @JsonKey(name: "sevkemri_MalToplama_KlavyedenGirisiEngelle")
  bool? sevkemriMalToplamaKlavyedenGirisiEngelle;
  @JsonKey(name: "sevkemri_MalToplama_Barkod2Sor")
  bool? sevkemriMalToplamaBarkod2Sor;
  @JsonKey(name: "sevkemri_MalToplama_Barkod2_YildizliGorunsun")
  bool? sevkemriMalToplamaBarkod2YildizliGorunsun;
  @JsonKey(name: "sevkemri_MalToplama_Barkod2KalemEkranindaSor")
  bool? sevkemriMalToplamaBarkod2KalemEkranindaSor;
  @JsonKey(name: "sevkemri_MalToplama_TumuToplanmadanTamamlanmasin")
  bool? sevkemriMalToplamaTumuToplanmadanTamamlanmasin;
  @JsonKey(name: "sevkemri_MalToplama_HangiHucredeGoster")
  bool? sevkemriMalToplamaHangiHucredeGoster;
  @JsonKey(name: "sevkemri_MalToplama_KalemDetayIslemOnaySormasin")
  bool? sevkemriMalToplamaKalemDetayIslemOnaySormasin;
  @JsonKey(name: "sevkemri_MalToplama_GosterilecekEkBilgiler")
  List<String>? sevkemriMalToplamaGosterilecekEkBilgiler;
  @JsonKey(name: "sevkemri_MalToplama_DegistirilemeyecekAlanlar")
  List<dynamic>? sevkemriMalToplamaDegistirilemeyecekAlanlar;
  @JsonKey(name: "sevkemri_MalToplama_GizlenecekAlanlar")
  List<dynamic>? sevkemriMalToplamaGizlenecekAlanlar;
  @JsonKey(name: "sevkemri_MalToplama_MiktarBarkoddan")
  bool? sevkemriMalToplamaMiktarBarkoddan;
  @JsonKey(name: "sevkemri_MalToplama_KalemDetayiSorulmasin")
  bool? sevkemriMalToplamaKalemDetayiSorulmasin;
  @JsonKey(name: "sevkemri_MalToplama_KalemDetayaUlasamasin")
  bool? sevkemriMalToplamaKalemDetayaUlasamasin;
  @JsonKey(name: "sevkemri_MalToplama_FazlaTeslimat")
  String? sevkemriMalToplamaFazlaTeslimat;
  @JsonKey(name: "sevkemri_MalToplama_VarsayilanOlcuBirimi")
  int? sevkemriMalToplamaVarsayilanOlcuBirimi;
  @JsonKey(name: "sevkemri_MalToplama_SiralamaTipi")
  String? sevkemriMalToplamaSiralamaTipi;
  @JsonKey(name: "sevkemri_MalKontrol")
  bool? sevkemriMalKontrol;
  @JsonKey(name: "sevkemri_MalKontrol_KlavyeEngelle")
  bool? sevkemriMalKontrolKlavyeEngelle;
  @JsonKey(name: "sevkemri_MalKontrolTipi")
  SevkemriMalKontrolTipi? sevkemriMalKontrolTipi;
  @JsonKey(name: "sevkemri_MalKontrolKullanicilar")
  List<int>? sevkemriMalKontrolKullanicilar;
  @JsonKey(name: "sevkemri_Paketleme")
  bool? sevkemriPaketleme;
  @JsonKey(name: "sevkemri_Paketleme_KlavyeEngelle")
  bool? sevkemriPaketlemeKlavyeEngelle;
  @JsonKey(name: "sevkemri_Paketleme_BarkodOkutmayaZorla")
  bool? sevkemriPaketlemeBarkodOkutmayaZorla;
  @JsonKey(name: "sevkemri_Paketleme_BarkodsuzUrunListedenSecilsin")
  bool? sevkemriPaketlemeBarkodsuzUrunListedenSecilsin;
  @JsonKey(name: "sevkemri_AracYukleme")
  bool? sevkemriAracYukleme;
  @JsonKey(name: "sevkemri_AracYukleme_KlavyeEngelle")
  bool? sevkemriAracYuklemeKlavyeEngelle;
  @JsonKey(name: "sevkemri_AracBosaltma")
  bool? sevkemriAracBosaltma;
  @JsonKey(name: "sevkemri_AracBosaltma_KlavyeEngelle")
  bool? sevkemriAracBosaltmaKlavyeEngelle;
  @JsonKey(name: "sevkemri_DepodanTeslimat")
  bool? sevkemriDepodanTeslimat;
  @JsonKey(name: "sevkemri_DepodanTeslimat_KlavyeEngelle")
  bool? sevkemriDepodanTeslimatKlavyeEngelle;
  @JsonKey(name: "sayim_sayim")
  bool? sayimSayim;
  @JsonKey(name: "sayim_Kontrol_Miktari")
  double? sayimKontrolMiktari;
  @JsonKey(name: "sayim_MiktarBarkoddanGelsin")
  bool? sayimMiktarBarkoddanGelsin;
  @JsonKey(name: "sayim_AyniStokDurumu")
  String? sayimAyniStokDurumu;
  @JsonKey(name: "sayim_Miktar1Gelsin")
  bool? sayimMiktar1Gelsin;
  @JsonKey(name: "sayim_HemenKaydet")
  bool? sayimHemenKaydet;
  @JsonKey(name: "sayim_CarpanAktif")
  bool? sayimCarpanAktif;
  @JsonKey(name: "sayim_SeriMikGirilenMikKabulEdilsin")
  bool? sayimSeriMikGirilenMikKabulEdilsin;
  @JsonKey(name: "sayim_DigerKulSayimHarGorsun")
  String? sayimDigerKulSayimHarGorsun;
  @JsonKey(name: "sayim_DigerKulSayimFisGorsun")
  String? sayimDigerKulSayimFisGorsun;
  @JsonKey(name: "sayim_Serbest")
  bool? sayimSerbest;
  @JsonKey(name: "sayim_Serbest_Sil")
  bool? sayimSerbestSil;
  @JsonKey(name: "sayim_DepoFarkRaporu")
  bool? sayimDepoFarkRaporu;
  @JsonKey(name: "sayim_BelgeBaglantisiniKopar")
  bool? sayimBelgeBaglantisiniKopar;
  @JsonKey(name: "sayim_BelgeOlusturabilir")
  List<String>? sayimBelgeOlusturabilir;
  @JsonKey(name: "sayim_EkAlanlar")
  List<dynamic>? sayimEkAlanlar;
  @JsonKey(name: "sayim_DegismeyecekAlanlar")
  List<dynamic>? sayimDegismeyecekAlanlar;
  @JsonKey(name: "sayim_GizlenecekAlanlar")
  List<dynamic>? sayimGizlenecekAlanlar;
  @JsonKey(name: "sayim_VarsayilanOlcuBirimi")
  int? sayimVarsayilanOlcuBirimi;
  @JsonKey(name: "sayim_Raporu")
  bool? sayimRaporu;
  @JsonKey(name: "paket_Olustur")
  bool? paketOlustur;
  @JsonKey(name: "paket_CokluOlustur")
  bool? paketCokluOlustur;
  @JsonKey(name: "paket_Kontrol")
  bool? paketKontrol;
  @JsonKey(name: "paket_MalzemeCikisi")
  bool? paketMalzemeCikisi;
  @JsonKey(name: "paket_ReceteyiFiltrele")
  bool? paketReceteyiFiltrele;
  @JsonKey(name: "islemler_HucreEtiket")
  bool? islemlerHucreEtiket;
  @JsonKey(name: "islemler_StokEtiket")
  bool? islemlerStokEtiket;
  @JsonKey(name: "islemler_BarkodTanimlama")
  bool? islemlerBarkodTanimlama;
  @JsonKey(name: "siparis_MusteriSiparisi")
  bool? siparisMusteriSiparisi;
  @JsonKey(name: "siparis_MusteriSiparisi_Kaydet")
  bool? siparisMusteriSiparisiKaydet;
  @JsonKey(name: "siparis_MusteriSiparisi_Duzelt")
  bool? siparisMusteriSiparisiDuzelt;
  @JsonKey(name: "siparis_MusteriSiparisi_Sil")
  bool? siparisMusteriSiparisiSil;
  @JsonKey(name: "siparis_MusteriSiparisi_KapalilarListelenmesin")
  bool? siparisMusteriSiparisiKapalilarListelenmesin;
  @JsonKey(name: "siparis_MusteriSiparisi_FiyatDegistirilmesin")
  bool? siparisMusteriSiparisiFiyatDegistirilmesin;
  @JsonKey(name: "siparis_MusteriSiparisi_FiyatSirasi")
  int? siparisMusteriSiparisiFiyatSirasi;
  @JsonKey(name: "siparis_MusSip_Birim1denKaydet")
  bool? siparisMusSipBirim1DenKaydet;
  @JsonKey(name: "siparis_MusteriSiparisi_KapatmaIslemi")
  bool? siparisMusteriSiparisiKapatmaIslemi;
  @JsonKey(name: "siparis_MusSip_OnayIslemleri")
  bool? siparisMusSipOnayIslemleri;
  @JsonKey(name: "siparis_MusSip_StokIhtiyacRaporu")
  bool? siparisMusSipStokIhtiyacRaporu;
  @JsonKey(name: "siparis_MusteriSiparisi_SonFiyatGoster")
  bool? siparisMusteriSiparisiSonFiyatGoster;
  @JsonKey(name: "siparis_MusSip_DigerSekmesiGoster")
  bool? siparisMusSipDigerSekmesiGoster;
  @JsonKey(name: "siparis_MusSip_EkAlan2Tablodan")
  bool? siparisMusSipEkAlan2Tablodan;
  @JsonKey(name: "siparis_MusSip_EkAlan2Hatirla")
  bool? siparisMusSipEkAlan2Hatirla;
  @JsonKey(name: "siparis_MusSip_Miktar1Gelsin")
  bool? siparisMusSipMiktar1Gelsin;
  @JsonKey(name: "siparis_MusSip_BosGecilmeyecekAlanlar")
  List<String>? siparisMusSipBosGecilmeyecekAlanlar;
  @JsonKey(name: "siparis_MusSip_OtoPdfGor")
  bool? siparisMusSipOtoPdfGor;
  @JsonKey(name: "siparis_MusSip_CariKoduDegistir")
  bool? siparisMusSipCariKoduDegistir;
  @JsonKey(name: "siparis_MusteriSiparisi_AciklamaAlanlari")
  List<int>? siparisMusteriSiparisiAciklamaAlanlari;
  @JsonKey(name: "siparis_MusteriSiparisi_GizlenecekAlanlar")
  List<dynamic>? siparisMusteriSiparisiGizlenecekAlanlar;
  @JsonKey(name: "siparis_MusteriSiparisi_DegismeyecekAlanlar")
  List<dynamic>? siparisMusteriSiparisiDegismeyecekAlanlar;
  @JsonKey(name: "siparis_MusSip_EkstraAlanlar")
  List<String>? siparisMusSipEkstraAlanlar;
  @JsonKey(name: "siparis_MusteriSiparisi_SatirAciklamaAlanlari")
  List<int>? siparisMusteriSiparisiSatirAciklamaAlanlari;
  @JsonKey(name: "siparis_MusSip_OlcuBirimi")
  int? siparisMusSipOlcuBirimi;
  @JsonKey(name: "siparis_MusSip_BakiyesizStokSecilmesin")
  bool? siparisMusSipBakiyesizStokSecilmesin;
  @JsonKey(name: "siparis_MusSip_HizliUrunGirisi_Miktar2Kullanilsin")
  String? siparisMusSipHizliUrunGirisiMiktar2Kullanilsin;
  @JsonKey(name: "siparis_MusteriSiparisi_DipFiyatUygulamasi")
  bool? siparisMusteriSiparisiDipFiyatUygulamasi;
  @JsonKey(name: "siparis_MusteriSiparisi_DipFiyatSaha")
  String? siparisMusteriSiparisiDipFiyatSaha;
  @JsonKey(name: "siparis_MusteriSiparisi_DipFiyatEylem")
  String? siparisMusteriSiparisiDipFiyatEylem;
  @JsonKey(name: "siparis_MusSip_MaxIskUygulamasi")
  bool? siparisMusSipMaxIskUygulamasi;
  @JsonKey(name: "siparis_MusSip_MaxSatIsk1")
  double? siparisMusSipMaxSatIsk1;
  @JsonKey(name: "siparis_MusSip_MaxSatIsk2")
  double? siparisMusSipMaxSatIsk2;
  @JsonKey(name: "siparis_MusSip_MaxSatIsk3")
  double? siparisMusSipMaxSatIsk3;
  @JsonKey(name: "siparis_MusSip_MaxSatIsk4")
  double? siparisMusSipMaxSatIsk4;
  @JsonKey(name: "siparis_MusSip_MaxSatIsk5")
  double? siparisMusSipMaxSatIsk5;
  @JsonKey(name: "siparis_MusSip_MaxSatIsk6")
  double? siparisMusSipMaxSatIsk6;
  @JsonKey(name: "siparis_MusSip_MaxGenIsk1")
  double? siparisMusSipMaxGenIsk1;
  @JsonKey(name: "siparis_MusSip_MaxGenIsk2")
  double? siparisMusSipMaxGenIsk2;
  @JsonKey(name: "siparis_MusSip_MaxGenIsk3")
  double? siparisMusSipMaxGenIsk3;
  @JsonKey(name: "siparis_MusteriSiparisi_Raporlar")
  bool? siparisMusteriSiparisiRaporlar;
  @JsonKey(name: "siparis_MusteriSiparisi_DurumRaporu")
  bool? siparisMusteriSiparisiDurumRaporu;
  @JsonKey(name: "siparis_MusteriSiparisi_DurumRaporuFiyatGor")
  bool? siparisMusteriSiparisiDurumRaporuFiyatGor;
  @JsonKey(name: "siparis_MusSip_KarlilikRaporu")
  bool? siparisMusSipKarlilikRaporu;
  @JsonKey(name: "siparis_MusSip_TeslimRaporu")
  bool? siparisMusSipTeslimRaporu;
  @JsonKey(name: "siparis_SaticiSiparisi")
  bool? siparisSaticiSiparisi;
  @JsonKey(name: "siparis_SaticiSiparisi_Kaydet")
  bool? siparisSaticiSiparisiKaydet;
  @JsonKey(name: "siparis_SaticiSiparisi_Duzelt")
  bool? siparisSaticiSiparisiDuzelt;
  @JsonKey(name: "siparis_SaticiSiparisi_Sil")
  bool? siparisSaticiSiparisiSil;
  @JsonKey(name: "siparis_SaticiSiparisi_KapalilarListelenmesin")
  bool? siparisSaticiSiparisiKapalilarListelenmesin;
  @JsonKey(name: "siparis_SaticiSiparisi_FiyatDegistirilmesin")
  bool? siparisSaticiSiparisiFiyatDegistirilmesin;
  @JsonKey(name: "siparis_SaticiSiparisi_FiyatSirasi")
  int? siparisSaticiSiparisiFiyatSirasi;
  @JsonKey(name: "siparis_SaticiSip_Birim1denKaydet")
  bool? siparisSaticiSipBirim1DenKaydet;
  @JsonKey(name: "siparis_SaticiSiparisi_KapatmaIslemi")
  bool? siparisSaticiSiparisiKapatmaIslemi;
  @JsonKey(name: "siparis_SaticiSip_OnayIslemleri")
  bool? siparisSaticiSipOnayIslemleri;
  @JsonKey(name: "siparis_SaticiSip_DigerSekmesiGoster")
  bool? siparisSaticiSipDigerSekmesiGoster;
  @JsonKey(name: "siparis_SaticiSip_OlcuBirimi")
  int? siparisSaticiSipOlcuBirimi;
  @JsonKey(name: "siparis_SaticiSip_CariKoduDegistir")
  bool? siparisSaticiSipCariKoduDegistir;
  @JsonKey(name: "siparis_SaticiSiparisi_Raporlar")
  bool? siparisSaticiSiparisiRaporlar;
  @JsonKey(name: "siparis_SaticiSiparisi_DurumRaporu")
  bool? siparisSaticiSiparisiDurumRaporu;
  @JsonKey(name: "siparis_SaticiSiparisi_DurumRaporuFiyatGor")
  bool? siparisSaticiSiparisiDurumRaporuFiyatGor;
  @JsonKey(name: "siparis_SaticiSip_TeslimRaporu")
  bool? siparisSaticiSipTeslimRaporu;
  @JsonKey(name: "stok_StokListesi")
  bool? stokStokListesi;
  @JsonKey(name: "stok_StokListesi_ExtraAlanlar")
  List<String>? stokStokListesiExtraAlanlar;
  @JsonKey(name: "stok_StokKarti")
  bool? stokStokKarti;
  @JsonKey(name: "stok_StokKarti_Kaydet")
  bool? stokStokKartiKaydet;
  @JsonKey(name: "stok_StokKarti_Duzelt")
  bool? stokStokKartiDuzelt;
  @JsonKey(name: "stok_StokKarti_Sil")
  bool? stokStokKartiSil;
  @JsonKey(name: "stok_StokKarti_AlisFiyatiGizle")
  bool? stokStokKartiAlisFiyatiGizle;
  @JsonKey(name: "stok_StokKarti_SatisFiyatiGizle")
  bool? stokStokKartiSatisFiyatiGizle;
  @JsonKey(name: "stok_StokHareketleri")
  bool? stokStokHareketleri;
  @JsonKey(name: "stok_StokHar_Kaydet")
  bool? stokStokHarKaydet;
  @JsonKey(name: "stok_StokHar_Duzelt")
  bool? stokStokHarDuzelt;
  @JsonKey(name: "stok_StokHar_Sil")
  bool? stokStokHarSil;
  @JsonKey(name: "stok_StokHar_PlasiyerKendiniGorsun")
  bool? stokStokHarPlasiyerKendiniGorsun;
  @JsonKey(name: "stok_ResimGoster")
  bool? stokResimGoster;
  @JsonKey(name: "stok_ResimGoster_Ekle")
  bool? stokResimGosterEkle;
  @JsonKey(name: "stok_ResimGoster_Sil")
  bool? stokResimGosterSil;
  @JsonKey(name: "stok_FiyatOzeti")
  bool? stokFiyatOzeti;
  @JsonKey(name: "stok_HareketDetayiniGizle")
  bool? stokHareketDetayiniGizle;
  @JsonKey(name: "stok_GirisHareketleriniGizle")
  bool? stokGirisHareketleriniGizle;
  @JsonKey(name: "stok_CikisHareketleriniGizle")
  bool? stokCikisHareketleriniGizle;
  @JsonKey(name: "stok_BakiyeGosterimTipi")
  String? stokBakiyeGosterimTipi;
  @JsonKey(name: "stok_BarkodKontrol")
  bool? stokBarkodKontrol;
  @JsonKey(name: "stok_DepoBakiyeDurumu")
  String? stokDepoBakiyeDurumu;
  @JsonKey(name: "stok_BarkodTanimlama")
  bool? stokBarkodTanimlama;
  @JsonKey(name: "stok_BarkodTanimlama_GorunecekAlanlar")
  List<String>? stokBarkodTanimlamaGorunecekAlanlar;
  @JsonKey(name: "stok_BarkodKayitlari")
  bool? stokBarkodKayitlari;
  @JsonKey(name: "stok_BarkodKayitlari_Ekle")
  bool? stokBarkodKayitlariEkle;
  @JsonKey(name: "stok_BarkodKayitlari_Duzelt")
  bool? stokBarkodKayitlariDuzelt;
  @JsonKey(name: "stok_BarkodKayitlari_Sil")
  bool? stokBarkodKayitlariSil;
  @JsonKey(name: "stok_KanbanBarkodEsle")
  bool? stokKanbanBarkodEsle;
  @JsonKey(name: "stok_KanbanBarkodEsle_Sil")
  bool? stokKanbanBarkodEsleSil;
  @JsonKey(name: "stok_KanbanBarkodEsleFarkliStokOkutulmasin")
  bool? stokKanbanBarkodEsleFarkliStokOkutulmasin;
  @JsonKey(name: "stok_FiyatGorEkrani")
  bool? stokFiyatGorEkrani;
  @JsonKey(name: "stok_FiyatGorEkraniGorunecekAlanlar")
  List<String>? stokFiyatGorEkraniGorunecekAlanlar;
  @JsonKey(name: "stok_FiyatGecmisi")
  bool? stokFiyatGecmisi;
  @JsonKey(name: "stok_FiyatGecmisiSil")
  bool? stokFiyatGecmisiSil;
  @JsonKey(name: "stok_FiyatGecmisiFiyatTipleri")
  List<String>? stokFiyatGecmisiFiyatTipleri;
  @JsonKey(name: "stok_SeriHar")
  bool? stokSeriHar;
  @JsonKey(name: "stok_SeriHar_Ekle")
  bool? stokSeriHarEkle;
  @JsonKey(name: "stok_SeriHar_Duzelt")
  bool? stokSeriHarDuzelt;
  @JsonKey(name: "stok_SeriHar_Sil")
  bool? stokSeriHarSil;
  @JsonKey(name: "stok_SeriParcala")
  bool? stokSeriParcala;
  @JsonKey(name: "stok_SeriParcala_Ekle")
  bool? stokSeriParcalaEkle;
  @JsonKey(name: "stok_SeriParcala_Duzelt")
  bool? stokSeriParcalaDuzelt;
  @JsonKey(name: "stok_SeriParcala_Sil")
  bool? stokSeriParcalaSil;
  @JsonKey(name: "stok_SeriBirlestir")
  bool? stokSeriBirlestir;
  @JsonKey(name: "stok_SeriBirlestir_Ekle")
  bool? stokSeriBirlestirEkle;
  @JsonKey(name: "stok_SeriBirlestir_Duzelt")
  bool? stokSeriBirlestirDuzelt;
  @JsonKey(name: "stok_SeriBirlestir_Sil")
  bool? stokSeriBirlestirSil;
  @JsonKey(name: "stok_Paketleme")
  bool? stokPaketleme;
  @JsonKey(name: "stok_Paketleme_Ekle")
  bool? stokPaketlemeEkle;
  @JsonKey(name: "stok_Paketleme_Sil")
  bool? stokPaketlemeSil;
  @JsonKey(name: "stok_Paketleme_OnaySormasin")
  String? stokPaketlemeOnaySormasin;
  @JsonKey(name: "stok_Paketleme_DigerKulKayitGorebilir")
  String? stokPaketlemeDigerKulKayitGorebilir;
  @JsonKey(name: "stok_Paketleme_SorulacakBelgeTipleri")
  List<String>? stokPaketlemeSorulacakBelgeTipleri;
  @JsonKey(name: "stok_Raporlar")
  bool? stokRaporlar;
  @JsonKey(name: "stok_Rap_AmbarMaliyet")
  bool? stokRapAmbarMaliyet;
  @JsonKey(name: "stok_Rap_LokalDepoBakiye")
  bool? stokRapLokalDepoBakiye;
  @JsonKey(name: "stok_Rap_UrunGrubunaGoreSatis")
  bool? stokRapUrunGrubunaGoreSatis;
  @JsonKey(name: "cari_CariListesi")
  bool? cariCariListesi;
  @JsonKey(name: "cari_CariListesi_RiskGorebilir")
  bool? cariCariListesiRiskGorebilir;
  @JsonKey(name: "cari_RiskGirisi")
  bool? cariRiskGirisi;
  @JsonKey(name: "cari_CariKarti")
  bool? cariCariKarti;
  @JsonKey(name: "cari_CariKarti_Kaydet")
  bool? cariCariKartiKaydet;
  @JsonKey(name: "cari_CariKarti_Duzelt")
  bool? cariCariKartiDuzelt;
  @JsonKey(name: "cari_CariKarti_Sil")
  bool? cariCariKartiSil;
  @JsonKey(name: "cari_CariKarti_EIslemler")
  bool? cariCariKartiEIslemler;
  @JsonKey(name: "cari_CariKarti_DegismeyecekAlanlar")
  List<String>? cariCariKartiDegismeyecekAlanlar;
  @JsonKey(name: "cari_CariKarti_GizlenecekAlanlar")
  List<dynamic>? cariCariKartiGizlenecekAlanlar;
  @JsonKey(name: "cari_CariHareketleri")
  bool? cariCariHareketleri;
  @JsonKey(name: "cari_CariHar_Kaydet")
  bool? cariCariHarKaydet;
  @JsonKey(name: "cari_CariHar_Duzelt")
  bool? cariCariHarDuzelt;
  @JsonKey(name: "cari_CariHar_Sil")
  bool? cariCariHarSil;
  @JsonKey(name: "cari_CariHareketleri_HarDetayGorsun")
  bool? cariCariHareketleriHarDetayGorsun;
  @JsonKey(name: "stok_CariHar_PlasiyerKendiniGorsun")
  bool? stokCariHarPlasiyerKendiniGorsun;
  @JsonKey(name: "cari_Aktivite")
  bool? cariAktivite;
  @JsonKey(name: "cari_Aktivite_Ekle")
  bool? cariAktiviteEkle;
  @JsonKey(name: "cari_Aktivite_Duzelt")
  bool? cariAktiviteDuzelt;
  @JsonKey(name: "cari_Aktivite_Sil")
  bool? cariAktiviteSil;
  @JsonKey(name: "cari_Aktivite_Atayabilir")
  bool? cariAktiviteAtayabilir;
  @JsonKey(name: "cari_Aktivite_BitirmeyiGeriAl")
  bool? cariAktiviteBitirmeyiGeriAl;
  @JsonKey(name: "cari_OzelHesapKapatma")
  bool? cariOzelHesapKapatma;
  @JsonKey(name: "cari_OzelHesapKapatma_Sil")
  bool? cariOzelHesapKapatmaSil;
  @JsonKey(name: "cari_VadeKontrolu")
  bool? cariVadeKontrolu;
  @JsonKey(name: "cari_VadeKontrolu_Gun")
  int? cariVadeKontroluGun;
  @JsonKey(name: "cari_VadeKontrolu_BelgeTipleri")
  List<String>? cariVadeKontroluBelgeTipleri;
  @JsonKey(name: "cari_Filtre")
  String? cariFiltre;
  @JsonKey(name: "cari_FiltreSQL")
  String? cariFiltreSql;
  @JsonKey(name: "cari_Virman")
  bool? cariVirman;
  @JsonKey(name: "cari_Virman_Kaydet")
  bool? cariVirmanKaydet;
  @JsonKey(name: "cari_Harita")
  bool? cariHarita;
  @JsonKey(name: "cari_TeslimCari_RehberSadeceSecsin")
  String? cariTeslimCariRehberSadeceSecsin;
  @JsonKey(name: "cari_TeslimCari_SatisBaglanmisCarilerSecilsin")
  String? cariTeslimCariSatisBaglanmisCarilerSecilsin;
  @JsonKey(name: "cari_Raporlar")
  bool? cariRaporlar;
  @JsonKey(name: "cari_Rap_Ekstre")
  bool? cariRapEkstre;
  @JsonKey(name: "cari_Rap_StokEkstre")
  bool? cariRapStokEkstre;
  @JsonKey(name: "cari_Rap_Yaslandirma")
  bool? cariRapYaslandirma;
  @JsonKey(name: "cari_Rap_HarDetayliYaslandir")
  bool? cariRapHarDetayliYaslandir;
  @JsonKey(name: "cari_Rap_Hareket")
  bool? cariRapHareket;
  @JsonKey(name: "cari_Rap_DovizBakiye")
  bool? cariRapDovizBakiye;
  @JsonKey(name: "cari_Rap_StokSatisOzeti")
  bool? cariRapStokSatisOzeti;
  @JsonKey(name: "cari_Rap_DovizliEkstre")
  bool? cariRapDovizliEkstre;
  @JsonKey(name: "tahsilat_Tahsilatlar")
  bool? tahsilatTahsilatlar;
  @JsonKey(name: "tahsilat_NakitTahsilat")
  bool? tahsilatNakitTahsilat;
  @JsonKey(name: "tahsilat_NakitTahsilat_Kaydet")
  bool? tahsilatNakitTahsilatKaydet;
  @JsonKey(name: "tahsilat_KKartiTahsilat")
  bool? tahsilatKKartiTahsilat;
  @JsonKey(name: "tahsilat_KKartiTahsilat_Kaydet")
  bool? tahsilatKKartiTahsilatKaydet;
  @JsonKey(name: "tahsilat_NakitOdeme")
  bool? tahsilatNakitOdeme;
  @JsonKey(name: "tahsilat_NakitOdeme_Kaydet")
  bool? tahsilatNakitOdemeKaydet;
  @JsonKey(name: "tahsilat_SenetTahsilat")
  bool? tahsilatSenetTahsilat;
  @JsonKey(name: "tahsilat_SenetTahsilat_Kaydet")
  bool? tahsilatSenetTahsilatKaydet;
  @JsonKey(name: "tahsilat_CekTahsilat")
  bool? tahsilatCekTahsilat;
  @JsonKey(name: "tahsilat_CekTahsilat_Kaydet")
  bool? tahsilatCekTahsilatKaydet;
  @JsonKey(name: "tahsilat_MuhtelifTahsilat")
  bool? tahsilatMuhtelifTahsilat;
  @JsonKey(name: "tahsilat_MuhtelifOdeme")
  bool? tahsilatMuhtelifOdeme;
  @JsonKey(name: "tahsilat_MuhtelifTahsilatFiltre")
  String? tahsilatMuhtelifTahsilatFiltre;
  @JsonKey(name: "tahsilat_MuhtelifTahsilatFiltreSQL")
  String? tahsilatMuhtelifTahsilatFiltreSQL;
  @JsonKey(name: "tahsilat_MuhtelifOdemeFiltre")
  String? tahsilatMuhtelifOdemeFiltre;
  @JsonKey(name: "tahsilat_MuhtelifOdemeFiltreSQL")
  String? tahsilatMuhtelifOdemeFiltreSQL;
  @JsonKey(name: "yonetici_Banka_Banka_Litesi")
  bool? yoneticiBankaBankaLitesi;
  @JsonKey(name: "yonetici_Banka_Islemleri")
  bool? yoneticiBankaIslemleri;
  @JsonKey(name: "yonetici_Banka_Islemleri_Sil")
  bool? yoneticiBankaIslemleriSil;
  @JsonKey(name: "yonetici_Banka_Islem_HesapEFT")
  bool? yoneticiBankaIslemHesapEft;
  @JsonKey(name: "yonetici_Banka_Islem_HesapVirman")
  bool? yoneticiBankaIslemHesapVirman;
  @JsonKey(name: "yonetici_Banka_Islem_CariEFT")
  bool? yoneticiBankaIslemCariEft;
  @JsonKey(name: "finans_Banka_Kasa_Transferi")
  bool? finansBankaKasaTransferi;
  @JsonKey(name: "finans_Kasa_Listesi")
  bool? finansKasaListesi;
  @JsonKey(name: "finans_Kasa_Islemleri")
  bool? finansKasaIslemleri;
  @JsonKey(name: "finans_Kasa_Islemleri_Sil")
  bool? finansKasaIslemleriSil;
  @JsonKey(name: "finans_KasalarArasiTransfer")
  bool? finansKasalarArasiTransfer;
  @JsonKey(name: "finans_Kasa_NakitTahsilat")
  bool? finansKasaNakitTahsilat;
  @JsonKey(name: "finans_Kasa_NakitOdeme")
  bool? finansKasaNakitOdeme;
  @JsonKey(name: "finans_Kasa_MuhtelifTahsilat")
  bool? finansKasaMuhtelifTahsilat;
  @JsonKey(name: "finans_Kasa_MuhtelifOdeme")
  bool? finansKasaMuhtelifOdeme;
  @JsonKey(name: "finans_Kasa_SenetTahsilati")
  bool? finansKasaSenetTahsilati;
  @JsonKey(name: "finans_Kasa_SenetOdemesi")
  bool? finansKasaSenetOdemesi;
  @JsonKey(name: "finans_Kasa_CekTahsilati")
  bool? finansKasaCekTahsilati;
  @JsonKey(name: "finans_Kasa_CekOdemesi")
  bool? finansKasaCekOdemesi;
  @JsonKey(name: "dekont_Listesi")
  bool? dekontListesi;
  @JsonKey(name: "dekont_Kaydet")
  bool? dekontKaydet;
  @JsonKey(name: "dekont_Duzelt")
  bool? dekontDuzelt;
  @JsonKey(name: "dekont_Sil")
  bool? dekontSil;
  @JsonKey(name: "finans_Cek_GizlenecekAlanlar")
  List<dynamic>? finansCekGizlenecekAlanlar;
  @JsonKey(name: "finans_Cek_Musteri")
  bool? finansCekMusteri;
  @JsonKey(name: "finans_MCEK_Ekle")
  bool? finansMcekEkle;
  @JsonKey(name: "finans_MCEK_Sil")
  bool? finansMcekSil;
  @JsonKey(name: "finans_MCEK_BelgeDetayi")
  bool? finansMcekBelgeDetayi;
  @JsonKey(name: "finans_MCEK_Hareketler")
  bool? finansMcekHareketler;
  @JsonKey(name: "finans_MCEK_Evraklar")
  bool? finansMcekEvraklar;
  @JsonKey(name: "finans_MCEK_CariyeCiro")
  bool? finansMcekCariyeCiro;
  @JsonKey(name: "finans_MCEK_TahsileCiro")
  bool? finansMcekTahsileCiro;
  @JsonKey(name: "finans_MCEK_TahsilDekontu")
  bool? finansMcekTahsilDekontu;
  @JsonKey(name: "finans_Cek_Borc")
  bool? finansCekBorc;
  @JsonKey(name: "finans_BorcCeki_Ekle")
  bool? finansBorcCekiEkle;
  @JsonKey(name: "finans_BorcCeki_Sil")
  bool? finansBorcCekiSil;
  @JsonKey(name: "finans_BCEK_Ekle")
  bool? finansBcekEkle;
  @JsonKey(name: "finans_BCEK_Sil")
  bool? finansBcekSil;
  @JsonKey(name: "finans_BCEK_BelgeDetayi")
  bool? finansBcekBelgeDetayi;
  @JsonKey(name: "finans_BCEK_Hareketler")
  bool? finansBcekHareketler;
  @JsonKey(name: "finans_BCEK_Evraklar")
  bool? finansBcekEvraklar;
  @JsonKey(name: "finans_BCEK_OdemeDekontu")
  bool? finansBcekOdemeDekontu;
  @JsonKey(name: "finans_Senet_Musteri")
  bool? finansSenetMusteri;
  @JsonKey(name: "finans_MSEN_Ekle")
  bool? finansMsenEkle;
  @JsonKey(name: "finans_MSEN_Sil")
  bool? finansMsenSil;
  @JsonKey(name: "finans_MSEN_BelgeDetayi")
  bool? finansMsenBelgeDetayi;
  @JsonKey(name: "finans_MSEN_Hareketler")
  bool? finansMsenHareketler;
  @JsonKey(name: "finans_MSEN_Evraklar")
  bool? finansMsenEvraklar;
  @JsonKey(name: "finans_MSEN_CariyeCiro")
  bool? finansMsenCariyeCiro;
  @JsonKey(name: "finans_MSEN_TahsileCiro")
  bool? finansMsenTahsileCiro;
  @JsonKey(name: "finans_MSEN_TahsilDekontu")
  bool? finansMsenTahsilDekontu;
  @JsonKey(name: "finans_Senet_Borc")
  bool? finansSenetBorc;
  @JsonKey(name: "finans_BSEN_Ekle")
  bool? finansBsenEkle;
  @JsonKey(name: "finans_BSEN_Sil")
  bool? finansBsenSil;
  @JsonKey(name: "finans_BSEN_BelgeDetayi")
  bool? finansBsenBelgeDetayi;
  @JsonKey(name: "finans_BSEN_Hareketler")
  bool? finansBsenHareketler;
  @JsonKey(name: "finans_BSEN_Evraklar")
  bool? finansBsenEvraklar;
  @JsonKey(name: "finans_BSEN_OdemeDekontu")
  bool? finansBsenOdemeDekontu;
  @JsonKey(name: "finans_KKartiTahsilati")
  bool? finansKKartiTahsilati;
  @JsonKey(name: "finans_MuhtelifTahsilat")
  bool? finansMuhtelifTahsilat;
  @JsonKey(name: "finans_MuhtelifOdeme")
  bool? finansMuhtelifOdeme;
  @JsonKey(name: "finans_TahsilatKayitlari")
  bool? finansTahsilatKayitlari;
  @JsonKey(name: "finans_HizliTahsilatKayitlari")
  bool? finansHizliTahsilatKayitlari;
  @JsonKey(name: "finans_HizliTahsilatKayitlari_Sil")
  bool? finansHizliTahsilatKayitlariSil;
  @JsonKey(name: "finans_OrtalamaVadeTarihiHesaplama")
  bool? finansOrtalamaVadeTarihiHesaplama;
  @JsonKey(name: "finans_OzetRapor")
  bool? finansOzetRapor;
  @JsonKey(name: "finans_Raporlar_FinansalDurum")
  bool? finansRaporlarFinansalDurum;
  @JsonKey(name: "finans_Raporlar_AylikMizan")
  bool? finansRaporlarAylikMizan;
  @JsonKey(name: "temsilci_Profil")
  bool? temsilciProfil;
  @JsonKey(name: "temsilci_Profil_KdvDahil")
  bool? temsilciProfilKdvDahil;
  @JsonKey(name: "temsilci_Profil_SatisPerformansiniGizle")
  bool? temsilciProfilSatisPerformansiniGizle;
  @JsonKey(name: "temsilci_Profil_AylaraGoreSatisiGizle")
  bool? temsilciProfilAylaraGoreSatisiGizle;
  @JsonKey(name: "temsilci_Profil_AylaraGoreTahsilatiGizle")
  bool? temsilciProfilAylaraGoreTahsilatiGizle;
  @JsonKey(name: "yazdirma_BluetoothYaziciKullanabilir")
  bool? yazdirmaBluetoothYaziciKullanabilir;
  @JsonKey(name: "yazdirma_Hucre_Etiketi")
  bool? yazdirmaHucreEtiketi;
  @JsonKey(name: "yazdirma_Hucre_Etiketi_Yazicilari")
  List<String>? yazdirmaHucreEtiketiYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_HucreEtiketi")
  List<dynamic>? yazdirmaDizaynHucreEtiketi;
  @JsonKey(name: "yazdirma_MalToplama_Etiketi")
  bool? yazdirmaMalToplamaEtiketi;
  @JsonKey(name: "yazdirma_Mal_Toplama_Yazicilari")
  List<String>? yazdirmaMalToplamaYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_MalToplama")
  List<dynamic>? yazdirmaDizaynMalToplama;
  @JsonKey(name: "yazdirma_MalKontrol_Etiketi")
  bool? yazdirmaMalKontrolEtiketi;
  @JsonKey(name: "yazdirma_Mal_Kontrol_Yazicilari")
  List<String>? yazdirmaMalKontrolYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_MalKontrol")
  List<dynamic>? yazdirmaDizaynMalKontrol;
  @JsonKey(name: "yazdirma_DAT")
  bool? yazdirmaDat;
  @JsonKey(name: "yazdirma_DAT_Yazicilari")
  List<String>? yazdirmaDatYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_DAT")
  List<int>? yazdirmaDizaynDAT;
  @JsonKey(name: "yazdirma_Paketleme_Etiketi")
  bool? yazdirmaPaketlemeEtiketi;
  @JsonKey(name: "yazdirma_Paketleme_KopyaSayisiGizle")
  bool? yazdirmaPaketlemeKopyaSayisiGizle;
  @JsonKey(name: "yazdirma_Paketleme_Yazicilari")
  List<String>? yazdirmaPaketlemeYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_Paketleme")
  List<int>? yazdirmaDizaynPaketleme;
  @JsonKey(name: "yazdirma_SatisIrs")
  bool? yazdirmaSatisIrs;
  @JsonKey(name: "yazdirma_SatisFat")
  bool? yazdirmaSatisFat;
  @JsonKey(name: "yazdirma_SatisFat_Yazicilari")
  List<String>? yazdirmaSatisFatYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_SatisFat")
  List<int>? yazdirmaDizaynSatisFat;
  @JsonKey(name: "yazdirma_AlisFat")
  bool? yazdirmaAlisFat;
  @JsonKey(name: "yazdirma_Dizayn_AlisFat")
  List<dynamic>? yazdirmaDizaynAlisFat;
  @JsonKey(name: "yazdirma_Mustahsil")
  bool? yazdirmaMustahsil;
  @JsonKey(name: "yazdirma_MusSip")
  bool? yazdirmaMusSip;
  @JsonKey(name: "yazdirma_MusSip_Yazicilari")
  List<dynamic>? yazdirmaMusSipYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_MusSip")
  List<int>? yazdirmaDizaynMusSip;
  @JsonKey(name: "yazdirma_SaticiSip")
  bool? yazdirmaSaticiSip;
  @JsonKey(name: "yazdirma_Dizayn_SaticiSip")
  List<int>? yazdirmaDizaynSaticiSip;
  @JsonKey(name: "yazdirma_ATAL")
  bool? yazdirmaAtal;
  @JsonKey(name: "yazdirma_ATAL_Yazicilari")
  List<String>? yazdirmaAtalYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_ATAL")
  List<int>? yazdirmaDizaynATAL;
  @JsonKey(name: "yazdirma_OdemeMakbuzu")
  bool? yazdirmaOdemeMakbuzu;
  @JsonKey(name: "yazdirma_OdemeMakbuzu_Yazicilari")
  List<dynamic>? yazdirmaOdemeMakbuzuYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_OdemeMakbuzu")
  List<int>? yazdirmaDizaynOdemeMakbuzu;
  @JsonKey(name: "yazdirma_AlisIrs")
  bool? yazdirmaAlisIrs;
  @JsonKey(name: "yazdirma_AlisIrs_Yazicilari")
  List<String>? yazdirmaAlisIrsYazicilari;
  @JsonKey(name: "yazdirma_Dizayn_AlisIrs")
  List<int>? yazdirmaDizaynAlisIrs;
  @JsonKey(name: "yazdirma_IsEmri")
  bool? yazdirmaIsEmri;
  @JsonKey(name: "yazdirma_AmbarCikis")
  bool? yazdirmaAmbarCikis;
  @JsonKey(name: "yazdirma_AmbarGiris")
  bool? yazdirmaAmbarGiris;
  @JsonKey(name: "yazdirma_CariHareket")
  bool? yazdirmaCariHareket;
  @JsonKey(name: "uretim_FiyatGorebilir")
  bool? uretimFiyatGorebilir;
  @JsonKey(name: "uretim_USK_Kaydet")
  bool? uretimUskKaydet;
  @JsonKey(name: "uretim_USK_Duzelt")
  bool? uretimUskDuzelt;
  @JsonKey(name: "uretim_USK_Sil")
  bool? uretimUskSil;
  @JsonKey(name: "uretim_USK_KacGunlukKayitlarListelensin")
  int? uretimUskKacGunlukKayitlarListelensin;
  @JsonKey(name: "uretim_USK_MiktarBarkoddan")
  bool? uretimUskMiktarBarkoddan;
  @JsonKey(name: "uretim_USK_Miktar1Gelsin")
  bool? uretimUskMiktar1Gelsin;
  @JsonKey(name: "sirket_Depo_Uretim_Giris")
  int? sirketDepoUretimGiris;
  @JsonKey(name: "sirket_Depo_Uretim_Cikis")
  int? sirketDepoUretimCikis;
  @JsonKey(name: "uretim_USK_IsEmriOtoGelsin")
  bool? uretimUskIsEmriOtoGelsin;
  @JsonKey(name: "uretim_USK_SoruSorulmasin")
  bool? uretimUskSoruSorulmasin;
  @JsonKey(name: "uretim_USK_StokRehberiAcilmasin")
  bool? uretimUskStokRehberiAcilmasin;
  @JsonKey(name: "uretim_USK_KlavyeEngelle")
  bool? uretimUskKlavyeEngelle;
  @JsonKey(name: "uretim_USK_DepoOnceligi")
  String? uretimUskDepoOnceligi;
  @JsonKey(name: "uretim_USK_FisiErpUretsin")
  bool? uretimUskFisiErpUretsin;
  @JsonKey(name: "uretim_USK_GizlenecekAlanlar")
  List<dynamic>? uretimUskGizlenecekAlanlar;
  @JsonKey(name: "uretim_USK_BosGecilmeyecekAlanlar")
  List<dynamic>? uretimUskBosGecilmeyecekAlanlar;
  @JsonKey(name: "uretim_USK_DegismeyecekAlanlar")
  List<dynamic>? uretimUskDegismeyecekAlanlar;
  @JsonKey(name: "uretim_USK_OlcuBirimi")
  int? uretimUskOlcuBirimi;
  @JsonKey(name: "uretim_USK_OtoYazdir")
  String? uretimUskOtoYazdir;
  @JsonKey(name: "uretim_USK_KalemliYapi")
  bool? uretimUskKalemliYapi;
  @JsonKey(name: "uretim_USK_KalemliYapi_StokMevcutaEklensin")
  bool? uretimUskKalemliYapiStokMevcutaEklensin;
  @JsonKey(name: "uretim_USK_KalemliYapi_OtoEtiketYazdir")
  bool? uretimUskKalemliYapiOtoEtiketYazdir;
  @JsonKey(name: "uretim_USK_KalemliYapi_AyniBarkodOkutulamaz")
  bool? uretimUskKalemliYapiAyniBarkodOkutulamaz;
  @JsonKey(name: "uretim_USK_KalemliYapi_OkutulanEnUsteEklensin")
  bool? uretimUskKalemliYapiOkutulanEnUsteEklensin;
  @JsonKey(name: "uretim_USK_KalemliYapi_KalemDuzeltilemesin")
  bool? uretimUskKalemliYapiKalemDuzeltilemesin;
  @JsonKey(name: "uretim_ReceteIzleme")
  bool? uretimReceteIzleme;
  @JsonKey(name: "uretim_MalToplama")
  bool? uretimMalToplama;
  @JsonKey(name: "uretim_MalToplama_Ekle")
  bool? uretimMalToplamaEkle;
  @JsonKey(name: "uretim_MalToplama_Sil")
  bool? uretimMalToplamaSil;
  @JsonKey(name: "uretim_MalToplama_KlavyeEngelle")
  bool? uretimMalToplamaKlavyeEngelle;
  @JsonKey(name: "uretim_MalToplama_BarkodOkutsun")
  bool? uretimMalToplamaBarkodOkutsun;
  @JsonKey(name: "uretim_MalToplama_BelgeTipleri")
  List<String>? uretimMalToplamaBelgeTipleri;
  @JsonKey(name: "uretim_MalToplama_ReceteFiltresi")
  String? uretimMalToplamaReceteFiltresi;
  @JsonKey(name: "uretim_MalToplama_ReceteFiltresiSQL")
  String? uretimMalToplamaReceteFiltresiSQL;
  @JsonKey(name: "uretim_IsEmri")
  bool? uretimIsEmri;
  @JsonKey(name: "uretim_IsEmri_Ekle")
  bool? uretimIsEmriEkle;
  @JsonKey(name: "uretim_IsEmri_Duzelt")
  bool? uretimIsEmriDuzelt;
  @JsonKey(name: "uretim_IsEmri_Sil")
  bool? uretimIsEmriSil;
  @JsonKey(name: "taltek_STEK")
  bool? taltekStek;
  @JsonKey(name: "taltek_STEK_Kaydet")
  bool? taltekStekKaydet;
  @JsonKey(name: "taltek_STEK_Duzelt")
  bool? taltekStekDuzelt;
  @JsonKey(name: "taltek_STEK_Sil")
  bool? taltekStekSil;
  @JsonKey(name: "taltek_STEK_KapalilarListenlenmesin")
  bool? taltekStekKapalilarListenlenmesin;
  @JsonKey(name: "taltek_STEK_OnayIslemleri")
  bool? taltekStekOnayIslemleri;
  @JsonKey(name: "taltek_STEK_CariKoduDegistir")
  bool? taltekStekCariKoduDegistir;
  @JsonKey(name: "taltek_STEK_FiyatDegistirilmesin")
  bool? taltekStekFiyatDegistirilmesin;
  @JsonKey(name: "taltek_STEK_Aciklamalar_YetkiTuru")
  String? taltekStekAciklamalarYetkiTuru;
  @JsonKey(name: "taltek_STEK_GizlenecekAlanlar")
  List<dynamic>? taltekStekGizlenecekAlanlar;
  @JsonKey(name: "taltek_STEK_DegismeyecekAlanlar")
  List<dynamic>? taltekStekDegismeyecekAlanlar;
  @JsonKey(name: "taltek_STEK_BosGecilmeyecekAlanlar")
  List<dynamic>? taltekStekBosGecilmeyecekAlanlar;
  @JsonKey(name: "taltek_STEK_AciklamaAlanlari")
  List<int>? taltekStekAciklamaAlanlari;
  @JsonKey(name: "taltek_STEK_OzelKod1degeri")
  String? taltekStekOzelKod1degeri;
  @JsonKey(name: "taltek_STEK_DipFiyatUygulamasi")
  bool? taltekStekDipFiyatUygulamasi;
  @JsonKey(name: "taltek_STEK_DipFiyatSaha")
  String? taltekStekDipFiyatSaha;
  @JsonKey(name: "taltek_STEK_DipFiyatEylem")
  String? taltekStekDipFiyatEylem;
  @JsonKey(name: "taltek_ATAL")
  bool? taltekAtal;
  @JsonKey(name: "taltek_ATAL_Kaydet")
  bool? taltekAtalKaydet;
  @JsonKey(name: "taltek_ATAL_Duzelt")
  bool? taltekAtalDuzelt;
  @JsonKey(name: "taltek_ATAL_Sil")
  bool? taltekAtalSil;
  @JsonKey(name: "taltek_ATAL_CariEMailAlani")
  String? taltekAtalCariEMailAlani;
  @JsonKey(name: "taltek_ATAL_OnayIslemleri")
  bool? taltekAtalOnayIslemleri;
  @JsonKey(name: "taltek_ATAL_CariKoduDegistir")
  bool? taltekAtalCariKoduDegistir;
  @JsonKey(name: "taltek_ATAL_Aciklamalar_YetkiTuru")
  String? taltekAtalAciklamalarYetkiTuru;
  @JsonKey(name: "taltek_ATAL_GizlenecekAlanlar")
  List<String>? taltekAtalGizlenecekAlanlar;
  @JsonKey(name: "taltek_ATAL_AciklamaAlanlari")
  List<int>? taltekAtalAciklamaAlanlari;
  @JsonKey(name: "taltek_ATAL_BelgeKopyala")
  bool? taltekAtalBelgeKopyala;
  @JsonKey(name: "taltek_STAL")
  bool? taltekStal;
  @JsonKey(name: "taltek_STAL_Kaydet")
  bool? taltekStalKaydet;
  @JsonKey(name: "taltek_STAL_Duzelt")
  bool? taltekStalDuzelt;
  @JsonKey(name: "taltek_STAL_Sil")
  bool? taltekStalSil;
  @JsonKey(name: "taltek_STAL_KapalilarListenlenmesin")
  bool? taltekStalKapalilarListenlenmesin;
  @JsonKey(name: "taltek_STAL_OnayIslemleri")
  bool? taltekStalOnayIslemleri;
  @JsonKey(name: "taltek_STAL_CariKoduDegistir")
  bool? taltekStalCariKoduDegistir;
  @JsonKey(name: "taltek_STAL_FiyatDegistirilmesin")
  bool? taltekStalFiyatDegistirilmesin;
  @JsonKey(name: "taltek_STAL_GizlenecekAlanlar")
  List<String>? taltekStalGizlenecekAlanlar;
  @JsonKey(name: "taltek_STAL_DipFiyatUygulamasi")
  bool? taltekStalDipFiyatUygulamasi;
  @JsonKey(name: "ebelge_EFat")
  bool? ebelgeEFat;
  @JsonKey(name: "ebelge_EFatCariGuncelle")
  bool? ebelgeEFatCariGuncelle;
  @JsonKey(name: "ebelge_EFatSorgula")
  bool? ebelgeEFatSorgula;
  @JsonKey(name: "ebelge_EFatGelenKutusu")
  bool? ebelgeEFatGelenKutusu;
  @JsonKey(name: "ebelge_EFatTaslakOlustur")
  bool? ebelgeEFatTaslakOlustur;
  @JsonKey(name: "ebelge_EFatTaslakSil")
  bool? ebelgeEFatTaslakSil;
  @JsonKey(name: "ebelge_EFatTaslakBasim")
  bool? ebelgeEFatTaslakBasim;
  @JsonKey(name: "ebelge_EFatGoruntule")
  bool? ebelgeEFatGoruntule;
  @JsonKey(name: "ebelge_EFatAlisFatOlustur")
  bool? ebelgeEFatAlisFatOlustur;
  @JsonKey(name: "ebelge_EFatGonder")
  bool? ebelgeEFatGonder;
  @JsonKey(name: "ebelge_EFat_Dizayn")
  int? ebelgeEFatDizayn;
  @JsonKey(name: "ebelge_EArsiv")
  bool? ebelgeEArsiv;
  @JsonKey(name: "ebelge_EArsivTaslakOlustur")
  bool? ebelgeEArsivTaslakOlustur;
  @JsonKey(name: "ebelge_EArsivTaslakSil")
  bool? ebelgeEArsivTaslakSil;
  @JsonKey(name: "ebelge_EArsivTaslakBasim")
  bool? ebelgeEArsivTaslakBasim;
  @JsonKey(name: "ebelge_EArsivGoruntule")
  bool? ebelgeEArsivGoruntule;
  @JsonKey(name: "ebelge_EArsivSorgula")
  bool? ebelgeEArsivSorgula;
  @JsonKey(name: "ebelge_EArsivGonder")
  bool? ebelgeEArsivGonder;
  @JsonKey(name: "ebelge_EArsiv_Dizayn")
  int? ebelgeEArsivDizayn;
  @JsonKey(name: "ebelge_EIrsaliye")
  bool? ebelgeEIrsaliye;
  @JsonKey(name: "ebelge_EFatGidenKutusu")
  bool? ebelgeEFaturaGidenKutusu;
  @JsonKey(name: "ebelge_EIrsaliyeGidenKutusu")
  bool? ebelgeEIrsaliyeGidenKutusu;
  @JsonKey(name: "ebelge_EIrsaliyeGelenKutusu")
  bool? ebelgeEIrsaliyeGelenKutusu;
  @JsonKey(name: "ebelge_EIrsaliyeTaslakOlustur")
  bool? ebelgeEIrsaliyeTaslakOlustur;
  @JsonKey(name: "ebelge_EIrsaliyeTaslakSil")
  bool? ebelgeEIrsaliyeTaslakSil;
  @JsonKey(name: "ebelge_EIrsaliyeTaslakBasim")
  bool? ebelgeEIrsaliyeTaslakBasim;
  @JsonKey(name: "ebelge_EIrsaliyeGonder")
  bool? ebelgeEIrsaliyeGonder;
  @JsonKey(name: "ebelge_EIrsaliyeGoruntule")
  bool? ebelgeEIrsaliyeGoruntule;
  @JsonKey(name: "ebelge_EIrsaliye_Dizayn")
  int? ebelgeEIrsaliyeDizayn;
  @JsonKey(name: "entegrasyon_UETDSESYA")
  bool? entegrasyonUetdsesya;
  @JsonKey(name: "entegrasyon_UETDSESYA_Iptal")
  bool? entegrasyonUetdsesyaIptal;
  @JsonKey(name: "transfer_DAT_TekrarEdenBarkod")
  String? transferDatTekrarEdenBarkod;
  @JsonKey(name: "transfer_DAT_AciklamaDuzenle")
  bool? transferDatAciklamaDuzenle;
  @JsonKey(name: "transfer_DAT_LokalDATSeciliGelmesin")
  bool? transferDatLokalDatSeciliGelmesin;
  @JsonKey(name: "transfer_DAT_VarsayilanHarTuruDegistiremesin")
  bool? transferDatVarsayilanHarTuruDegistiremesin;
  @JsonKey(name: "transfer_DAT_DepoCaridenGelsin")
  bool? transferDatDepoCaridenGelsin;
  @JsonKey(name: "transfer_AG_SipBagSecenegi")
  String? transferAgSipBagSecenegi;
  @JsonKey(name: "transfer_AG_TekrarEdenBarkod")
  String? transferAgTekrarEdenBarkod;
  @JsonKey(name: "transfer_AG_AciklamaDuzenle")
  bool? transferAgAciklamaDuzenle;
  @JsonKey(name: "transfer_AC_SipBagSecenegi")
  String? transferAcSipBagSecenegi;
  @JsonKey(name: "transfer_AC_TekrarEdenBarkod")
  String? transferAcTekrarEdenBarkod;
  @JsonKey(name: "transfer_AC_AciklamaDuzenle")
  bool? transferAcAciklamaDuzenle;
  @JsonKey(name: "transfer_DepoTalebi_Bildirim")
  bool? transferDepoTalebiBildirim;
  @JsonKey(name: "uretim_USK")
  bool? uretimUsk;
  @JsonKey(name: "malKabul_AlisIrs_DegismeyecekAlanlar")
  List<dynamic>? malKabulAlisIrsDegismeyecekAlanlar;
  @JsonKey(name: "malKabul_AlisIrs_AciklamaDuzenle")
  bool? malKabulAlisIrsAciklamaDuzenle;
  @JsonKey(name: "malKabul_AlisFat_AciklamaDuzenle")
  bool? malKabulAlisFatAciklamaDuzenle;
  @JsonKey(name: "malKabul_AlisFat_TekrarEdenBarkod")
  String? malKabulAlisFatTekrarEdenBarkod;
  @JsonKey(name: "malKabul_AlisFaturasi_SipBagSecenegi")
  String? malKabulAlisFaturasiSipBagSecenegi;
  @JsonKey(name: "sevkiyat_SatisIrs_VarsayilanBelgeTipi")
  int? sevkiyatSatisIrsVarsayilanBelgeTipi;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesi_AciklamaAlanlari")
  List<int>? sevkiyatSatisIrsaliyesiAciklamaAlanlari;
  @JsonKey(name: "sevkiyat_SatisIrsaliyesi_AciklamaDuzenle")
  bool? sevkiyatSatisIrsaliyesiAciklamaDuzenle;
  @JsonKey(name: "sevkiyat_SatisIrs_KayittanSonraTaslakOlustur")
  bool? sevkiyatSatisIrsKayittanSonraTaslakOlustur;
  @JsonKey(name: "sevkiyat_SatisIrs_IadeMiktariGirebilir")
  bool? sevkiyatSatisIrsIadeMiktariGirebilir;
  @JsonKey(name: "sevkiyat_SatisIrs_IadeMiktariGirebilirFarkliDepo")
  bool? sevkiyatSatisIrsIadeMiktariGirebilirFarkliDepo;
  @JsonKey(name: "sevkiyat_SatisIrs_TekrarEdenBarkod")
  String? sevkiyatSatisIrsTekrarEdenBarkod;
  @JsonKey(name: "sevkiyat_SatisFat_AciklamaDuzenle")
  bool? sevkiyatSatisFatAciklamaDuzenle;
  @JsonKey(name: "sevkiyat_SatisFat_IadeMiktariGirebilir")
  bool? sevkiyatSatisFatIadeMiktariGirebilir;
  @JsonKey(name: "sevkiyat_SatisFat_IadeMiktariGirebilirFarkliDepo")
  bool? sevkiyatSatisFatIadeMiktariGirebilirFarkliDepo;
  @JsonKey(name: "sevkiyat_SatisFaturasi_TekrarEdenBarkod")
  String? sevkiyatSatisFaturasiTekrarEdenBarkod;
  @JsonKey(name: "sevkemri_MalToplama_Yontemi")
  String? sevkemriMalToplamaYontemi;
  @JsonKey(name: "sayim_SerbestSayimFiltreIslem")
  String? sayimSerbestSayimFiltreIslem;
  @JsonKey(name: "siparis_MusSip_BelgeKopyala")
  bool? siparisMusSipBelgeKopyala;
  @JsonKey(name: "siparis_MusSip_TekrarEdenBarkod")
  String? siparisMusSipTekrarEdenBarkod;
  @JsonKey(name: "siparis_MusSip_KacGunlukKayitlarListelensin")
  int? siparisMusSipKacGunlukKayitlarListelensin;
  @JsonKey(name: "siparis_MusteriSiparisi_AciklamaDuzenle")
  bool? siparisMusteriSiparisiAciklamaDuzenle;
  @JsonKey(name: "stok_FiltreSQLTipi")
  String? stokFiltreSqlTipi;
  @JsonKey(name: "stok_FiyatGorEkrani_GunlukKurdanTLGoster")
  bool? stokFiyatGorEkraniGunlukKurdanTlGoster;
  @JsonKey(name: "stok_Paketleme_Coklu")
  bool? stokPaketlemeCoklu;
  @JsonKey(name: "stok_RehberBakiyesindeDigerOlcuBirimleriGorunsun")
  bool? stokRehberBakiyesindeDigerOlcuBirimleriGorunsun;
  @JsonKey(name: "stok_YazdirPdfGoruntule")
  bool? stokYazdirPdfGoruntule;
  @JsonKey(name: "cari_ToplamGorunmesin")
  bool? cariToplamGorunmesin;
  @JsonKey(name: "cari_BakiyeGosterim")
  String? cariBakiyeGosterim;
  @JsonKey(name: "cari_FiltreSQLTipi")
  String? cariFiltreSqlTipi;
  @JsonKey(name: "tahsilat_DovizKuru_Degeri")
  String? tahsilatDovizKuruDegeri;
  @JsonKey(name: "tahsilat_DovizKuru_Yetki")
  String? tahsilatDovizKuruYetki;
  @JsonKey(name: "tahsilat_DovizKuru_Tolerans")
  double? tahsilatDovizKuruTolerans;
  @JsonKey(name: "finans_Raporlar_KasaEkstre")
  bool? finansRaporlarKasaEkstre;
  @JsonKey(name: "finans_Kasa_GizlenecekAlanlar")
  List<dynamic>? finansKasaGizlenecekAlanlar;
  @JsonKey(name: "finans_Kasa_DegistirilemeyecekAlanlar")
  List<dynamic>? finansKasaDegistirilemeyecekAlanlar;
  @JsonKey(name: "finans_Kasa_BosGecilemeyecekAlanlar")
  List<dynamic>? finansKasaBosGecilemeyecekAlanlar;
  @JsonKey(name: "taltek_STEK_AciklamaDuzenle")
  bool? taltekStekAciklamaDuzenle;
  @JsonKey(name: "taltek_STEK_DipFiyatKDVDurumu")
  String? taltekStekDipFiyatKdvDurumu;
  @JsonKey(name: "taltek_STAL_AciklamaDuzenle")
  bool? taltekStalAciklamaDuzenle;
  @JsonKey(name: "taltek_STAL_DipFiyatSaha")
  String? taltekStalDipFiyatSaha;
  @JsonKey(name: "taltek_STAL_DipFiyatEylem")
  String? taltekStalDipFiyatEylem;
  @JsonKey(name: "taltek_STAL_DipFiyatKDVDurumu")
  String? taltekStalDipFiyatKdvDurumu;
  @JsonKey(name: "malKabul_AlisIrs_Birim1denKaydet")
  bool? malKabulAlisIrsBirim1DenKaydet;
  @JsonKey(name: "malKabul_AlisFat_Birim1denKaydet")
  bool? malKabulAlisFatBirim1DenKaydet;
  @JsonKey(name: "transfer_AG_Birim1denKaydet")
  bool? transferAgBirim1DenKaydet;
  @JsonKey(name: "transfer_AC_Birim1denKaydet")
  bool? transferAcBirim1DenKaydet;
  @JsonKey(name: "sevkiyat_SatisIrs_KDVSifirGelsin")
  bool? sevkiyatSatisIrsKdvSifirGelsin;
  @JsonKey(name: "sevkiyat_SatisIrs_Birim1denKaydet")
  bool? sevkiyatSatisIrsBirim1DenKaydet;
  @JsonKey(name: "sevkiyat_SatisIrs_DipFiyatKDVDurumu")
  String? sevkiyatSatisIrsDipFiyatKdvDurumu;
  @JsonKey(name: "sevkiyat_SatisFat_Birim1denKaydet")
  bool? sevkiyatSatisFatBirim1DenKaydet;
  @JsonKey(name: "siparis_MusteriSiparisi_DipFiyatKDVDurumu")
  String? siparisMusteriSiparisiDipFiyatKdvDurumu;
  @JsonKey(name: "siparis_SatSip_TekrarEdenBarkod")
  String? siparisSatSipTekrarEdenBarkod;
  @JsonKey(name: "siparis_SatSip_KacGunlukKayitlarListelensin")
  int? siparisSatSipKacGunlukKayitlarListelensin;
  @JsonKey(name: "cari_Rap_BorcAlacakDokumu")
  bool? cariRapBorcAlacakDokumu;

  factory ProfilYetkiModel.fromJson(String json) => _$ProfilYetkiModelFromJson(jsonDecode(json));

  Map<String, dynamic> toJson() => _$ProfilYetkiModelToJson(this);

  @override
  String toString() => toJson().toString();
}

@JsonSerializable(fieldRename: FieldRename.pascal)
class SevkemriMalKontrolTipi {
  int? kod;
  String? tanim;

  SevkemriMalKontrolTipi();

  factory SevkemriMalKontrolTipi.fromJson(Map<String, dynamic> json) => _$SevkemriMalKontrolTipiFromJson(json);

  Map<String, dynamic> toJson() => _$SevkemriMalKontrolTipiToJson(this);
}
