# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = "gsbb-uybx-zqnj-ketk"
update_fastlane

default_platform(:android)

platform :android do
  desc "Firebase deploy"
  lane :firebase do
    sh("fb_apk")
    firebase_app_distribution(
      app: "com.bracket23.picker",
      groups: "com.bracket23.picker",
      release_notes: "New features and bug fixes",
      debug: false)
  end
end
platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    # gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
