// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'banka_hareketleri_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_BankaHareketleriModel _$BankaHareketleriModelFromJson(
  Map<String, dynamic> json,
) => _BankaHareketleriModel(
  inckeyno: (json['INCKEYNO'] as num?)?.toInt(),
  netheskodu: json['NETHESKODU'] as String?,
  tarih: json['TARIH'] == null ? null : DateTime.parse(json['TARIH'] as String),
  harturu: (json['HARTURU'] as num?)?.toInt(),
  ba: json['BA'] as String?,
  tutar: (json['TUTAR'] as num?)?.toDouble(),
  aciklama: json['ACIKLAMA'] as String?,
  entegrefkey: json['ENTEGREFKEY'] as String?,
  dovizTipi: (json['DOVIZ_TIPI'] as num?)?.toInt(),
  dovizTutari: (json['DOVIZ_TUTARI'] as num?)?.toDouble(),
  hareketTipi: (json['HAREKET_TIPI'] as num?)?.toInt(),
  hesapAdi: json['HESAP_ADI'] as String?,
  hareketAciklama: json['HAREKET_ACIKLAMA'] as String?,
  bankaKodu: json['BANKA_KODU'] as String?,
  bankaAdi: json['BANKA_ADI'] as String?,
  bankasubeKodu: json['BANKASUBE_KODU'] as String?,
  subeAdi: json['SUBE_ADI'] as String?,
  belgeno: json['BELGENO'] as String?,
  dovizAdi: json['DOVIZ_ADI'] as String?,
  cariKodu: json['CARI_KODU'] as String?,
  cariAdi: json['CARI_ADI'] as String?,
  belgeNo: json['BELGE_NO'] as String?,
  kasaKodu: json['KASA_KODU'] as String?,
  kasaAdi: json['KASA_ADI'] as String?,
  entegreKasaKodu: json['ENTEGRE_KASA_KODU'] as String?,
  sozlesmeKodu: json['SOZLESME_KODU'] as String?,
  projeKodu: json['PROJE_KODU'] as String?,
  projeAciklama: json['PROJE_ACIKLAMA'] as String?,
  plasiyerKodu: json['PLASIYER_KODU'] as String?,
  plasiyerAdi: json['PLASIYER_ADI'] as String?,
  nakitmi: json['NAKITMI'] as String?,
  taksitSayisi: (json['TAKSIT_SAYISI'] as num?)?.toInt(),
);

Map<String, dynamic> _$BankaHareketleriModelToJson(
  _BankaHareketleriModel instance,
) => <String, dynamic>{
  'INCKEYNO': ?instance.inckeyno,
  'NETHESKODU': ?instance.netheskodu,
  'TARIH': ?instance.tarih?.toIso8601String(),
  'HARTURU': ?instance.harturu,
  'BA': ?instance.ba,
  'TUTAR': ?instance.tutar,
  'ACIKLAMA': ?instance.aciklama,
  'ENTEGREFKEY': ?instance.entegrefkey,
  'DOVIZ_TIPI': ?instance.dovizTipi,
  'DOVIZ_TUTARI': ?instance.dovizTutari,
  'HAREKET_TIPI': ?instance.hareketTipi,
  'HESAP_ADI': ?instance.hesapAdi,
  'HAREKET_ACIKLAMA': ?instance.hareketAciklama,
  'BANKA_KODU': ?instance.bankaKodu,
  'BANKA_ADI': ?instance.bankaAdi,
  'BANKASUBE_KODU': ?instance.bankasubeKodu,
  'SUBE_ADI': ?instance.subeAdi,
  'BELGENO': ?instance.belgeno,
  'DOVIZ_ADI': ?instance.dovizAdi,
  'CARI_KODU': ?instance.cariKodu,
  'CARI_ADI': ?instance.cariAdi,
  'BELGE_NO': ?instance.belgeNo,
  'KASA_KODU': ?instance.kasaKodu,
  'KASA_ADI': ?instance.kasaAdi,
  'ENTEGRE_KASA_KODU': ?instance.entegreKasaKodu,
  'SOZLESME_KODU': ?instance.sozlesmeKodu,
  'PROJE_KODU': ?instance.projeKodu,
  'PROJE_ACIKLAMA': ?instance.projeAciklama,
  'PLASIYER_KODU': ?instance.plasiyerKodu,
  'PLASIYER_ADI': ?instance.plasiyerAdi,
  'NAKITMI': ?instance.nakitmi,
  'TAKSIT_SAYISI': ?instance.taksitSayisi,
};
